# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: extract
defmodule E2e.ExtractTest do
  use ExUnit.Case, async: false

  describe "extract_bytes_input" do
    test "extract_bytes_input" do
      input_value = %Xberg.ExtractInput{
        bytes: File.read!("test_documents/pdf/fake_memo.pdf"),
        filename: "fake_memo.pdf",
        kind: "bytes",
        mime_type: "application/pdf"
      }

      {:ok, result} = Xberg.extract(input: input_value)
      assert String.trim(Enum.at(result.results, 0).mime_type) == "application/pdf"

      assert (is_binary(Enum.at(result.results, 0).content) && byte_size(Enum.at(result.results, 0).content) >= 50) ||
               (is_list(Enum.at(result.results, 0).content) && length(Enum.at(result.results, 0).content) >= 50)
    end
  end

  describe "extract_bytes_input_empty_mime" do
    test "extract_bytes_input_empty_mime" do
      input_value = %Xberg.ExtractInput{
        bytes: File.read!("test_documents/text/plain.txt"),
        config: %{},
        filename: "plain.txt",
        kind: "bytes",
        mime_type: ""
      }

      assert {:error, _} = Xberg.extract(input: input_value, config: "{}")
    end
  end

  describe "extract_bytes_input_invalid_mime" do
    test "extract_bytes_input_invalid_mime" do
      input_value = %Xberg.ExtractInput{
        bytes: File.read!("test_documents/text/plain.txt"),
        config: %{},
        filename: "plain.txt",
        kind: "bytes",
        mime_type: "application/x-nonexistent"
      }

      assert {:error, _} = Xberg.extract(input: input_value, config: "{}")
    end
  end
end
