# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.BedrockConfig do
  @moduledoc """
  AWS Bedrock configuration for `bedrock/`-prefixed models.

  Mirrors liter-llm's `BedrockConfig`. Every field is optional: anything left
  unset falls back to the standard AWS environment variables
  (`AWS_DEFAULT_REGION` / `AWS_REGION`, `AWS_ACCESS_KEY_ID`,
  `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN`, `BEDROCK_CROSS_REGION`) and the
  default AWS credential chain. Leave the credential fields unset unless you
  have an explicit reason to pin them.

  # Example

  ```toml
  [ocr.vlm_config]
  model = "bedrock/anthropic.claude-3-sonnet-20240229-v1:0"

  [ocr.vlm_config.bedrock]
  region = "eu-central-1"
  cross_region_prefix = "eu"
  ```

  `Debug` is implemented by hand so the three credential fields are never printed.
  """

  @typedoc "AWS Bedrock configuration for `bedrock/`-prefixed models."
  @type t :: %__MODULE__{
          region: String.t() | nil,
          cross_region_prefix: String.t() | nil,
          access_key_id: String.t() | nil,
          secret_access_key: String.t() | nil,
          session_token: String.t() | nil
        }

  defstruct region: nil,
            cross_region_prefix: nil,
            access_key_id: nil,
            secret_access_key: nil,
            session_token: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
