# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ChunkClassificationDefinition do
  @moduledoc """
  A single labeled definition the chunk classifier may emit.

  Unlike `PageClassificationConfig::labels` (bare label names), chunk
  classification targets potentially large domain taxonomies where every
  label carries its own semantic description, letting the LLM disambiguate
  similarly named labels without relying on the label string alone.
  """

  @typedoc "A single labeled definition the chunk classifier may emit."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          description: String.t() | nil
        }

  defstruct label: nil,
            description: nil
end
