# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.CsvConfig do
  @moduledoc """
  Configuration for CSV/TSV extraction.

  When unset (`ExtractionConfig::csv == None`), the extractor keeps its
  existing default behavior: the delimiter is auto-detected by sampling the
  file (comma, tab, pipe, or semicolon), and no line is treated as a comment.

  # Example

  ```rust
  use xberg::core::config::CsvConfig;

  let config = CsvConfig {
      delimiter: Some(";".to_string()),
      comment_prefixes: vec!["#".to_string()],
  };
  ```
  """

  @typedoc "Configuration for CSV/TSV extraction."
  @type t :: %__MODULE__{
          delimiter: String.t() | nil,
          comment_prefixes: [String.t()]
        }

  defstruct delimiter: nil,
            comment_prefixes: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
