# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @typedoc "MIME type detection response."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          filename: String.t() | nil
        }

  defstruct mime_type: nil,
            filename: nil
end
