# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.DoctorCheck do
  @moduledoc "A single doctor verdict: what was checked, the outcome, and why."

  @typedoc "A single doctor verdict: what was checked, the outcome, and why."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          status: Xberg.ProbeStatus.t(),
          message: String.t() | nil
        }

  defstruct name: nil,
            status: :pass,
            message: nil
end
