# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: [Xberg.FormattedBlock.t()]
        }

  defstruct label: nil,
            content: []
end
