# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: Xberg.InlineType.t(),
          content: String.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            metadata: nil
end
