# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LateInteractionMatch do
  @moduledoc """
  A single document match returned by [`max_sim_rank`], with its position in
  the input and MaxSim score.

  Since v5.0.0.
  """

  @typedoc "A single document match returned by [`max_sim_rank`], with its position in the input and MaxSim score."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          score: float()
        }

  defstruct index: 0,
            score: 0.0
end
