# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.LateInteractionConfig do
  @moduledoc """
  Configuration for the late-interaction (ColBERT) pipeline.

  Controls which model to use, batching, and download/cache behavior for the
  local ONNX ColBERT model.

  Since v5.0.0.
  """

  @typedoc "Configuration for the late-interaction (ColBERT) pipeline."
  @type t :: %__MODULE__{
          model: Xberg.LateInteractionModelType.t(),
          batch_size: non_neg_integer(),
          max_length: non_neg_integer(),
          query_max_length: non_neg_integer(),
          show_download_progress: boolean(),
          cache_dir: String.t() | nil,
          acceleration: Xberg.AccelerationConfig.t() | nil,
          max_embed_duration_secs: non_neg_integer() | nil
        }

  defstruct model: nil,
            batch_size: nil,
            max_length: nil,
            query_max_length: nil,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_embed_duration_secs: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
