# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.MultidocInput do
  @moduledoc "Input signals for multi-document boundary detection."

  @typedoc "Input signals for multi-document boundary detection."
  @type t :: %__MODULE__{
          page_count: non_neg_integer(),
          pages: [Xberg.PageSignals.t()]
        }

  defstruct page_count: 0,
            pages: []
end
