# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.NerConfig do
  @moduledoc "Configuration for the NER post-processor."

  @typedoc "Configuration for the NER post-processor."
  @type t :: %__MODULE__{
          backend: Xberg.NerBackendKind.t(),
          categories: [Xberg.EntityCategory.t()],
          model: String.t() | nil,
          llm: Xberg.LlmConfig.t() | nil,
          custom_labels: [String.t()]
        }

  defstruct backend: :onnx,
            categories: [],
            model: nil,
            llm: nil,
            custom_labels: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
