# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.OutputFormat do
  @moduledoc """
  Output format for extraction results.

  Controls the format of the `content` field in `ExtractedDocument`.
  When set to `Markdown`, `Djot`, or `Html`, the output uses that format.
  `Plain` returns the raw extracted text.
  `Structured` is currently a metadata-only label: `derive_extraction_result`
  returns `None` for it (see `extraction/derive.rs`), so no renderer runs and
  the content is left exactly as `Plain` would leave it. Only
  `metadata.output_format` differs. It does NOT attach OCR element data,
  bounding boxes or confidence scores.
  """

  @typedoc "Output format for extraction results."
  @type t :: term()

  @typedoc "Plain text content only (default)"
  @type plain :: :plain
  @typedoc "Markdown format"
  @type markdown :: :markdown
  @typedoc "Djot markup format"
  @type djot :: :djot
  @typedoc "HTML format"
  @type html :: :html
  @typedoc "JSON tree format with heading-driven sections."
  @type json :: :json
  @typedoc "Metadata-only label; content is identical to [`OutputFormat::Plain`]. No dedicated renderer exists yet, so this attaches no OCR element metadata. See the enum-level docs above."
  @type structured :: :structured
  @typedoc "Docling DocTags format (tables rendered as OTSL)."
  @type doc_tags :: :doc_tags
  @typedoc "Custom renderer registered via the RendererRegistry. The string is the renderer name (e.g., \"docx\", \"latex\")."
  @type custom :: %{type: :custom, value: String.t()}
end
