# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PdfAnnotationType do
  @moduledoc "Type of PDF annotation."

  @typedoc "Type of PDF annotation."
  @type t ::
          :text
          | :highlight
          | :link
          | :stamp
          | :underline
          | :strike_out
          | :squiggly
          | :ink
          | :square
          | :circle
          | :polygon
          | :poly_line
          | :line
          | :caret
          | :file_attachment
          | :sound
          | :movie
          | :other

  @text :text
  @highlight :highlight
  @link :link
  @stamp :stamp
  @underline :underline
  @strike_out :strike_out
  @squiggly :squiggly
  @ink :ink
  @square :square
  @circle :circle
  @polygon :polygon
  @poly_line :poly_line
  @line :line
  @caret :caret
  @file_attachment :file_attachment
  @sound :sound
  @movie :movie
  @other :other

  @doc "Sticky note / text annotation"
  @spec text() :: t()
  def text, do: @text
  @doc "Highlighted text region"
  @spec highlight() :: t()
  def highlight, do: @highlight
  @doc "Hyperlink annotation"
  @spec link() :: t()
  def link, do: @link
  @doc "Rubber stamp annotation"
  @spec stamp() :: t()
  def stamp, do: @stamp
  @doc "Underline text markup"
  @spec underline() :: t()
  def underline, do: @underline
  @doc "Strikeout text markup"
  @spec strike_out() :: t()
  def strike_out, do: @strike_out
  @doc "Squiggly (wavy) underline text markup"
  @spec squiggly() :: t()
  def squiggly, do: @squiggly
  @doc "Freehand drawing (ink) annotation"
  @spec ink() :: t()
  def ink, do: @ink
  @doc "Rectangle/box shape annotation"
  @spec square() :: t()
  def square, do: @square
  @doc "Ellipse/oval shape annotation"
  @spec circle() :: t()
  def circle, do: @circle
  @doc "Closed polygon shape annotation"
  @spec polygon() :: t()
  def polygon, do: @polygon
  @doc "Open polyline shape annotation"
  @spec poly_line() :: t()
  def poly_line, do: @poly_line
  @doc "Line annotation"
  @spec line() :: t()
  def line, do: @line
  @doc "Caret (text-insertion marker) annotation"
  @spec caret() :: t()
  def caret, do: @caret
  @doc "Embedded file attachment annotation"
  @spec file_attachment() :: t()
  def file_attachment, do: @file_attachment
  @doc "Embedded sound annotation"
  @spec sound() :: t()
  def sound, do: @sound
  @doc "Embedded movie annotation"
  @spec movie() :: t()
  def movie, do: @movie
  @doc "Any other annotation type"
  @spec other() :: t()
  def other, do: @other
end
