# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.PresetSummary do
  @moduledoc """
  Lightweight projection of [`Preset`] used by the registry list endpoint
  (omits the full schema and prompt to keep the payload small).
  """

  @typedoc "Lightweight projection of [`Preset`] used by the registry list endpoint (omits the full schema and prompt to keep the payload small)."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          version: String.t() | nil,
          schema_name: String.t() | nil,
          description: String.t() | nil,
          category: Xberg.PresetCategory.t(),
          tags: [String.t()],
          preferred_call_mode: Xberg.CallMode.t(),
          emit_citations: boolean(),
          fingerprint: String.t() | nil
        }

  defstruct id: nil,
            version: nil,
            schema_name: nil,
            description: nil,
            category: :finance,
            tags: [],
            preferred_call_mode: :text_only,
            emit_citations: false,
            fingerprint: nil
end
