# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.ProbeStatus do
  @moduledoc "Outcome of a single doctor check."

  @typedoc "Outcome of a single doctor check."
  @type t :: :pass | :warn | :fail | :skip

  @pass :pass
  @warn :warn
  @fail :fail
  @skip :skip

  @doc "The backend or setting will work as configured."
  @spec pass() :: t()
  def pass, do: @pass
  @doc "The check ran and found something actionable, but nothing is broken (e.g. stray cache files, stale model revisions). Never fails the report."
  @spec warn() :: t()
  def warn, do: @warn
  @doc "The configured setup will not work (or will silently degrade) on this host."
  @spec fail() :: t()
  def fail, do: @fail
  @doc "The check cannot run locally (e.g. model not cached, feature not compiled in); first real use decides, possibly after a download."
  @spec skip() :: t()
  def skip, do: @skip
end
