# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule Xberg.RedactionFinding do
  @moduledoc "One redaction event: which span was rewritten, why, and with what."

  @typedoc "One redaction event: which span was rewritten, why, and with what."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          category: Xberg.PiiCategory.t(),
          strategy: Xberg.RedactionStrategy.t(),
          replacement_token: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            category: :email,
            strategy: :mask,
            replacement_token: nil
end
