<?php

// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify

declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\ExtractionConfig;
use Xberg\Xberg;

/** E2e tests for category: registry. */
final class RegistryTest extends TestCase
{
    /** List embedding backends */
    public function test_list_embedding_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listEmbeddingBackends();
    }

    /** List OCR backends */
    public function test_list_ocr_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listOcrBackends();
    }

    /** List post-processors */
    public function test_list_post_processors(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listPostProcessors();
    }

    /** List renderers */
    public function test_list_renderers(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listRenderers();
    }

    /** List validators */
    public function test_list_validators(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listValidators();
    }
}
