<?php

// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify

declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\ExtractionConfig;
use Xberg\Xberg;

/** E2e tests for category: reranker_backend_management. */
final class RerankerBackendManagementTest extends TestCase
{
    /** Clear all reranker backends and verify list is empty */
    public function test_clear_reranker_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearRerankerBackends();
    }

    /** List all registered reranker backends */
    public function test_list_reranker_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listRerankerBackends();
    }
}
