<?php

// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify

declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\ExtractionConfig;
use Xberg\Xberg;

/** E2e tests for category: validator_management. */
final class ValidatorManagementTest extends TestCase
{
    /** Clear all validators and verify list is empty */
    public function test_validators_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearValidators();
    }

    /** List all registered validators */
    public function test_validators_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listValidators();
    }
}
