// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import io.xberg.ExtractionConfig
import io.xberg.ExtractInput

/** E2e tests for category: code. */
class CodeTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true")
            }
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testCodeShebangDetection() = runBlocking {
        // Test language detection from shebang line via bytes input
        val inputMockBaseUrl = System.getProperty("mockServer.code_shebang_detection", System.getenv("MOCK_SERVER_CODE_SHEBANG_DETECTION") ?: ((System.getProperty("mockServerUrl", System.getenv("MOCK_SERVER_URL") ?: "") ?: "") + "/fixtures/code_shebang_detection"))
        val inputJson = "{\"kind\":\"uri\",\"mime_type\":\"text/x-source-code\",\"uri\":\"\$mock_url/code/script.sh\"}".replace("\$mock_url", inputMockBaseUrl)
        val input = MAPPER.readValue(inputJson, ExtractInput::class.java)
        val input = MAPPER.readValue("{\"kind\":\"uri\",\"mime_type\":\"text/x-source-code\",\"uri\":\"\$mock_url/code/script.sh\"}", ExtractInput::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
        assertEquals("text/x-source-code", result.results.first().mimeType)
        assertTrue(result.results.first().content.length >= 10, "expected length >= 10")
        assertTrue(result.results.first().content.contains("build"), "expected to contain: " + "build")
        assertTrue(result.results.first().content.contains("clean"), "expected to contain: " + "clean")
    }

}
