// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// AWS Bedrock configuration for `bedrock/`-prefixed models.
///
/// Mirrors liter-llm's `BedrockConfig`. Every field is optional: anything left
/// unset falls back to the standard AWS environment variables
/// (`AWS_DEFAULT_REGION` / `AWS_REGION`, `AWS_ACCESS_KEY_ID`,
/// `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN`, `BEDROCK_CROSS_REGION`) and the
/// default AWS credential chain. Leave the credential fields unset unless you
/// have an explicit reason to pin them.
/// </summary>
public sealed record BedrockConfig
{
    /// <summary>
    /// AWS region (e.g. `"us-east-1"`).
    /// </summary>
    [JsonPropertyName("region")]
    public string? Region { get; init; } = null;

    /// <summary>
    /// Cross-region inference profile prefix (e.g. `"us"`).
    /// </summary>
    [JsonPropertyName("cross_region_prefix")]
    public string? CrossRegionPrefix { get; init; } = null;

    /// <summary>
    /// Explicit AWS access key ID. Secret — never logged.
    /// </summary>
    [JsonPropertyName("access_key_id")]
    public string? AccessKeyId { get; init; } = null;

    /// <summary>
    /// Explicit AWS secret access key. Secret — never logged.
    /// </summary>
    [JsonPropertyName("secret_access_key")]
    public string? SecretAccessKey { get; init; } = null;

    /// <summary>
    /// Explicit AWS session token for temporary credentials. Secret — never logged.
    /// </summary>
    [JsonPropertyName("session_token")]
    public string? SessionToken { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="BedrockConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static BedrockConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<BedrockConfig>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse BedrockConfig from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse BedrockConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
