// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Chunking configuration.
///
/// Configures text chunking for document content, including chunk size,
/// overlap, trimming behavior, and optional embeddings.
///
/// Use `..Default.default()` when constructing to allow for future field additions:
/// </summary>
public sealed record ChunkingConfig
{
    /// <summary>
    /// Maximum size per chunk (in units determined by `sizing`).
    ///
    /// When `sizing` is `Characters` (default), this is the max character count.
    /// When using token-based sizing, this is the max token count.
    ///
    /// Default: 1000
    /// </summary>
    [JsonPropertyName("max_chars")]
    public ulong MaxCharacters { get; init; } = 1000;

    /// <summary>
    /// Overlap between chunks (in units determined by `sizing`).
    ///
    /// Default: 200
    /// </summary>
    [JsonPropertyName("max_overlap")]
    public ulong Overlap { get; init; } = 200;

    /// <summary>
    /// Whether to trim whitespace from chunk boundaries.
    ///
    /// Default: true
    /// </summary>
    [JsonPropertyName("trim")]
    public bool Trim { get; init; } = true;

    /// <summary>
    /// Type of chunker to use (Text or Markdown).
    ///
    /// Default: Text
    /// </summary>
    [JsonPropertyName("chunker_type")]
    public ChunkerType ChunkerType { get; init; } = ChunkerType.Text;

    /// <summary>
    /// Optional embedding configuration for chunk embeddings.
    /// </summary>
    [JsonPropertyName("embedding")]
    public EmbeddingConfig? Embedding { get; init; } = null;

    /// <summary>
    /// Optional sparse (SPLADE) embedding configuration for chunk embeddings.
    ///
    /// When set, sparse vectors are generated for each chunk's content and attached
    /// via `sparse_embedding`. Requires the `sparse-embeddings`
    /// feature; without it, a warning is emitted and no sparse vectors are attached.
    ///
    /// Config-file only: like `RerankerConfig` and the local-ONNX branch of
    /// `embedding`, this has no CLI flag and no environment variable. Only the secret/identity
    /// fields of LLM-routed configs (model, API key, base URL) get that reach. ~keep
    /// </summary>
    [JsonPropertyName("sparse_embedding")]
    public SparseEmbeddingConfig? SparseEmbedding { get; init; } = null;

    /// <summary>
    /// Optional late-interaction (ColBERT) embedding configuration for chunk embeddings.
    ///
    /// When set, multi-vector embeddings are generated for each chunk's content and
    /// attached via `late_interaction`. Requires the
    /// `late-interaction` feature; without it, a warning is emitted and no
    /// late-interaction vectors are attached.
    ///
    /// Config-file only, for the same reason as `sparse_embedding` above. ~keep
    /// </summary>
    [JsonPropertyName("late_interaction")]
    public LateInteractionConfig? LateInteraction { get; init; } = null;

    /// <summary>
    /// Use a preset configuration (overrides individual settings if provided).
    /// </summary>
    [JsonPropertyName("preset")]
    public string? Preset { get; init; } = null;

    /// <summary>
    /// How to measure chunk size.
    ///
    /// Default: `Characters` (Unicode character count).
    /// Enable `chunking-tiktoken` or `chunking-tokenizers` features for token-based sizing.
    /// </summary>
    [JsonPropertyName("sizing")]
    public ChunkSizing? Sizing { get; init; } = null;

    /// <summary>
    /// **Deprecated and inert** (#1393): no longer prepends anything into
    /// `content`. Setting this field has no observable effect on chunking output
    /// any more.
    ///
    /// Previously, when `true` and `chunker_type` was `Markdown`, this prepended
    /// the heading hierarchy path (e.g. `"# Title &gt; ## Section\n\n"`) directly
    /// into each chunk's `content` string. `content` now always equals the exact
    /// `[byte_start, byte_end)` source span regardless of this flag — see
    /// `BreadcrumbTarget` for
    /// the full rationale. `heading_context`/`heading_path` on `ChunkMetadata` are
    /// populated independently of this flag, so callers lose no information —
    /// only the in-place mutation is gone.
    ///
    /// Call `render_heading_breadcrumb`
    /// explicitly at index time instead, for the retrieval consumer that wants the
    /// breadcrumb inline.
    ///
    /// Kept only so existing callers keep compiling.
    ///
    /// Default: `false`
    /// </summary>
    [JsonPropertyName("prepend_heading_context")]
    public bool PrependHeadingContext { get; init; } = false;

    /// <summary>
    /// Optional cosine similarity threshold for semantic topic boundary detection.
    ///
    /// Only used when `chunker_type` is `Semantic` and an `EmbeddingConfig` is
    /// provided. You almost never need to set this. When omitted, defaults to
    /// `0.75` which works well for most documents. Lower values detect more
    /// topic boundaries (more, smaller chunks); higher values detect fewer.
    /// Range: `0.0..=1.0`.
    /// </summary>
    [JsonPropertyName("topic_threshold")]
    public float? TopicThreshold { get; init; } = null;

    /// <summary>
    /// How to handle markdown tables that exceed the chunk size limit.
    ///
    /// Only applies when `chunker_type` is `Markdown`.
    ///
    /// * `Split` (default) — tables are split at row boundaries; continuation
    ///   chunks do not repeat the header.
    /// * `RepeatHeader` — the table header row and separator are prepended to
    ///   every continuation chunk so each chunk is self-contained.
    ///
    /// Default: `Split`
    /// </summary>
    [JsonPropertyName("table_chunking")]
    public TableChunkingMode TableChunking { get; init; } = TableChunkingMode.Split;

    /// <summary>
    /// **Deprecated and inert** (#1393): see
    /// `BreadcrumbTarget` for
    /// the full explanation. Neither variant has any effect on `content` any
    /// more — call
    /// `render_heading_breadcrumb`
    /// explicitly at index time instead. Kept only for backward compatibility.
    ///
    /// Default: `Content`.
    /// </summary>
    [JsonPropertyName("breadcrumb_target")]
    public BreadcrumbTarget? BreadcrumbTarget { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="ChunkingConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static ChunkingConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ChunkingConfig>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse ChunkingConfig from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse ChunkingConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
