// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Configuration for CSV/TSV extraction.
///
/// When unset (`ExtractionConfig.csv == None`), the extractor keeps its
/// existing default behavior: the delimiter is auto-detected by sampling the
/// file (comma, tab, pipe, or semicolon), and no line is treated as a comment.
/// </summary>
public sealed record CsvConfig
{
    /// <summary>
    /// Field delimiter, as a single-character string (e.g. `","`, `";"`,
    /// `"\t"`, `"|"`). When `None` (default), the delimiter is auto-detected
    /// from a sample of the file.
    ///
    /// Must be exactly one ASCII byte when set — `ExtractionConfig.validate`
    /// rejects an empty string or a multi-byte value with a helpful error.
    /// The TSV MIME type (`text/tab-separated-values`) always forces `\t`
    /// regardless of this setting.
    /// </summary>
    [JsonPropertyName("delimiter")]
    public string? Delimiter { get; init; } = null;

    /// <summary>
    /// Line prefixes that mark a comment line to skip entirely during row
    /// parsing (e.g. `["#"]`). A line is treated as a comment when its
    /// trimmed start matches any of these prefixes exactly.
    ///
    /// Default: empty, meaning no line is treated as a comment (matches the
    /// pre-existing extractor behavior).
    /// </summary>
    [JsonPropertyName("comment_prefixes")]
    public List<string> CommentPrefixes { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="CsvConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static CsvConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<CsvConfig>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse CsvConfig from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse CsvConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
