// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// A single doctor verdict: what was checked, the outcome, and why.
/// </summary>
public sealed record DoctorCheck
{
    /// <summary>
    /// Check identifier, e.g. `ocr.tesseract` or `layout.rtdetr`.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Pass / warn / fail / skip verdict.
    /// </summary>
    [JsonPropertyName("status")]
    public required ProbeStatus Status { get; init; }

    /// <summary>
    /// One-line reason or detail (e.g. missing language, resolved path, error).
    /// </summary>
    [JsonPropertyName("message")]
    public required string Message { get; init; }


    /// <summary>
    /// Parse a <see cref="DoctorCheck"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static DoctorCheck FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DoctorCheck>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse DoctorCheck from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse DoctorCheck from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>
    /// A `ProbeStatus.Pass` verdict: the checked backend or setting will
    /// </summary>
    public static DoctorCheck Pass(string name, string message)
    {
        var nativeResult = NativeMethods.DoctorCheckPass(name, message);
        var jsonPtr = NativeMethods.DoctorCheckToJson(nativeResult);
        var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.DoctorCheckFree(nativeResult);
        return JsonSerializer.Deserialize<DoctorCheck>(json ?? "null", JsonOptions)!;
    }

    /// <summary>
    /// A `ProbeStatus.Warn` verdict: the check ran and found something
    /// </summary>
    public static DoctorCheck Warn(string name, string message)
    {
        var nativeResult = NativeMethods.DoctorCheckWarn(name, message);
        var jsonPtr = NativeMethods.DoctorCheckToJson(nativeResult);
        var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.DoctorCheckFree(nativeResult);
        return JsonSerializer.Deserialize<DoctorCheck>(json ?? "null", JsonOptions)!;
    }

    /// <summary>
    /// A `ProbeStatus.Fail` verdict: the configured setup will not work (or
    /// </summary>
    public static DoctorCheck Fail(string name, string message)
    {
        var nativeResult = NativeMethods.DoctorCheckFail(name, message);
        var jsonPtr = NativeMethods.DoctorCheckToJson(nativeResult);
        var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.DoctorCheckFree(nativeResult);
        return JsonSerializer.Deserialize<DoctorCheck>(json ?? "null", JsonOptions)!;
    }

    /// <summary>
    /// A `ProbeStatus.Skip` verdict: the check cannot run locally; first
    /// </summary>
    public static DoctorCheck Skip(string name, string message)
    {
        var nativeResult = NativeMethods.DoctorCheckSkip(name, message);
        var jsonPtr = NativeMethods.DoctorCheckToJson(nativeResult);
        var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
        NativeMethods.FreeString(jsonPtr);
        NativeMethods.DoctorCheckFree(nativeResult);
        return JsonSerializer.Deserialize<DoctorCheck>(json ?? "null", JsonOptions)!;
    }
}
