// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Which PDF pages the layout model runs on.
///
/// Layout detection renders each selected page to a raster and runs ONNX
/// inference on it, which dominates extraction cost. This controls page
/// selection; `LayoutStrategy.Always` preserves the historical behavior of
/// running on every page. Wire format is snake_case in all serializers
/// (JSON, TOML, YAML).
/// </summary>
[JsonConverter(typeof(LayoutStrategyJsonConverter))]
public enum LayoutStrategy
{
    /// <summary>
    /// Run layout detection unconditionally on every page.
    /// </summary>
    [JsonPropertyName("always")]
    Always,
    /// <summary>
    /// Pre-screen each page with cheap geometry signals and run the model
    /// only on pages likely to benefit (multi-column, table-bearing,
    /// figure-heavy, form-like, or rotated pages).
    ///
    /// Pages the pre-screen skips are processed exactly like pages where the
    /// model ran and found no regions. On the OCR path only inference is
    /// skipped; page rasters are still produced because OCR consumes them.
    /// For non-PDF inputs `Auto` behaves as `LayoutStrategy.Always`.
    /// </summary>
    [JsonPropertyName("auto")]
    Auto,
}


/// <summary>
/// Custom JSON converter for <see cref="LayoutStrategy"/> that respects explicit variant names.
/// </summary>
internal sealed class LayoutStrategyJsonConverter : JsonConverter<LayoutStrategy>
{
    public override LayoutStrategy Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "always" => LayoutStrategy.Always,
            "auto" => LayoutStrategy.Auto,
            _ => throw new JsonException($"Unknown LayoutStrategy value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, LayoutStrategy value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            LayoutStrategy.Always => "always",
            LayoutStrategy.Auto => "auto",
            _ => throw new JsonException($"Unknown LayoutStrategy value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
