// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Budget enforcement configuration.
///
/// Mirrors liter-llm's `LlmBudgetConfig`. Only takes effect when liter-llm's `tower`
/// feature is compiled in; otherwise the value round-trips through configuration
/// but is not enforced at request time.
/// </summary>
public sealed record LlmBudgetConfig
{
    /// <summary>
    /// Global spend limit in USD.
    /// </summary>
    [JsonPropertyName("global_limit")]
    public double? GlobalLimit { get; init; } = null;

    /// <summary>
    /// Per-model spend limits in USD, keyed by model name.
    /// </summary>
    [JsonPropertyName("model_limits")]
    public Dictionary<string, double>? ModelLimits { get; init; } = null;

    /// <summary>
    /// Enforcement mode: `"hard"` (reject over-budget requests) or `"soft"` (log only).
    /// </summary>
    [JsonPropertyName("enforcement")]
    public string? Enforcement { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="LlmBudgetConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static LlmBudgetConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<LlmBudgetConfig>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse LlmBudgetConfig from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse LlmBudgetConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
