// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// Configuration for an LLM provider/model via liter-llm.
///
/// Each feature (VLM OCR, VLM embeddings, structured extraction) carries
/// its own `LlmConfig`, allowing different providers per feature.
/// </summary>
public sealed record LlmConfig
{
    /// <summary>
    /// Provider/model string using liter-llm routing format.
    ///
    /// Examples: `"openai/gpt-4o"`, `"anthropic/claude-sonnet-4-20250514"`,
    /// `"groq/llama-3.1-70b-versatile"`.
    /// </summary>
    [JsonPropertyName("model")]
    public string Model { get; init; } = "";

    /// <summary>
    /// API key for the provider. When `None`, liter-llm falls back to
    /// the provider's standard environment variable (e.g., `OPENAI_API_KEY`).
    /// </summary>
    [JsonPropertyName("api_key")]
    public string? ApiKey { get; init; } = null;

    /// <summary>
    /// Custom base URL override for the provider endpoint.
    /// </summary>
    [JsonPropertyName("base_url")]
    public string? BaseUrl { get; init; } = null;

    /// <summary>
    /// Request timeout in seconds. When `None`, liter-llm's built-in 60s default
    /// applies, except the VLM OCR path which uses a 300s default (a single page
    /// image transcription routinely exceeds 60s). Set explicitly to override.
    /// </summary>
    [JsonPropertyName("timeout_secs")]
    public ulong? TimeoutSecs { get; init; } = null;

    /// <summary>
    /// Maximum retry attempts (default: 3).
    /// </summary>
    [JsonPropertyName("max_retries")]
    public uint? MaxRetries { get; init; } = null;

    /// <summary>
    /// Sampling temperature for generation tasks.
    /// </summary>
    [JsonPropertyName("temperature")]
    public double? Temperature { get; init; } = null;

    /// <summary>
    /// Maximum tokens to generate.
    /// </summary>
    [JsonPropertyName("max_tokens")]
    public ulong? MaxTokens { get; init; } = null;

    /// <summary>
    /// Nucleus sampling parameter for generation tasks, applied to individual
    /// requests built from this config. Restricts sampling to the smallest set of
    /// tokens whose cumulative probability mass is at least this value; lower is
    /// more focused. Validated to `[0.0, 1.0]` by `LlmConfig.validate`.
    ///
    /// Mirrors liter-llm's `ChatCompletionRequest.top_p`. A request-time
    /// parameter like `temperature`/`max_tokens` above, not a client-level
    /// setting.
    /// </summary>
    [JsonPropertyName("top_p")]
    public double? TopP { get; init; } = null;

    /// <summary>
    /// Stop sequence(s) that halt token generation, applied to individual requests
    /// built from this config.
    ///
    /// Mirrors liter-llm's `ChatCompletionRequest.stop`
    /// (`types.common.StopSequence`), which liter-llm represents as either a
    /// single string or a list of strings via an untagged enum. Always expressed
    /// here as a list — even one stop sequence is `["..."]` — so the field has a
    /// single, FFI-friendly shape across every language binding instead of a
    /// single-or-list union type. Converted to liter-llm's
    /// `StopSequence.Multiple` at each request-building call site; see
    /// `to_stop_sequence`.
    /// </summary>
    [JsonPropertyName("stop")]
    public List<string>? Stop { get; init; } = null;

    /// <summary>
    /// Random seed for reproducible outputs, applied to individual requests built
    /// from this config. Provider support varies — some silently ignore it.
    ///
    /// Mirrors liter-llm's `ChatCompletionRequest.seed`.
    /// </summary>
    [JsonPropertyName("seed")]
    public long? Seed { get; init; } = null;

    /// <summary>
    /// Presence penalty for generation tasks, applied to individual requests
    /// built from this config. Positive values discourage the model from
    /// repeating topics already present in the conversation. Validated to
    /// `[-2.0, 2.0]` by `LlmConfig.validate`.
    ///
    /// Mirrors liter-llm's `ChatCompletionRequest.presence_penalty`.
    /// </summary>
    [JsonPropertyName("presence_penalty")]
    public double? PresencePenalty { get; init; } = null;

    /// <summary>
    /// Frequency penalty for generation tasks, applied to individual requests
    /// built from this config. Positive values discourage the model from
    /// repeating the same tokens verbatim. Validated to `[-2.0, 2.0]` by
    /// `LlmConfig.validate`.
    ///
    /// Mirrors liter-llm's `ChatCompletionRequest.frequency_penalty`.
    /// </summary>
    [JsonPropertyName("frequency_penalty")]
    public double? FrequencyPenalty { get; init; } = null;

    /// <summary>
    /// Reasoning effort level for extended-thinking models, applied to individual
    /// requests built from this config.
    ///
    /// Mirrors liter-llm's `ChatCompletionRequest.reasoning_effort`
    /// (`types.chat.ReasoningEffort`). A request-time parameter like `temperature`/
    /// `max_tokens` above, not a client-level setting — `into_client_builder` does not
    /// map it. Accepted as a plain string — one of `"low"`, `"medium"`, `"high"`,
    /// `"minimal"`, `"max"` (case-insensitive; liter-llm's own
    /// `#[serde(rename_all = "lowercase")]` spelling) — rather than importing
    /// liter-llm's enum, because this module compiles even when the `liter-llm`
    /// feature is disabled. See `parse_reasoning_effort` for the
    /// conversion into `liter_llm.ReasoningEffort`.
    /// </summary>
    [JsonPropertyName("reasoning_effort")]
    public string? ReasoningEffort { get; init; } = null;

    /// <summary>
    /// Provider-specific extra parameters merged into the request body (guardrails,
    /// safety settings, grounding config, etc.), applied to individual requests built
    /// from this config.
    ///
    /// Mirrors liter-llm's `ChatCompletionRequest.extra_body`. A request-time
    /// parameter like `temperature`/`max_tokens` above, not a client-level setting.
    /// </summary>
    [JsonPropertyName("extra_body")]
    public JsonElement? ExtraBody { get; init; } = null;

    /// <summary>
    /// Whether liter-llm should load provider credentials from environment variables.
    ///
    /// Mirrors liter-llm's `ClientConfigBuilder.load_env`. When `None`, liter-llm's
    /// own default behavior applies.
    /// </summary>
    [JsonPropertyName("load_env")]
    public bool? LoadEnv { get; init; } = null;

    /// <summary>
    /// Extra HTTP headers sent with every request to the provider.
    ///
    /// Mirrors liter-llm's `ClientConfigBuilder.header`, for gateways or providers
    /// that require custom auth/routing headers.
    /// </summary>
    [JsonPropertyName("headers")]
    public Dictionary<string, string>? Headers { get; init; } = null;

    /// <summary>
    /// Custom provider configurations, in addition to liter-llm's built-in providers.
    ///
    /// Mirrors liter-llm's `LlmConfig.providers`, for OpenAI-compatible gateways
    /// and self-hosted model servers that are not in the built-in provider catalog.
    /// </summary>
    [JsonPropertyName("providers")]
    public List<LlmProviderConfig>? Providers { get; init; } = null;

    /// <summary>
    /// Response cache configuration.
    ///
    /// Mirrors liter-llm's `LlmConfig.cache`. Only takes effect when liter-llm's
    /// `tower` feature is compiled in; otherwise the value is accepted but unused.
    ///
    /// Boxed for the same reason as `bedrock` (a4579589ac): `LlmConfig` is the payload
    /// of `EmbeddingModelType.Llm` and `RerankerModelType.Llm`, whose other variants
    /// are tens of bytes. Inlining this and the two sub-configs below pushed that
    /// variant to 480 bytes and tripped `clippy.large_enum_variant` on the
    /// `--features full` leg. ~keep
    /// </summary>
    [JsonPropertyName("cache")]
    public LlmCacheConfig? Cache { get; init; } = null;

    /// <summary>
    /// Budget enforcement configuration.
    ///
    /// Mirrors liter-llm's `LlmConfig.budget`. Only takes effect when liter-llm's
    /// `tower` feature is compiled in; otherwise the value is accepted but unused.
    /// </summary>
    [JsonPropertyName("budget")]
    public LlmBudgetConfig? Budget { get; init; } = null;

    /// <summary>
    /// Per-model rate limiting configuration.
    ///
    /// Mirrors liter-llm's `LlmConfig.rate_limit`. Only takes effect when liter-llm's
    /// `tower` feature is compiled in; otherwise the value is accepted but unused.
    /// </summary>
    [JsonPropertyName("rate_limit")]
    public LlmRateLimitConfig? RateLimit { get; init; } = null;

    /// <summary>
    /// Enable per-request cost tracking.
    ///
    /// Mirrors liter-llm's `LlmConfig.cost_tracking`. Only takes effect when
    /// liter-llm's `tower` feature is compiled in; otherwise the value is accepted
    /// but unused.
    /// </summary>
    [JsonPropertyName("cost_tracking")]
    public bool? CostTracking { get; init; } = null;

    /// <summary>
    /// Enable OpenTelemetry-compatible tracing spans.
    ///
    /// Mirrors liter-llm's `LlmConfig.tracing`. Only takes effect when liter-llm's
    /// `tower` feature is compiled in; otherwise the value is accepted but unused.
    /// </summary>
    [JsonPropertyName("tracing")]
    public bool? Tracing { get; init; } = null;

    /// <summary>
    /// Cooldown duration after transient errors, in seconds.
    ///
    /// Mirrors liter-llm's `LlmConfig.cooldown_secs`. Only takes effect when
    /// liter-llm's `tower` feature is compiled in; otherwise the value is accepted
    /// but unused.
    /// </summary>
    [JsonPropertyName("cooldown_secs")]
    public ulong? CooldownSecs { get; init; } = null;

    /// <summary>
    /// Background health check interval, in seconds.
    ///
    /// Mirrors liter-llm's `LlmConfig.health_check_secs`. Only takes effect when
    /// liter-llm's `tower` feature is compiled in; otherwise the value is accepted
    /// but unused.
    /// </summary>
    [JsonPropertyName("health_check_secs")]
    public ulong? HealthCheckSecs { get; init; } = null;

    /// <summary>
    /// AWS Bedrock settings (region, cross-region routing, explicit credentials).
    ///
    /// Only consulted for `bedrock/`-prefixed models. When `None` — or when an
    /// individual field inside it is `None` — liter-llm falls back to the standard
    /// AWS environment variables and the default credential chain.
    /// </summary>
    [JsonPropertyName("bedrock")]
    public BedrockConfig? Bedrock { get; init; } = null;

    /// <summary>
    /// Managed OAuth2/STS credential provider for auth modes liter-llm cannot express via a
    /// static `api_key` — Azure AD, Vertex AI OAuth2, Vertex AI Application Default
    /// Credentials, and AWS STS Web Identity (EKS IRSA) for Bedrock.
    ///
    /// Mirrors liter-llm's `client.ClientConfigBuilder.credential_provider`, which takes an
    /// `Arc&lt;dyn liter_llm.auth.CredentialProvider&gt;` trait object — that cannot appear in a
    /// serde DTO. Every `CredentialProviderConfig` variant is plain data instead, so it
    /// round-trips through TOML/JSON/YAML and every language binding like the rest of
    /// `LlmConfig`.
    ///
    /// Inert on `wasm32`: `crate.llm` (the module that reads this field —
    /// `build_credential_provider` and friends) is compiled out
    /// entirely on that target, via the crate-root `#[cfg(all(feature = "liter-llm",
    /// not(target_arch = "wasm32")))] pub mod llm;` gate in `lib.rs`. Every variant needs
    /// liter-llm's `native-http`-backed auth modules, and wasm32 builds request only
    /// `wasm-http` (see the `liter-llm` dependency comment in Cargo.toml), so there is no
    /// code path left on that target to construct a provider from this field, or to reject
    /// it. This type (`core.config.llm`) has no `liter-llm` dependency itself and compiles
    /// on every target, so setting this field on a wasm32 build is accepted by serde and
    /// silently ignored — a plain no-op, not a `Validation`. Reject a
    /// wasm32 build that sets this field yourself if that silence is a problem for your use
    /// case; xberg does not do it for you.
    ///
    /// GitHub Copilot's device-flow provider has no variant here: it takes no configuration at
    /// all (`liter_llm.auth.github_copilot.GithubCopilotCredentialProvider.new` accepts only
    /// an HTTP client) and drives an interactive terminal prompt, so it cannot be expressed as
    /// data. A Rust embedder who needs it — or any other fully custom `CredentialProvider` — can
    /// call `xberg.llm.client.create_client_with_credential_provider` directly with a
    /// `liter-llm` dependency of their own.
    /// </summary>
    [JsonPropertyName("credential_provider")]
    public CredentialProviderConfig? CredentialProvider { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="LlmConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static LlmConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<LlmConfig>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse LlmConfig from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse LlmConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
