// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// A custom provider configuration entry, in addition to liter-llm's built-in providers.
///
/// Mirrors liter-llm's `LlmProviderConfig`.
/// </summary>
public sealed record LlmProviderConfig
{
    /// <summary>
    /// Provider name, used to key model prefix matching.
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    /// <summary>
    /// Base URL for the provider's OpenAI-compatible API.
    /// </summary>
    [JsonPropertyName("base_url")]
    public string BaseUrl { get; init; } = "";

    /// <summary>
    /// Header name used to carry the API key (defaults to `Authorization` when unset).
    /// </summary>
    [JsonPropertyName("auth_header")]
    public string? AuthHeader { get; init; } = null;

    /// <summary>
    /// Model name prefixes routed to this provider (e.g. `["my-provider/"]`).
    /// </summary>
    [JsonPropertyName("model_prefixes")]
    public List<string> ModelPrefixes { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="LlmProviderConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static LlmProviderConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<LlmProviderConfig>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse LlmProviderConfig from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse LlmProviderConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
