// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while loading or validating a preset file.
/// </summary>
public class LoadErrorException : XbergException
{
    public LoadErrorException(string message) : base(message) { }

    public LoadErrorException(string message, Exception innerException) : base(message, innerException) { }
}
