// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;

/// <summary>
/// A PDF annotation extracted from a document page.
/// </summary>
public sealed record PdfAnnotation
{
    /// <summary>
    /// The type of annotation.
    /// </summary>
    [JsonPropertyName("annotation_type")]
    public required PdfAnnotationType AnnotationType { get; init; }

    /// <summary>
    /// Text content of the annotation (e.g., comment text, link URL).
    /// </summary>
    [JsonPropertyName("content")]
    public string? Content { get; init; } = null;

    /// <summary>
    /// Page number where the annotation appears (1-indexed).
    /// </summary>
    [JsonPropertyName("page_number")]
    public uint PageNumber { get; init; } = 0;

    /// <summary>
    /// Bounding box of the annotation on the page.
    /// </summary>
    [JsonPropertyName("bounding_box")]
    public BoundingBox? BoundingBox { get; init; } = null;

    /// <summary>
    /// Author/creator of the annotation (PDF `/T` entry).
    /// </summary>
    [JsonPropertyName("author")]
    public string? Author { get; init; } = null;

    /// <summary>
    /// Last modification date of the annotation (PDF `/M` entry), as a raw
    /// PDF date string (e.g. `"D:20240115120000Z"`).
    /// </summary>
    [JsonPropertyName("modified")]
    public string? Modified { get; init; } = null;

    /// <summary>
    /// Annotation colour (PDF `/C` entry), normalised to a CSS-compatible
    /// `#rrggbb` hex string. Gray and CMYK colour spaces are converted to RGB.
    /// </summary>
    [JsonPropertyName("color")]
    public string? Color { get; init; } = null;

    /// <summary>
    /// Subject of the annotation (PDF `/Subj` entry).
    /// </summary>
    [JsonPropertyName("subject")]
    public string? Subject { get; init; } = null;

    /// <summary>
    /// Per-line bounding boxes derived from the annotation's `/QuadPoints`
    /// entry. Present for text markup annotations (Highlight, Underline,
    /// StrikeOut, Squiggly), one box per marked line/run of text.
    /// </summary>
    [JsonPropertyName("quad_points")]
    public List<BoundingBox>? QuadPoints { get; init; } = null;

    /// <summary>
    /// The document text covered by `Self.quad_points`, recovered from the
    /// page content underneath the marked-up region. Populated for
    /// Highlight, Underline, StrikeOut, and Squiggly annotations when the
    /// underlying text could be recovered.
    /// </summary>
    [JsonPropertyName("marked_text")]
    public string? MarkedText { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="PdfAnnotation"/> from a JSON string.
    /// </summary>
    /// <exception cref="XbergException">When the JSON cannot be deserialised.</exception>
    public static PdfAnnotation FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<PdfAnnotation>(json, JsonOptions)
                ?? throw new XbergException($"Failed to parse PdfAnnotation from JSON: deserializer returned null");
        }
        catch (XbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new XbergException($"Failed to parse PdfAnnotation from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
