// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Xberg;
/// <summary>
/// Outcome of a single doctor check.
/// </summary>
[JsonConverter(typeof(ProbeStatusJsonConverter))]
public enum ProbeStatus
{
    /// <summary>
    /// The backend or setting will work as configured.
    /// </summary>
    [JsonPropertyName("pass")]
    Pass,
    /// <summary>
    /// The check ran and found something actionable, but nothing is broken
    /// (e.g. stray cache files, stale model revisions). Never fails the report.
    /// </summary>
    [JsonPropertyName("warn")]
    Warn,
    /// <summary>
    /// The configured setup will not work (or will silently degrade) on this host.
    /// </summary>
    [JsonPropertyName("fail")]
    Fail,
    /// <summary>
    /// The check cannot run locally (e.g. model not cached, feature not compiled in);
    /// first real use decides, possibly after a download.
    /// </summary>
    [JsonPropertyName("skip")]
    Skip,
}


/// <summary>
/// Custom JSON converter for <see cref="ProbeStatus"/> that respects explicit variant names.
/// </summary>
internal sealed class ProbeStatusJsonConverter : JsonConverter<ProbeStatus>
{
    public override ProbeStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "pass" => ProbeStatus.Pass,
            "warn" => ProbeStatus.Warn,
            "fail" => ProbeStatus.Fail,
            "skip" => ProbeStatus.Skip,
            _ => throw new JsonException($"Unknown ProbeStatus value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ProbeStatus value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            ProbeStatus.Pass => "pass",
            ProbeStatus.Warn => "warn",
            ProbeStatus.Fail => "fail",
            ProbeStatus.Skip => "skip",
            _ => throw new JsonException($"Unknown ProbeStatus value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
