// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException
{
    public ResolveErrorException(string message) : base(message) { }

    public ResolveErrorException(string message, Exception innerException) : base(message, innerException) { }
}
