// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// JSON or MessagePack serialization/deserialization failed.
/// </summary>
public class SerializationException : XbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
