// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : XbergErrorException
{
    public TranscriptionException(string message) : base(message) { }

    public TranscriptionException(string message, Exception innerException) : base(message, innerException) { }
}
