// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration or input parameters were supplied.
/// </summary>
public class ValidationException : XbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
