// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
}

// E2e tests for category: batch

test "extract_batch_bytes_happy" {
    // extract_batch: happy path with mixed inputs
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const inputs_file_0 = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "test_documents/html/html.html", allocator, .unlimited);
    defer allocator.free(inputs_file_0);
    const inputs_file_0_json = try std.json.Stringify.valueAlloc(allocator, inputs_file_0, .{ .emit_strings_as_arrays = true });
    defer allocator.free(inputs_file_0_json);
    const inputs_json_0 = try std.mem.replaceOwned(u8, allocator, "[{\"bytes\":[72,101,108,108,111,44,32,119,111,114,108,100,33],\"kind\":\"bytes\",\"mime_type\":\"text/plain\"},{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"kind\":\"bytes\",\"mime_type\":\"text/html\"}]", "\"__ALEF_DOC_FILE_0__\"", inputs_file_0_json);
    defer allocator.free(inputs_json_0);
    const _result_json = try xberg.extract_batch(inputs_json_0, "{}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expect(result.object.get("results").?.array.items.len >= @as(usize, 1));
}

test "extract_batch_bytes_invalid_mime" {
    // extract_batch with invalid bytes MIME type
    allow_private_network();
    const _result_json = try xberg.extract_batch("[{\"bytes\":[72,101,108,108,111],\"kind\":\"bytes\",\"mime_type\":\"application/x-nonexistent\"}]", "{}");
    defer std.heap.c_allocator.free(_result_json);
    std.debug.print("{s}\n", .{_result_json});
}

test "extract_batch_bytes_mixed_format" {
    // extract_batch: handles unsupported MIME gracefully
    allow_private_network();
    const _result_json = try xberg.extract_batch("[{\"bytes\":[80,68,70,32,112,108,97,99,101,104,111,108,100,101,114],\"kind\":\"bytes\",\"mime_type\":\"application/x-unknown\"}]", "{}");
    defer std.heap.c_allocator.free(_result_json);
    std.debug.print("{s}\n", .{_result_json});
}

test "extract_batch_bytes_unsupported_mime" {
    // extract_batch with unsupported bytes MIME type
    allow_private_network();
    const _result_json = try xberg.extract_batch("[{\"bytes\":[100,97,116,97],\"kind\":\"bytes\",\"mime_type\":\"application/x-unknown\"}]", "{}");
    defer std.heap.c_allocator.free(_result_json);
    std.debug.print("{s}\n", .{_result_json});
}

test "extract_batch_empty_inputs" {
    // extract_batch: empty batch
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try xberg.extract_batch("[]", "{}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqual(@as(usize, 0), result.object.get("results").?.array.items.len);
}

test "extract_batch_uri_all_missing" {
    // extract_batch with missing URI inputs
    allow_private_network();
    const _result_json = try xberg.extract_batch("[{\"kind\":\"uri\",\"uri\":\"/nonexistent/a.pdf\"},{\"kind\":\"uri\",\"uri\":\"/nonexistent/b.txt\"}]", "{}");
    defer std.heap.c_allocator.free(_result_json);
    std.debug.print("{s}\n", .{_result_json});
}

test "extract_batch_uri_basic" {
    // extract_batch over URI inputs
    allow_private_network();
    const _result_json = try xberg.extract_batch("[{\"kind\":\"uri\",\"uri\":\"pdf/fake_memo.pdf\"},{\"kind\":\"uri\",\"uri\":\"text/fake_text.txt\"}]", "{}");
    defer std.heap.c_allocator.free(_result_json);
    std.debug.print("{s}\n", .{_result_json});
}

test "extract_batch_uri_not_found" {
    // extract_batch with missing URI input
    allow_private_network();
    const _result_json = try xberg.extract_batch("[{\"kind\":\"uri\",\"uri\":\"/nonexistent/a.pdf\"}]", "{}");
    defer std.heap.c_allocator.free(_result_json);
    std.debug.print("{s}\n", .{_result_json});
}

test "extract_batch_uri_partial_failure" {
    // extract_batch with mixed valid and missing URI inputs
    allow_private_network();
    const _result_json = try xberg.extract_batch("[{\"kind\":\"uri\",\"uri\":\"text/plain.txt\"},{\"kind\":\"uri\",\"uri\":\"/nonexistent/missing.pdf\"}]", "{}");
    defer std.heap.c_allocator.free(_result_json);
    std.debug.print("{s}\n", .{_result_json});
}
