// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
}

// E2e tests for category: contract

test "api_extract_batch_bytes" {
    // Tests batch bytes extraction API (extract_batch)
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const inputs_file_0 = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "test_documents/pdf/fake_memo.pdf", allocator, .unlimited);
    defer allocator.free(inputs_file_0);
    const inputs_file_0_json = try std.json.Stringify.valueAlloc(allocator, inputs_file_0, .{ .emit_strings_as_arrays = true });
    defer allocator.free(inputs_file_0_json);
    const inputs_json_0 = try std.mem.replaceOwned(u8, allocator, "[{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"filename\":\"fake_memo.pdf\",\"kind\":\"bytes\"}]", "\"__ALEF_DOC_FILE_0__\"", inputs_file_0_json);
    defer allocator.free(inputs_json_0);
    const _result_json = try xberg.extract_batch(inputs_json_0, "{}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
    try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
    try testing.expect(
        std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("content").?.string, "May 5, 2023") != null or
        std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("content").?.string, "Mallori") != null
    );
}

test "api_extract_batch_bytes_with_config" {
    // Tests batch bytes extraction with per-input config (extract_batch)
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const inputs_file_0 = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "test_documents/pdf/fake_memo.pdf", allocator, .unlimited);
    defer allocator.free(inputs_file_0);
    const inputs_file_0_json = try std.json.Stringify.valueAlloc(allocator, inputs_file_0, .{ .emit_strings_as_arrays = true });
    defer allocator.free(inputs_file_0_json);
    const inputs_json_0 = try std.mem.replaceOwned(u8, allocator, "[{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"config\":{\"output_format\":\"markdown\"},\"filename\":\"fake_memo.pdf\",\"kind\":\"bytes\"}]", "\"__ALEF_DOC_FILE_0__\"", inputs_file_0_json);
    defer allocator.free(inputs_json_0);
    const _result_json = try xberg.extract_batch(inputs_json_0, "{}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
    try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
    try testing.expectEqualStrings("markdown", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("metadata").?.object.get("output_format").?.string, " \n\r\t"));
}

test "api_extract_batch_uri" {
    // Tests batch URI extraction API (extract_batch)
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const inputs_mock_base_url = if (std.c.getenv("MOCK_SERVER_API_EXTRACT_BATCH_URI")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/api_extract_batch_uri", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
    defer allocator.free(inputs_mock_base_url);
    const inputs_json = try std.mem.replaceOwned(u8, allocator, "[{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}]", "$mock_url", inputs_mock_base_url);
    defer allocator.free(inputs_json);
    const _result_json = try xberg.extract_batch(inputs_json, "{}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
    try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
    try testing.expect(
        std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("content").?.string, "May 5, 2023") != null or
        std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("content").?.string, "Mallori") != null
    );
}

test "api_extract_batch_uri_with_config" {
    // Tests batch URI extraction with per-input config (extract_batch)
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const inputs_mock_base_url = if (std.c.getenv("MOCK_SERVER_API_EXTRACT_BATCH_URI_WITH_CONFIG")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/api_extract_batch_uri_with_config", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
    defer allocator.free(inputs_mock_base_url);
    const inputs_json = try std.mem.replaceOwned(u8, allocator, "[{\"config\":{\"output_format\":\"markdown\"},\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}]", "$mock_url", inputs_mock_base_url);
    defer allocator.free(inputs_json);
    const _result_json = try xberg.extract_batch(inputs_json, "{}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
    try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
    try testing.expectEqualStrings("markdown", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("metadata").?.object.get("output_format").?.string, " \n\r\t"));
}

test "api_extract_bytes_input" {
    // Tests bytes input extraction API (extract)
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const input_file_0 = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "test_documents/pdf/fake_memo.pdf", allocator, .unlimited);
    defer allocator.free(input_file_0);
    const input_file_0_json = try std.json.Stringify.valueAlloc(allocator, input_file_0, .{ .emit_strings_as_arrays = true });
    defer allocator.free(input_file_0_json);
    const input_json_0 = try std.mem.replaceOwned(u8, allocator, "{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"filename\":\"fake_memo.pdf\",\"kind\":\"bytes\"}", "\"__ALEF_DOC_FILE_0__\"", input_file_0_json);
    defer allocator.free(input_json_0);
    const _result_json = try xberg.extract(input_json_0, "{}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
    try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
    try testing.expect(
        std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("content").?.string, "May 5, 2023") != null or
        std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("content").?.string, "Mallori") != null
    );
}

test "api_extract_uri" {
    // Tests URI extraction API
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const input_mock_base_url = if (std.c.getenv("MOCK_SERVER_API_EXTRACT_URI")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/api_extract_uri", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
    defer allocator.free(input_mock_base_url);
    const input_json = try std.mem.replaceOwned(u8, allocator, "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}", "$mock_url", input_mock_base_url);
    defer allocator.free(input_json);
    const _result_json = try xberg.extract(input_json, "{}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
    try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
    try testing.expect(
        std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("content").?.string, "May 5, 2023") != null or
        std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("content").?.string, "Mallori") != null
    );
}

test "config_document_structure_with_headings" {
    // Tests document structure with DOCX heading-driven nesting
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const input_mock_base_url = if (std.c.getenv("MOCK_SERVER_CONFIG_DOCUMENT_STRUCTURE_WITH_HEADINGS")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/config_document_structure_with_headings", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
    defer allocator.free(input_mock_base_url);
    const input_json = try std.mem.replaceOwned(u8, allocator, "{\"kind\":\"uri\",\"uri\":\"$mock_url/docx/fake.docx\"}", "$mock_url", input_mock_base_url);
    defer allocator.free(input_json);
    const _result_json = try xberg.extract(input_json, "{\"include_document_structure\":true}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqualStrings("application/vnd.openxmlformats-officedocument.wordprocessingml.document", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
    try testing.expect(result.object.get("results").?.array.items[0].object.get("document").? != .null);
    try testing.expect(result.object.get("results").?.array.items[0].object.get("document").?.object.get("nodes").?.array.items.len >= @as(usize, 1));
}

test "config_element_types" {
    // Tests element-based result format with element type assertions on DOCX
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const input_mock_base_url = if (std.c.getenv("MOCK_SERVER_CONFIG_ELEMENT_TYPES")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/config_element_types", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
    defer allocator.free(input_mock_base_url);
    const input_json = try std.mem.replaceOwned(u8, allocator, "{\"kind\":\"uri\",\"uri\":\"$mock_url/docx/unit_test_headers.docx\"}", "$mock_url", input_mock_base_url);
    defer allocator.free(input_json);
    const _result_json = try xberg.extract(input_json, "{\"result_format\":\"element_based\"}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expect(
        std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, "application/vnd.openxmlformats-officedocument.wordprocessingml.document") != null
    );
    try testing.expect(result.object.get("results").?.array.items[0].object.get("elements").?.array.items.len >= @as(usize, 1));
}

test "config_extraction_timeout" {
    // Tests that extraction_timeout_secs config field is accepted and does not affect fast extractions
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const input_mock_base_url = if (std.c.getenv("MOCK_SERVER_CONFIG_EXTRACTION_TIMEOUT")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/config_extraction_timeout", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
    defer allocator.free(input_mock_base_url);
    const input_json = try std.mem.replaceOwned(u8, allocator, "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}", "$mock_url", input_mock_base_url);
    defer allocator.free(input_json);
    const _result_json = try xberg.extract(input_json, "{\"extraction_timeout_secs\":300}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
    try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
}

test "config_keywords" {
    // Tests keyword extraction via YAKE algorithm
    allow_private_network();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const input_mock_base_url = if (std.c.getenv("MOCK_SERVER_CONFIG_KEYWORDS")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/config_keywords", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
    defer allocator.free(input_mock_base_url);
    const input_json = try std.mem.replaceOwned(u8, allocator, "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}", "$mock_url", input_mock_base_url);
    defer allocator.free(input_json);
    const _result_json = try xberg.extract(input_json, "{\"keywords\":{\"algorithm\":\"yake\",\"max_keywords\":10}}");
        defer std.heap.c_allocator.free(_result_json);
        var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
        defer _parsed.deinit();
        const result = &_parsed.value;
        try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
        try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
        try testing.expect(result.object.get("results").?.array.items[0].object.get("extracted_keywords").? != .null);
        try testing.expect(result.object.get("results").?.array.items[0].object.get("extracted_keywords").?.array.items.len >= @as(usize, 1));
    }

    test "config_pages" {
        // Tests page extraction and page marker configuration
        allow_private_network();
        var gpa: std.heap.DebugAllocator(.{}) = .init;
        defer _ = gpa.deinit();
        const allocator = gpa.allocator();

        const input_mock_base_url = if (std.c.getenv("MOCK_SERVER_CONFIG_PAGES")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/config_pages", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
        defer allocator.free(input_mock_base_url);
        const input_json = try std.mem.replaceOwned(u8, allocator, "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}", "$mock_url", input_mock_base_url);
        defer allocator.free(input_json);
        const _result_json = try xberg.extract(input_json, "{\"pages\":{\"extract_pages\":true,\"insert_page_markers\":true}}");
            defer std.heap.c_allocator.free(_result_json);
            var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
            defer _parsed.deinit();
            const result = &_parsed.value;
            try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
            try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
            try testing.expect(
                std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("content").?.string, "PAGE") != null
            );
        }

        test "config_quality_enabled" {
            // Tests quality scoring produces a score value in [0.0, 1.0]
            allow_private_network();
            var gpa: std.heap.DebugAllocator(.{}) = .init;
            defer _ = gpa.deinit();
            const allocator = gpa.allocator();

            const input_mock_base_url = if (std.c.getenv("MOCK_SERVER_CONFIG_QUALITY_ENABLED")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/config_quality_enabled", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
            defer allocator.free(input_mock_base_url);
            const input_json = try std.mem.replaceOwned(u8, allocator, "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}", "$mock_url", input_mock_base_url);
            defer allocator.free(input_json);
            const _result_json = try xberg.extract(input_json, "{\"enable_quality_processing\":true}");
            defer std.heap.c_allocator.free(_result_json);
            var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
            defer _parsed.deinit();
            const result = &_parsed.value;
            try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
            try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
            try testing.expect(result.object.get("results").?.array.items[0].object.get("quality_score").? != .null);
            try testing.expect(result.object.get("results").?.array.items[0].object.get("quality_score").?.float >= @as(f64, 0.0));
            try testing.expect(result.object.get("results").?.array.items[0].object.get("quality_score").?.float <= @as(f64, 1.0));
        }

        test "config_security_limits" {
            // Tests archive extraction with custom security limits
            allow_private_network();
            var gpa: std.heap.DebugAllocator(.{}) = .init;
            defer _ = gpa.deinit();
            const allocator = gpa.allocator();

            const input_mock_base_url = if (std.c.getenv("MOCK_SERVER_CONFIG_SECURITY_LIMITS")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/config_security_limits", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
            defer allocator.free(input_mock_base_url);
            const input_json = try std.mem.replaceOwned(u8, allocator, "{\"kind\":\"uri\",\"uri\":\"$mock_url/archives/documents.zip\"}", "$mock_url", input_mock_base_url);
            defer allocator.free(input_json);
            const _result_json = try xberg.extract(input_json, "{\"security_limits\":{\"max_archive_size\":104857600,\"max_compression_ratio\":50,\"max_files_in_archive\":100}}");
                defer std.heap.c_allocator.free(_result_json);
                var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
                defer _parsed.deinit();
                const result = &_parsed.value;
                try testing.expect(
                    std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, "application/zip") != null or
                    std.mem.indexOf(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, "application/x-zip-compressed") != null
                );
                try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
            }

            test "config_tree_sitter" {
                // Tests tree-sitter configuration round-trip
                allow_private_network();
                var gpa: std.heap.DebugAllocator(.{}) = .init;
                defer _ = gpa.deinit();
                const allocator = gpa.allocator();

                const input_mock_base_url = if (std.c.getenv("MOCK_SERVER_CONFIG_TREE_SITTER")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/config_tree_sitter", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
                defer allocator.free(input_mock_base_url);
                const input_json = try std.mem.replaceOwned(u8, allocator, "{\"kind\":\"uri\",\"uri\":\"$mock_url/code/hello.py\"}", "$mock_url", input_mock_base_url);
                defer allocator.free(input_json);
                const _result_json = try xberg.extract(input_json, "{\"tree_sitter\":{\"groups\":[\"web\"],\"languages\":[\"python\",\"rust\"],\"process\":{\"comments\":false,\"diagnostics\":false,\"docstrings\":false,\"exports\":true,\"imports\":true,\"structure\":true,\"symbols\":false}}}");
                    defer std.heap.c_allocator.free(_result_json);
                    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
                    defer _parsed.deinit();
                    const result = &_parsed.value;
                    try testing.expectEqualStrings("text/x-source-code", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
                    try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 5));
                }

                test "output_format_bytes_markdown" {
                    // Tests markdown output format via bytes extraction API
                    allow_private_network();
                    var gpa: std.heap.DebugAllocator(.{}) = .init;
                    defer _ = gpa.deinit();
                    const allocator = gpa.allocator();

                    const input_file_0 = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "test_documents/pdf/fake_memo.pdf", allocator, .unlimited);
                    defer allocator.free(input_file_0);
                    const input_file_0_json = try std.json.Stringify.valueAlloc(allocator, input_file_0, .{ .emit_strings_as_arrays = true });
                    defer allocator.free(input_file_0_json);
                    const input_json_0 = try std.mem.replaceOwned(u8, allocator, "{\"bytes\":\"__ALEF_DOC_FILE_0__\",\"config\":{\"output_format\":\"markdown\"},\"filename\":\"fake_memo.pdf\",\"kind\":\"bytes\",\"mime_type\":\"application/pdf\"}", "\"__ALEF_DOC_FILE_0__\"", input_file_0_json);
                    defer allocator.free(input_json_0);
                    const _result_json = try xberg.extract(input_json_0, "{\"output_format\":\"markdown\"}");
                    defer std.heap.c_allocator.free(_result_json);
                    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
                    defer _parsed.deinit();
                    const result = &_parsed.value;
                    try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
                    try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
                    try testing.expectEqualStrings("markdown", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("metadata").?.object.get("output_format").?.string, " \n\r\t"));
                }

                test "output_format_markdown" {
                    // Tests Markdown output format
                    allow_private_network();
                    var gpa: std.heap.DebugAllocator(.{}) = .init;
                    defer _ = gpa.deinit();
                    const allocator = gpa.allocator();

                    const input_mock_base_url = if (std.c.getenv("MOCK_SERVER_OUTPUT_FORMAT_MARKDOWN")) |_pf| try std.fmt.allocPrint(allocator, "{s}", .{std.mem.span(_pf)}) else try std.fmt.allocPrint(allocator, "{s}/fixtures/output_format_markdown", .{if (std.c.getenv("MOCK_SERVER_URL")) |url| std.mem.span(url) else "http://localhost:8080"});
                    defer allocator.free(input_mock_base_url);
                    const input_json = try std.mem.replaceOwned(u8, allocator, "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}", "$mock_url", input_mock_base_url);
                    defer allocator.free(input_json);
                    const _result_json = try xberg.extract(input_json, "{\"output_format\":\"markdown\"}");
                    defer std.heap.c_allocator.free(_result_json);
                    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
                    defer _parsed.deinit();
                    const result = &_parsed.value;
                    try testing.expectEqualStrings("application/pdf", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("mime_type").?.string, " \n\r\t"));
                    try testing.expect(result.object.get("results").?.array.items[0].object.get("content").?.string.len >= @as(usize, 10));
                    try testing.expectEqualStrings("markdown", std.mem.trim(u8, result.object.get("results").?.array.items[0].object.get("metadata").?.object.get("output_format").?.string, " \n\r\t"));
                }
