// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
}

// E2e tests for category: ocr_backend_management

test "ocr_backends_clear" {
    // Clear all OCR backends and verify list is empty
    allow_private_network();
    _ = try xberg.clear_ocr_backends();
}

test "ocr_backends_list" {
    // List all registered OCR backends
    allow_private_network();
    _ = try xberg.list_ocr_backends();
}

test "ocr_backends_unregister" {
    // Unregister nonexistent OCR backend gracefully
    allow_private_network();
    _ = try xberg.unregister_ocr_backend("nonexistent-backend-xyz");
}
