// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
}

// E2e tests for category: post_processor_management

test "post_processors_clear" {
    // Clear all post-processors and verify list is empty
    allow_private_network();
    _ = try xberg.clear_post_processors();
}

test "post_processors_list" {
    // List all registered post-processors
    allow_private_network();
    _ = try xberg.list_post_processors();
}
