// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

extern "c" fn setenv(name: [*:0]const u8, value: [*:0]const u8, overwrite: c_int) c_int;
fn allow_private_network() void {
    _ = setenv("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true", 1);
}

// E2e tests for category: validator_management

test "validators_clear" {
    // Clear all validators and verify list is empty
    allow_private_network();
    _ = try xberg.clear_validators();
}

test "validators_list" {
    // List all registered validators
    allow_private_network();
    _ = try xberg.list_validators();
}
