// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";
import { extract, ExtractInput, type ExtractionConfig } from "@xberg-io/xberg";

process.env.CRAWLBERG_ALLOW_PRIVATE_NETWORK ??= "true";


async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let buffer = await response.arrayBuffer();

	if (contentEncoding === "gzip") {
		const { gunzipSync } = await import("zlib");
		buffer = gunzipSync(new Uint8Array(buffer)).buffer;
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		buffer = brotliDecompressSync(new Uint8Array(buffer)).buffer;
	}

	const text = new TextDecoder().decode(buffer);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("error", () => {

	it("error_empty_bytes: Graceful handling of empty bytes (should not error)", async () => {
		await extract({ bytes: Uint8Array.from([]), config: {  }, filename: "empty.txt", kind: ExtractInputKind.Bytes, mimeType: "text/plain" } as ExtractInput, undefined);
	}, 30000);
	it("error_empty_mime: Error when extracting with empty MIME type", async () => {
		await expect(async () => {
			await extract({ bytes: await (await import("node:fs/promises")).readFile("test_documents/text/plain.txt"), config: {  }, filename: "plain.txt", kind: ExtractInputKind.Bytes, mimeType: "" } as ExtractInput, undefined);
		}).rejects.toThrow();
	}, 30000);
	it("error_extract_input_conflicting_ocr: extract force+disable OCR", async () => {
		await expect(async () => {
			await extract({ bytes: await (await import("node:fs/promises")).readFile("test_documents/text/fake_text.txt"), config: { disableOcr: true, forceOcr: true }, filename: "fake_text.txt", kind: ExtractInputKind.Bytes, mimeType: "text/plain" } as ExtractInput, { disableOcr: true, forceOcr: true } as ExtractionConfig);
		}).rejects.toThrow();
	}, 30000);
	it("error_invalid_mime_format: Error when extracting with invalid MIME type format", async () => {
		await expect(async () => {
			await extract({ bytes: await (await import("node:fs/promises")).readFile("test_documents/text/plain.txt"), config: {  }, filename: "plain.txt", kind: ExtractInputKind.Bytes, mimeType: "not-a-mime" } as ExtractInput, undefined);
		}).rejects.toThrow();
	}, 30000);
	it("error_unsupported_mime: Error when extracting with unsupported MIME type", async () => {
		await expect(async () => {
			await extract({ bytes: await (await import("node:fs/promises")).readFile("test_documents/text/plain.txt"), config: {  }, filename: "plain.txt", kind: ExtractInputKind.Bytes, mimeType: "application/x-nonexistent" } as ExtractInput, undefined);
		}).rejects.toThrow();
	}, 30000);
});
