# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: code."""

import json
import os
import pytest  # noqa: F401
from xberg import extract, ExtractInput


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = " ".join(str(value) for value in raw_items) if isinstance(raw_items, list) else ""
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio

async def test_code_shebang_detection() -> None:
    """Test language detection from shebang line via bytes input."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/code_shebang_detection'
    input_json = "{\"kind\":\"uri\",\"mime_type\":\"text/x-source-code\",\"uri\":\"$mock_url/code/script.sh\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))

    result = await extract(input, None)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "text/x-source-code".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert "build".lower() in str(result.results[0].content).lower()  # noqa: S101
    assert "clean".lower() in str(result.results[0].content).lower()  # noqa: S101
