# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: extract."""

from pathlib import Path
import pytest  # noqa: F401
from xberg import extract, ExtractInput, ExtractionConfig, ExtractInputKind


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = " ".join(str(value) for value in raw_items) if isinstance(raw_items, list) else ""
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio

async def test_extract_bytes_input() -> None:
    """extract bytes input from PDF document."""
    input = ExtractInput(bytes=Path("test_documents/pdf/fake_memo.pdf").read_bytes(), filename="fake_memo.pdf", kind=ExtractInputKind("bytes"), mime_type="application/pdf")

    result = await extract(input, None)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 50  # noqa: S101


@pytest.mark.asyncio

async def test_extract_bytes_input_empty_mime() -> None:
    """extract bytes input with empty MIME type."""
    with pytest.raises(Exception):  # noqa: B017
        input = ExtractInput(bytes=Path("test_documents/text/plain.txt").read_bytes(), config={}, filename="plain.txt", kind=ExtractInputKind("bytes"), mime_type="")
        config = ExtractionConfig()
        await extract(input, config)


@pytest.mark.asyncio

async def test_extract_bytes_input_invalid_mime() -> None:
    """extract bytes input with unsupported MIME type."""
    with pytest.raises(Exception):  # noqa: B017
        input = ExtractInput(bytes=Path("test_documents/text/plain.txt").read_bytes(), config={}, filename="plain.txt", kind=ExtractInputKind("bytes"), mime_type="application/x-nonexistent")
        config = ExtractionConfig()
        await extract(input, config)
