# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: contract."""

from pathlib import Path
import json
import os
import pytest  # noqa: F401
from xberg import extract_batch, extract, ExtractInput, ExtractionConfig, ExtractInputKind, OutputFormat, ResultFormat


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = " ".join(str(value) for value in raw_items) if isinstance(raw_items, list) else ""
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio

async def test_api_extract_batch_bytes() -> None:
    """Tests batch bytes extraction API (extract_batch)."""
    inputs = [ExtractInput(bytes=Path("test_documents/pdf/fake_memo.pdf").read_bytes(), filename="fake_memo.pdf", kind="bytes")]

    result = await extract_batch(inputs, None)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert any(v.lower() in str(result.results[0].content).lower() for v in ["May 5, 2023", "Mallori"])  # noqa: S101


@pytest.mark.asyncio

async def test_api_extract_batch_bytes_with_config() -> None:
    """Tests batch bytes extraction with per-input config (extract_batch)."""
    inputs = [ExtractInput(bytes=Path("test_documents/pdf/fake_memo.pdf").read_bytes(), config={"output_format": "markdown"}, filename="fake_memo.pdf", kind="bytes")]

    result = await extract_batch(inputs, None)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert _alef_e2e_text(result.results[0].metadata.output_format).lower() == "markdown".lower()  # noqa: S101


@pytest.mark.asyncio

async def test_api_extract_batch_uri() -> None:
    """Tests batch URI extraction API (extract_batch)."""
    inputs_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/api_extract_batch_uri'
    inputs_json = "[{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}]".replace("$mock_url", inputs_mock_base_url)
    inputs = json.loads(inputs_json)

    result = await extract_batch(inputs, None)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert any(v.lower() in str(result.results[0].content).lower() for v in ["May 5, 2023", "Mallori"])  # noqa: S101


@pytest.mark.asyncio

async def test_api_extract_batch_uri_with_config() -> None:
    """Tests batch URI extraction with per-input config (extract_batch)."""
    inputs_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/api_extract_batch_uri_with_config'
    inputs_json = "[{\"config\":{\"output_format\":\"markdown\"},\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}]".replace("$mock_url", inputs_mock_base_url)
    inputs = json.loads(inputs_json)

    result = await extract_batch(inputs, None)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert _alef_e2e_text(result.results[0].metadata.output_format).lower() == "markdown".lower()  # noqa: S101


@pytest.mark.asyncio

async def test_api_extract_bytes_input() -> None:
    """Tests bytes input extraction API (extract)."""
    input = ExtractInput(bytes=Path("test_documents/pdf/fake_memo.pdf").read_bytes(), filename="fake_memo.pdf", kind=ExtractInputKind("bytes"))

    result = await extract(input, None)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert any(v.lower() in str(result.results[0].content).lower() for v in ["May 5, 2023", "Mallori"])  # noqa: S101


@pytest.mark.asyncio

async def test_api_extract_uri() -> None:
    """Tests URI extraction API."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/api_extract_uri'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))

    result = await extract(input, None)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert any(v.lower() in str(result.results[0].content).lower() for v in ["May 5, 2023", "Mallori"])  # noqa: S101


@pytest.mark.asyncio

async def test_config_chunking_prepend_heading_context() -> None:
    """Tests markdown chunker records heading hierarchy on chunk metadata."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/config_chunking_prepend_heading_context'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/markdown/extraction_test.md\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))
    config = ExtractionConfig(chunking={"chunker_type": "markdown", "max_chars": 300, "max_overlap": 50, "prepend_heading_context": True})

    result = await extract(input, config)
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert len(result.chunks) >= 2  # noqa: S101
    assert all(c.content for c in (result.chunks or []))  # noqa: S101
    assert all(c.metadata and c.metadata.heading_context is not None for c in (result.chunks or []))  # noqa: S101
    assert bool((result.chunks or []) and (result.chunks[0].metadata and result.chunks[0].metadata.heading_context))  # noqa: S101


@pytest.mark.asyncio

async def test_config_document_structure_with_headings() -> None:
    """Tests document structure with DOCX heading-driven nesting."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/config_document_structure_with_headings'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/docx/fake.docx\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))
    config = ExtractionConfig(include_document_structure=True)

    result = await extract(input, config)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/vnd.openxmlformats-officedocument.wordprocessingml.document".lower()  # noqa: S101
    assert result.results[0].document  # noqa: S101
    assert len(result.results[0].document.nodes) >= 1  # noqa: S101


@pytest.mark.asyncio

async def test_config_element_types() -> None:
    """Tests element-based result format with element type assertions on DOCX."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/config_element_types'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/docx/unit_test_headers.docx\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))
    config = ExtractionConfig(result_format=ResultFormat("element_based"))

    result = await extract(input, config)
    assert any(v.lower() in str(result.results[0].mime_type).lower() for v in ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"])  # noqa: S101
    assert len(result.results[0].elements) >= 1  # noqa: S101


@pytest.mark.asyncio

async def test_config_extraction_timeout() -> None:
    """Tests that extraction_timeout_secs config field is accepted and does not affect fast extractions."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/config_extraction_timeout'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))
    config = ExtractionConfig(extraction_timeout_secs=300)

    result = await extract(input, config)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101


@pytest.mark.asyncio

async def test_config_keywords() -> None:
    """Tests keyword extraction via YAKE algorithm."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/config_keywords'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))
    config = ExtractionConfig(keywords={"algorithm": "yake", "max_keywords": 10})

    result = await extract(input, config)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert result.results[0].extracted_keywords  # noqa: S101
    assert len(result.results[0].extracted_keywords) >= 1  # noqa: S101


@pytest.mark.asyncio

async def test_config_pages() -> None:
    """Tests page extraction and page marker configuration."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/config_pages'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))
    config = ExtractionConfig(pages={"extract_pages": True, "insert_page_markers": True})

    result = await extract(input, config)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert any(v.lower() in str(result.results[0].content).lower() for v in ["PAGE"])  # noqa: S101


@pytest.mark.asyncio

async def test_config_quality_enabled() -> None:
    """Tests quality scoring produces a score value in [0.0, 1.0]."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/config_quality_enabled'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))
    config = ExtractionConfig(enable_quality_processing=True)

    result = await extract(input, config)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert result.results[0].quality_score  # noqa: S101
    assert result.results[0].quality_score >= 0.0  # noqa: S101
    assert result.results[0].quality_score <= 1.0  # noqa: S101


@pytest.mark.asyncio

async def test_config_security_limits() -> None:
    """Tests archive extraction with custom security limits."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/config_security_limits'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/archives/documents.zip\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))
    config = ExtractionConfig(security_limits={"max_archive_size": 104857600, "max_compression_ratio": 50, "max_files_in_archive": 100})

    result = await extract(input, config)
    assert any(v.lower() in str(result.results[0].mime_type).lower() for v in ["application/zip", "application/x-zip-compressed"])  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101


@pytest.mark.asyncio

async def test_config_tree_sitter() -> None:
    """Tests tree-sitter configuration round-trip."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/config_tree_sitter'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/code/hello.py\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))
    config = ExtractionConfig(tree_sitter={"groups": ["web"], "languages": ["python", "rust"], "process": {"comments": False, "diagnostics": False, "docstrings": False, "exports": True, "imports": True, "structure": True, "symbols": False}})

    result = await extract(input, config)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "text/x-source-code".lower()  # noqa: S101
    assert len(result.results[0].content) >= 5  # noqa: S101


@pytest.mark.asyncio

async def test_output_format_bytes_markdown() -> None:
    """Tests markdown output format via bytes extraction API."""
    input = ExtractInput(bytes=Path("test_documents/pdf/fake_memo.pdf").read_bytes(), config={"output_format": "markdown"}, filename="fake_memo.pdf", kind=ExtractInputKind("bytes"), mime_type="application/pdf")
    config = ExtractionConfig(output_format=OutputFormat("markdown"))

    result = await extract(input, config)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert _alef_e2e_text(result.results[0].metadata.output_format).lower() == "markdown".lower()  # noqa: S101


@pytest.mark.asyncio

async def test_output_format_markdown() -> None:
    """Tests Markdown output format."""
    input_mock_base_url = os.environ['MOCK_SERVER_URL'] + '/fixtures/output_format_markdown'
    input_json = "{\"kind\":\"uri\",\"uri\":\"$mock_url/pdf/fake_memo.pdf\"}".replace("$mock_url", input_mock_base_url)
    input = ExtractInput(**json.loads(input_json))
    config = ExtractionConfig(output_format=OutputFormat("markdown"))

    result = await extract(input, config)
    assert _alef_e2e_text(result.results[0].mime_type).lower() == "application/pdf".lower()  # noqa: S101
    assert len(result.results[0].content) >= 10  # noqa: S101
    assert _alef_e2e_text(result.results[0].metadata.output_format).lower() == "markdown".lower()  # noqa: S101
