// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Main extraction configuration.
 *
 * This struct contains all configuration options for the extraction process.
 * It can be loaded from TOML, YAML, or JSON files, or created programmatically.
 */
data class ExtractionConfig(
    /** Enable caching of extraction results */
    val useCache: Boolean = true,
    /** Enable quality post-processing */
    val enableQualityProcessing: Boolean = true,
    /**
     * OCR configuration.
     *
     * `null` does not run OCR for documents that already have usable text. Under
     * `OcrStrategy.Auto`, a PDF with no text layer at all (a scan) is still routed
     * to OCR with default settings so it is not returned empty (#1338). Set
     * `Self.disable_ocr` to hard-disable OCR regardless of the detected content.
     */
    val ocr: OcrConfig? = null,
    /** Force OCR even for searchable PDFs */
    val forceOcr: Boolean = false,
    /**
     * Which pages get OCR'd when neither `force_ocr` nor `force_ocr_pages` applies.
     *
     * Defaults to `OcrStrategy.Auto`, which OCRs only pages whose native text
     * fails a quality check. Only applies to PDF documents. Cannot be
     * `OcrStrategy.ScannedPages` while `disable_ocr` is `true`.
     */
    @field:com.fasterxml.jackson.databind.annotation.JsonSerialize(`as` = OcrStrategy::class)
    val ocrStrategy: OcrStrategy = OcrStrategy.Auto,
    /**
     * Force OCR on specific pages only (1-indexed page numbers, must be >= 1).
     *
     * When set, only the listed pages are OCR'd regardless of text layer quality.
     * Unlisted pages use native text extraction. Ignored when `force_ocr` is `true`.
     * Only applies to PDF documents. Duplicates are automatically deduplicated.
     * An `ocr` config is recommended for backend/language selection; defaults are used if absent.
     */
    val forceOcrPages: List<Int>? = null,
    /**
     * Disable OCR entirely, even for images.
     *
     * When `true`, OCR is skipped for all document types. Images return metadata
     * only (dimensions, format, EXIF) without text extraction. PDFs use only
     * native text extraction without OCR fallback.
     *
     * Cannot be `true` simultaneously with `force_ocr`.
     */
    val disableOcr: Boolean = false,
    /** Text chunking configuration (None = chunking disabled) */
    val chunking: ChunkingConfig? = null,
    /**
     * Content filtering configuration (None = use extractor defaults).
     *
     * Controls whether document "furniture" (headers, footers, watermarks,
     * repeating text) is included in or stripped from extraction results.
     * See `ContentFilterConfig` for per-field documentation.
     */
    val contentFilter: ContentFilterConfig? = null,
    /** Image extraction configuration (None = no image extraction) */
    val images: ImageExtractionConfig? = null,
    /** PDF-specific options (None = use defaults) */
    val pdfOptions: PdfConfig? = null,
    /** Token reduction configuration (None = no token reduction) */
    val tokenReduction: TokenReductionOptions? = null,
    /** Language detection configuration (None = no language detection) */
    val languageDetection: LanguageDetectionConfig? = null,
    /** Page extraction configuration (None = no page tracking) */
    val pages: PageConfig? = null,
    /** Keyword extraction configuration (None = no keyword extraction) */
    val keywords: KeywordConfig? = null,
    /** Post-processor configuration (None = use defaults) */
    val postprocessor: PostProcessorConfig? = null,
    /**
     * HTML to Markdown conversion options (None = use defaults)
     *
     * Configure how HTML documents are converted to Markdown, including heading styles,
     * list formatting, code block styles, and preprocessing options.
     */
    val htmlOptions: ConversionOptions? = null,
    /**
     * Styled HTML output configuration.
     *
     * When set alongside `output_format = OutputFormat.Html`, the extraction
     * pipeline uses `StyledHtmlRenderer`
     * which emits stable `kb-*` CSS class hooks on every structural element
     * and optionally embeds theme CSS or user-supplied CSS in a `<style>` block.
     *
     * When `null`, the existing plain comrak-based HTML renderer is used.
     */
    val htmlOutput: HtmlOutputConfig? = null,
    /**
     * Default per-file timeout in seconds for batch extraction.
     *
     * When set, each file in a batch will be canceled after this duration
     * unless overridden by `FileExtractionConfig.timeout_secs`.
     *
     * Defaults to `Some(600)` (10 minutes) to prevent pathological files
     * (e.g. deeply nested archives, documents with millions of cells) from
     * running indefinitely and exhausting caller resources, while still
     * giving slow paths (VLM-based OCR, large scanned documents) enough
     * headroom to finish. Set to `null` to disable the timeout for trusted
     * input or long-running workloads.
     */
    val extractionTimeoutSecs: Long? = null,
    /**
     * Maximum concurrent document extractions in batch operations.
     *
     * This is a ceiling within the configured total thread budget, not an
     * independent pool size. When unset, the scheduler derives document and
     * per-document concurrency from `ConcurrencyConfig.max_threads`.
     */
    val maxConcurrentExtractions: Long? = null,
    /**
     * Result structure format
     *
     * Controls whether results are returned in unified format (default) with all
     * content in the `content` field, or element-based format with semantic
     * elements (for Unstructured-compatible output).
     */
    val resultFormat: ResultFormat = ResultFormat.UNIFIED,
    /**
     * Security limits for archive extraction.
     *
     * Controls maximum archive size, compression ratio, file count, and other
     * security thresholds to prevent decompression bomb attacks. Also caps
     * nesting depth, iteration count, entity / token length, total
     * content size, and table cell count for every extraction path that
     * ingests user-controlled bytes.
     * When `null`, default limits are used.
     */
    val securityLimits: SecurityLimits? = null,
    /**
     * Maximum uncompressed size in bytes for a single embedded file before
     * recursive extraction is attempted (default: 50 MiB).
     *
     * Applies to embedded objects inside OOXML containers (DOCX, PPTX) and
     * to email attachments processed via recursive extraction. Files that
     * exceed this limit are skipped with a `ProcessingWarning` rather than
     * passed to the extraction pipeline, preventing a single oversized
     * embedded object from consuming unbounded memory or time.
     *
     * Set to `null` to disable the per-embedded-file cap (falls back to
     * `security_limits.max_archive_size` as the only guard).
     */
    val maxEmbeddedFileBytes: Long? = null,
    /**
     * Content text format (default: Plain).
     *
     * Controls the format of the extracted content:
     *
     * - `Plain`: Raw extracted text (default)
     * - `Markdown`: Markdown formatted output
     * - `Djot`: Djot markup format (requires djot feature)
     * - `Html`: HTML formatted output
     *
     * When set to a structured format, extraction results will include
     * formatted output. The `formatted_content` field may be populated
     * when format conversion is applied.
     */
    val outputFormat: OutputFormat = OutputFormat.Plain,
    /**
     * Escape Markdown special characters in rendered prose (default: `true`).
     *
     * When `output_format` is `Markdown` or `Djot`, the renderer backslash-escapes
     * CommonMark-significant leading characters (e.g. `-`, `#`) so that literal
     * text such as `#06-18` or `- clause` round-trips safely through a CommonMark
     * parser instead of being reinterpreted as a heading or list marker.
     *
     * Table cell text is never escaped, so escaped prose can look inconsistent
     * with table cells containing the same characters. Set this to `false` to
     * disable prose escaping and make `content`, `pages[].content`, and
     * `chunks[].content` read identically to table cell text — useful for LLM
     * prompts or search indexing where CommonMark round-tripping does not matter.
     *
     * Defaults to `true` to preserve existing behavior.
     */
    val escapeMarkdown: Boolean = true,
    /**
     * Emit an opt-in anchor marker before each table's rendered Markdown
     * block (default: `false`).
     *
     * When `output_format` is `Markdown` (or `Djot`) and this is `true`, the
     * renderer inserts a `[TABLE:{table_id}]` marker immediately before each
     * table's Markdown in `content`, `pages[].content`, and
     * `chunks[].content`, where `table_id` matches the corresponding
     * entry's `table_id`. This lets a consumer
     * reconcile a rendered Markdown table block with its structured
     * `tables[]` entry.
     *
     * Defaults to `false` so existing output is byte-identical unless
     * explicitly enabled.
     */
    val tableAnchors: Boolean = false,
    /**
     * Controls how Jupyter notebook (`.ipynb`) code cells are rendered.
     *
     * - `Both` (default): code source plus the notebook's saved outputs
     * - `Source`: only the code source (fenced code blocks)
     * - `Outputs`: only the saved outputs
     *
     * Cells are never executed; `Outputs`/`Both` surface only outputs already
     * stored in the notebook.
     */
    val jupyterCellRendering: JupyterCellRendering = JupyterCellRendering.BOTH,
    /**
     * Layout detection configuration (None = layout detection disabled).
     *
     * When set, PDF pages and images are analyzed for document structure
     * (headings, code, formulas, tables, figures, etc.) using RT-DETR models
     * via ONNX Runtime. For PDFs, layout hints override paragraph classification
     * in the markdown pipeline. For images, per-region OCR is performed with
     * markdown formatting based on detected layout classes.
     * Requires the `layout-detection` feature to run inference; the field is
     * present whenever the `layout-types` feature is active (which includes
     * `layout-detection` as well as the no-ORT target groups).
     */
    val layout: LayoutDetectionConfig? = null,
    /**
     * Transcription (speech-to-text) configuration for audio/video files.
     *
     * When set and `enabled`, files with audio/video MIME types (mp3, mp4,
     * m4a, wav, webm, etc.) are routed to the Whisper-based transcription
     * pipeline. The actual heavy dependencies are only active under the
     * `transcription` feature; the field is visible under `transcription-types`
     * (including on WASM and Android targets that use the no-ORT preset).
     *
     * Default: `null` (transcription disabled). This is an additive,
     * non-breaking change.
     */
    val transcription: TranscriptionConfig? = null,
    /**
     * Run layout detection on the non-OCR PDF markdown path.
     *
     * When `true` and `layout` is `Some(_)`, layout regions inform reading
     * order, region grouping, and table detection while native font/tag
     * semantics remain authoritative for headings, lists, code, and formulas.
     * OCR layout classification is unchanged. This improves structural output
     * at the cost of inference latency (~150-300ms/page CPU, ~20-50ms/page
     * GPU). Default: `false`. Requires the `layout-detection` feature.
     */
    val useLayoutForMarkdown: Boolean = false,
    /**
     * Enable structured document tree output.
     *
     * When true, populates the `document` field on `ExtractedDocument` with a
     * hierarchical `DocumentStructure` containing heading-driven section nesting,
     * table grids, content layer classification, and inline annotations.
     *
     * Independent of `result_format` — can be combined with Unified or ElementBased.
     */
    val includeDocumentStructure: Boolean = false,
    /**
     * Hardware acceleration configuration for ONNX Runtime models.
     *
     * Controls execution provider selection for layout detection and embedding
     * models. When `null`, uses platform defaults (CoreML on macOS, CUDA on
     * Linux, CPU on Windows).
     */
    val acceleration: AccelerationConfig? = null,
    /**
     * Cache namespace for tenant isolation.
     *
     * When set, cache entries are stored under `{cache_dir}/{namespace}/`.
     * Must be alphanumeric, hyphens, or underscores only (max 64 chars).
     * Different namespaces have isolated cache spaces on the same filesystem.
     */
    val cacheNamespace: String? = null,
    /**
     * Per-request cache TTL in seconds.
     *
     * Overrides the global `max_age_days` for this specific extraction.
     * When `0`, caching is completely skipped (no read or write).
     * When `null`, the global TTL applies.
     */
    val cacheTtlSecs: Long? = null,
    /**
     * Email extraction configuration (None = use defaults).
     *
     * Currently supports configuring the fallback codepage for MSG files
     * that do not specify one. See `EmailConfig` for details.
     */
    val email: EmailConfig? = null,
    /**
     * CSV/TSV extraction configuration (None = use defaults).
     *
     * Lets callers set an explicit delimiter and declare comment-line
     * prefixes to skip, instead of relying solely on delimiter
     * auto-detection. See `CsvConfig` for details.
     */
    val csv: CsvConfig? = null,
    /** URL ingestion and crawl configuration. */
    val url: UrlExtractionConfig = UrlExtractionConfig(),
    /**
     * Maximum recursion depth for archive extraction (default: 3).
     * Set to 0 to disable recursive extraction (legacy behavior).
     */
    val maxArchiveDepth: Long,
    /**
     * Tree-sitter language pack configuration (None = tree-sitter disabled).
     *
     * When set, enables code file extraction using tree-sitter parsers.
     * Controls grammar download behavior and code analysis options.
     */
    val treeSitter: TreeSitterConfig? = null,
    /**
     * Structured extraction via LLM (None = disabled).
     *
     * When set, the extracted document content is sent to an LLM with the
     * provided JSON schema. The structured response is stored in
     * `ExtractedDocument.structured_output`.
     */
    val structuredExtraction: StructuredExtractionConfig? = null,
    /**
     * Named-entity recognition configuration. When set, the NER post-processor runs at
     * the Middle stage and populates `ExtractedDocument.entities`.
     */
    val ner: NerConfig? = null,
    /**
     * Redaction / anonymisation configuration. When set, the redaction post-processor
     * runs at the Late stage and rewrites every textual field in `ExtractedDocument`,
     * emitting an audit trail in `ExtractedDocument.redaction_report`.
     */
    val redaction: RedactionConfig? = null,
    /**
     * Summarisation configuration. When set, the summarisation post-processor runs at
     * the Middle stage and populates `ExtractedDocument.summary`.
     */
    val summarization: SummarizationConfig? = null,
    /**
     * Translation configuration. When set, the translation post-processor runs at the
     * Middle stage and populates `ExtractedDocument.translation`.
     */
    val translation: TranslationConfig? = null,
    /**
     * Per-page classification configuration. When set, the classification post-processor
     * runs at the Middle stage and populates `ExtractedDocument.page_classifications`.
     */
    val pageClassification: PageClassificationConfig? = null,
    /**
     * Per-chunk multi-label classification configuration. When set, the
     * chunk-classification post-processor runs at the Middle stage (after
     * chunking) and populates `ChunkMetadata.classifications` on every chunk.
     */
    val chunkClassification: ChunkClassificationConfig? = null,
    /**
     * VLM captioning configuration for extracted images. When set, the captioning
     * post-processor runs at the Middle stage and writes a caption into each
     * `ExtractedImage.caption`.
     */
    val captioning: CaptioningConfig? = null,
    /**
     * Enable QR-code detection in extracted images. When `true`, the QR post-processor
     * runs at the Middle stage and populates `ExtractedImage.qr_codes`.
     */
    val qrCodes: Boolean? = null,
) {

    /**
     * Check if image processing is needed by examining OCR and image extraction settings.
     *
     * Returns `true` if either OCR is enabled or image extraction is configured,
     * indicating that image decompression and processing should occur.
     * Returns `false` if both are disabled, allowing optimization to skip unnecessary
     * image decompression for text-only extraction workflows.
     *
     * # Optimization Impact
     * For text-only extractions (no OCR, no image extraction), skipping image
     * decompression can improve CPU utilization by 5-10% by avoiding wasteful
     * image I/O and processing when results won't be used.
     * Returns `true` when image binary data should be extracted.
     *
     * True when `config.images.extract_images` is set, captioning is configured, or QR-code
     * detection is enabled. Captioning and QR-code detection both require image bytes
     * regardless of whether the caller also requested image extraction.
     */
    fun needsImageData(): Boolean {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        return XbergBridge.nativeExtractionConfigNeedsImageData(selfJson)
    }

    /**
     * Returns `true` when any image processing is needed during extraction.
     *
     * # Optimization Impact
     *
     * For text-only extractions (no OCR, no image extraction, no captioning), skipping
     * image decompression can improve CPU utilization by 5-10% by avoiding wasteful
     * image I/O and processing when results won't be used.
     */
    fun needsImageProcessing(): Boolean {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        return XbergBridge.nativeExtractionConfigNeedsImageProcessing(selfJson)
    }
}

// Marshals the receiver and the parameter object across the value-method JNI
// boundary. The naming strategy, null handling, and unknown-property tolerance
// must match the module facade's mapper — both feed the same Rust serde types.
private val VALUE_METHOD_MAPPER = com.fasterxml.jackson.module.kotlin.jacksonObjectMapper()
    .registerModule(com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
    .registerModule(
        com.fasterxml.jackson.module.kotlin.KotlinModule.Builder()
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullIsSameAsDefault, true)
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyCollection, true)
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyMap, true)
            .build(),
    )
    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
    .configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
