// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Which PDF pages the layout model runs on.
 *
 * Layout detection renders each selected page to a raster and runs ONNX
 * inference on it, which dominates extraction cost. This controls page
 * selection; `LayoutStrategy.Always` preserves the historical behavior of
 * running on every page. Wire format is snake_case in all serializers
 * (JSON, TOML, YAML).
 */
enum class LayoutStrategy {
    /** Run layout detection unconditionally on every page. */
    @com.fasterxml.jackson.annotation.JsonProperty("always") ALWAYS,
    /**
     * Pre-screen each page with cheap geometry signals and run the model
     * only on pages likely to benefit (multi-column, table-bearing,
     * figure-heavy, form-like, or rotated pages).
     *
     * Pages the pre-screen skips are processed exactly like pages where the
     * model ran and found no regions. On the OCR path only inference is
     * skipped; page rasters are still produced because OCR consumes them.
     * For non-PDF inputs `Auto` behaves as `LayoutStrategy.Always`.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("auto") AUTO;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            ALWAYS -> "always"
            AUTO -> "auto"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): LayoutStrategy =
            when (value) {
                "always" -> ALWAYS
                "auto" -> AUTO
                else -> throw IllegalArgumentException("Unknown LayoutStrategy value: $value")
            }
    }
}
