// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * A ColBERT multi-vector embedding: one row per attention-live token.
 *
 * `data` is a flat, row-major buffer of length `num_tokens * dim` — row `i`
 * (the embedding for token `i`) occupies `data[i*dim .. (i+1)*dim]`. Flat
 * storage keeps the type FFI-friendly across binding boundaries; use
 * `MultiVectorEmbedding.rows` internally to iterate per-token slices.
 *
 * Since v5.0.
 */
data class MultiVectorEmbedding(
    /**
     * Number of attention-live token rows (padding rows are dropped, not
     * zeroed — see `engine.normalize_tokens`).
     */
    val numTokens: Int,
    /** Dimensionality of each per-token vector. */
    val dim: Int,
    /** Flat row-major buffer, length `num_tokens * dim`. */
    val data: List<Float> = emptyList(),
) {

    /**
     * Returns `true` if `data` holds exactly `num_tokens * dim` values — i.e.
     * the flat buffer matches the declared shape.
     *
     * All fields are `pub` and the type is `Deserialize`, so a value coming
     * from an untrusted source (FFI caller, JSON, a store row) may be
     * malformed. `max_sim_score` guards on this so a length-mismatched
     * buffer scores `0.0` rather than silently mis-scoring (a shorter `data`
     * would make `rows`' `chunks_exact` drop a trailing partial
     * chunk). Uses `checked_mul` so an overflowing `num_tokens * dim` is
     * reported as malformed instead of wrapping.
     *
     * Since v5.0.
     */
    fun isWellFormed(): Boolean {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        return XbergBridge.nativeMultiVectorEmbeddingIsWellFormed(selfJson)
    }
}

// Marshals the receiver and the parameter object across the value-method JNI
// boundary. The naming strategy, null handling, and unknown-property tolerance
// must match the module facade's mapper — both feed the same Rust serde types.
private val VALUE_METHOD_MAPPER = com.fasterxml.jackson.module.kotlin.jacksonObjectMapper()
    .registerModule(com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
    .registerModule(
        com.fasterxml.jackson.module.kotlin.KotlinModule.Builder()
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullIsSameAsDefault, true)
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyCollection, true)
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyMap, true)
            .build(),
    )
    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
    .configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
