// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Which concrete ONNX inference engine PaddleOCR model loading uses.
 *
 * Mirrors `sceptre.Backend` for the PaddleOCR backend: `Ort` is the native,
 * full-featured path (acceleration/execution-provider hook, ONNX-embedded
 * dictionary metadata); `Tract` is the pure-Rust, CPU-only path used on targets
 * where `ort` cannot link (Android x86_64 emulator, WASM once wired).
 */
enum class PaddleInferenceBackend {
    /** Native ONNX Runtime (requires the `paddle-ocr-ort` feature). */
    @com.fasterxml.jackson.annotation.JsonProperty("ort") ORT,
    /** Pure-Rust ONNX via `tract` (requires the `paddle-ocr-tract` feature). */
    @com.fasterxml.jackson.annotation.JsonProperty("tract") TRACT;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            ORT -> "ort"
            TRACT -> "tract"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): PaddleInferenceBackend =
            when (value) {
                "ort" -> ORT
                "tract" -> TRACT
                else -> throw IllegalArgumentException("Unknown PaddleInferenceBackend value: $value")
            }
    }
}
