// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Configuration for PaddleOCR backend.
 *
 * Configures PaddleOCR text detection and recognition with multi-language support.
 * Uses a builder pattern for convenient configuration.
 */
data class PaddleOcrConfig(
    /** Language code (e.g., "en", "ch", "jpn", "kor", "deu", "fra") */
    val language: String = "",
    /**
     * Optional Hugging Face Hub cache root for model files.
     *
     * When unset, the standard `HF_HUB_CACHE`, legacy
     * `HUGGINGFACE_HUB_CACHE`, and `HF_HOME` conventions are used.
     */
    val cacheDir: String? = null,
    /**
     * Enable angle classification for rotated text (default: false).
     * Can misfire on short text regions, rotating crops incorrectly before recognition.
     */
    val useAngleCls: Boolean = false,
    /** Enable table structure detection (default: false) */
    val enableTableDetection: Boolean = false,
    /**
     * Database threshold for text detection (default: 0.3)
     * Range: 0.0-1.0, higher values require more confident detections
     */
    val detDbThresh: Float = 0.0f,
    /**
     * Box threshold for text bounding box refinement (default: 0.5)
     * Range: 0.0-1.0
     */
    val detDbBoxThresh: Float = 0.0f,
    /**
     * Unclip ratio for expanding text bounding boxes (default: 1.6)
     * Controls the expansion of detected text regions
     */
    val detDbUnclipRatio: Float = 0.0f,
    /**
     * Maximum side length for detection image (default: 1024)
     * Larger images may be resized to this limit for faster inference
     */
    val detLimitSideLen: Int = 0,
    /**
     * Batch size for recognition inference (default: 6)
     * Number of text regions to process simultaneously
     */
    val recBatchNum: Int = 0,
    /**
     * Padding in pixels added around the image before detection (default: 10).
     * Large values can include surrounding content like table gridlines.
     */
    val padding: Int = 0,
    /**
     * Minimum recognition confidence score for text lines (default: 0.5).
     * Text regions with recognition confidence below this threshold are discarded.
     * Matches PaddleOCR Python's `drop_score` parameter.
     * Range: 0.0-1.0
     */
    val dropScore: Float = 0.0f,
    /**
     * Model tier controlling detection/recognition model size and accuracy trade-off.
     *
     * For PP-OCRv5 (`model_version = "pp-ocrv5"`):
     *
     * - `"mobile"` (default): Lightweight models (~4.5MB detection, ~16.5MB recognition), fast download and inference
     * - `"server"`: Large, high-accuracy models (~88MB detection, ~84MB recognition), best for GPU or complex documents
     *
     * For PP-OCRv6 (`model_version = "pp-ocrv6"`): `"medium"` (default), `"small"`, or `"tiny"`.
     * A legacy `"mobile"`/`"server"` tier under v6 falls back to `"medium"`.
     */
    val modelTier: String = "",
    /**
     * Model generation: `"pp-ocrv6"` (default) or `"pp-ocrv5"`.
     *
     * PP-OCRv6 adds a unified CJK+Latin+JA/KO recognition model with `medium`/`small`/`tiny`
     * tiers (see `model_tier`). Scripts outside the v6 unified coverage (Arabic, Cyrillic,
     * Devanagari, Greek, Tamil, Telugu, Thai) transparently fall back to the PP-OCRv5
     * per-script recognition models. Defaults to `"pp-ocrv6"`; the default `model_tier`
     * (`"mobile"`) resolves to the v6 `"medium"` tier. Select `"pp-ocrv5"` to pin the
     * legacy per-script/unified fleet.
     */
    val modelVersion: String = "",
    /**
     * Explicit inference engine choice.
     *
     * `null` (the default) resolves to the compiled default: `ort` when the
     * `paddle-ocr-ort` feature is compiled in, otherwise `tract`. An explicit choice
     * is validated against the compiled features when the OCR engine is constructed
     * (see `crate.paddle_ocr.backend.effective_backend`); requesting an engine
     * whose feature is not compiled in is a clear configuration error rather than a
     * silent fallback.
     */
    val inferenceBackend: PaddleInferenceBackend? = null,
) {

    /** Sets a custom Hugging Face Hub cache root for model files. */
    fun withCacheDir(path: String): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "path" to path,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithCacheDir(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /** Enables or disables table structure detection. */
    fun withTableDetection(enable: Boolean): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "enable" to enable,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithTableDetection(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /** Enables or disables angle classification for rotated text. */
    fun withAngleCls(enable: Boolean): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "enable" to enable,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithAngleCls(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /** Sets the database threshold for text detection. */
    fun withDetDbThresh(threshold: Float): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "threshold" to threshold,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithDetDbThresh(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /** Sets the box threshold for text bounding box refinement. */
    fun withDetDbBoxThresh(threshold: Float): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "threshold" to threshold,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithDetDbBoxThresh(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /** Sets the unclip ratio for expanding text bounding boxes. */
    fun withDetDbUnclipRatio(ratio: Float): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "ratio" to ratio,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithDetDbUnclipRatio(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /** Sets the maximum side length for detection images. */
    fun withDetLimitSideLen(length: Int): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "length" to length,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithDetLimitSideLen(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /** Sets the batch size for recognition inference. */
    fun withRecBatchNum(batchSize: Int): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "batch_size" to batchSize,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithRecBatchNum(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /** Sets the minimum recognition confidence threshold. */
    fun withDropScore(score: Float): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "score" to score,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithDropScore(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /** Sets padding in pixels added around images before detection. */
    fun withPadding(padding: Int): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "padding" to padding,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithPadding(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /** Sets the model tier controlling detection/recognition model size. */
    fun withModelTier(tier: String): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "tier" to tier,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithModelTier(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }

    /**
     * Sets the model generation.
     *
     *   selects among `"medium"`/`"small"`/`"tiny"`.
     */
    fun withModelVersion(version: String): PaddleOcrConfig {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "version" to version,
            ),
        )
        val resultJson = XbergBridge.nativePaddleOcrConfigWithModelVersion(selfJson, requestJson)
        return VALUE_METHOD_MAPPER.readValue(
            resultJson,
            object : com.fasterxml.jackson.core.type.TypeReference<PaddleOcrConfig>() {},
        )
    }
}

// Marshals the receiver and the parameter object across the value-method JNI
// boundary. The naming strategy, null handling, and unknown-property tolerance
// must match the module facade's mapper — both feed the same Rust serde types.
private val VALUE_METHOD_MAPPER = com.fasterxml.jackson.module.kotlin.jacksonObjectMapper()
    .registerModule(com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
    .registerModule(
        com.fasterxml.jackson.module.kotlin.KotlinModule.Builder()
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullIsSameAsDefault, true)
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyCollection, true)
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyMap, true)
            .build(),
    )
    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
    .configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
