// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Type of PDF annotation. */
enum class PdfAnnotationType {
    /** Sticky note / text annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("text") TEXT,
    /** Highlighted text region */
    @com.fasterxml.jackson.annotation.JsonProperty("highlight") HIGHLIGHT,
    /** Hyperlink annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("link") LINK,
    /** Rubber stamp annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("stamp") STAMP,
    /** Underline text markup */
    @com.fasterxml.jackson.annotation.JsonProperty("underline") UNDERLINE,
    /** Strikeout text markup */
    @com.fasterxml.jackson.annotation.JsonProperty("strike_out") STRIKE_OUT,
    /** Squiggly (wavy) underline text markup */
    @com.fasterxml.jackson.annotation.JsonProperty("squiggly") SQUIGGLY,
    /** Freehand drawing (ink) annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("ink") INK,
    /** Rectangle/box shape annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("square") SQUARE,
    /** Ellipse/oval shape annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("circle") CIRCLE,
    /** Closed polygon shape annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("polygon") POLYGON,
    /** Open polyline shape annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("poly_line") POLY_LINE,
    /** Line annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("line") LINE,
    /** Caret (text-insertion marker) annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("caret") CARET,
    /** Embedded file attachment annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("file_attachment") FILE_ATTACHMENT,
    /** Embedded sound annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("sound") SOUND,
    /** Embedded movie annotation */
    @com.fasterxml.jackson.annotation.JsonProperty("movie") MOVIE,
    /** Any other annotation type */
    @com.fasterxml.jackson.annotation.JsonProperty("other") OTHER;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            TEXT -> "text"
            HIGHLIGHT -> "highlight"
            LINK -> "link"
            STAMP -> "stamp"
            UNDERLINE -> "underline"
            STRIKE_OUT -> "strike_out"
            SQUIGGLY -> "squiggly"
            INK -> "ink"
            SQUARE -> "square"
            CIRCLE -> "circle"
            POLYGON -> "polygon"
            POLY_LINE -> "poly_line"
            LINE -> "line"
            CARET -> "caret"
            FILE_ATTACHMENT -> "file_attachment"
            SOUND -> "sound"
            MOVIE -> "movie"
            OTHER -> "other"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): PdfAnnotationType =
            when (value) {
                "text" -> TEXT
                "highlight" -> HIGHLIGHT
                "link" -> LINK
                "stamp" -> STAMP
                "underline" -> UNDERLINE
                "strike_out" -> STRIKE_OUT
                "squiggly" -> SQUIGGLY
                "ink" -> INK
                "square" -> SQUARE
                "circle" -> CIRCLE
                "polygon" -> POLYGON
                "poly_line" -> POLY_LINE
                "line" -> LINE
                "caret" -> CARET
                "file_attachment" -> FILE_ATTACHMENT
                "sound" -> SOUND
                "movie" -> MOVIE
                "other" -> OTHER
                else -> throw IllegalArgumentException("Unknown PdfAnnotationType value: $value")
            }
    }
}
