// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Outcome of a single doctor check. */
enum class ProbeStatus {
    /** The backend or setting will work as configured. */
    @com.fasterxml.jackson.annotation.JsonProperty("pass") PASS,
    /**
     * The check ran and found something actionable, but nothing is broken
     * (e.g. stray cache files, stale model revisions). Never fails the report.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("warn") WARN,
    /** The configured setup will not work (or will silently degrade) on this host. */
    @com.fasterxml.jackson.annotation.JsonProperty("fail") FAIL,
    /**
     * The check cannot run locally (e.g. model not cached, feature not compiled in);
     * first real use decides, possibly after a download.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("skip") SKIP;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            PASS -> "pass"
            WARN -> "warn"
            FAIL -> "fail"
            SKIP -> "skip"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): ProbeStatus =
            when (value) {
                "pass" -> PASS
                "warn" -> WARN
                "fail" -> FAIL
                "skip" -> SKIP
                else -> throw IllegalArgumentException("Unknown ProbeStatus value: $value")
            }
    }
}
