// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * API server configuration.
 *
 * This struct holds all configuration options for the Xberg API server,
 * including host/port settings, CORS configuration, and upload limits.
 *
 * # Defaults
 *
 * - `host`: "127.0.0.1" (localhost only)
 * - `port`: 8000
 * - `cors_origins`: empty listtor (allows all origins)
 * - `max_request_body_bytes`: 104_857_600 (100 MB)
 * - `max_multipart_field_bytes`: 104_857_600 (100 MB)
 */
data class ServerConfig(
    /** Server host address (e.g., "127.0.0.1", "0.0.0.0") */
    val host: String,
    /** Server port number */
    val port: Short,
    /**
     * CORS allowed origins. Empty vector means allow all origins.
     *
     * If this is an empty listtor, the server will accept requests from any origin.
     * If populated with specific origins (e.g., `"https://example.com"`), only
     * those origins will be allowed.
     */
    val corsOrigins: List<String> = emptyList(),
    /** Maximum size of request body in bytes (default: 100 MB) */
    val maxRequestBodyBytes: Long,
    /** Maximum size of multipart fields in bytes (default: 100 MB) */
    val maxMultipartFieldBytes: Long,
) {

    /** Get the server listen address (host:port). */
    fun listenAddr(): String {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        return XbergBridge.nativeServerConfigListenAddr(selfJson)
    }

    /**
     * Check if CORS allows all origins.
     *
     * Returns `true` if the `cors_origins` vector is empty, meaning all origins
     * are allowed. Returns `false` if specific origins are configured.
     */
    fun corsAllowsAll(): Boolean {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        return XbergBridge.nativeServerConfigCorsAllowsAll(selfJson)
    }

    /**
     * Check if a given origin is allowed by CORS configuration.
     *
     * Returns `true` if:
     *
     * - CORS allows all origins (empty origins list), or
     * - The given origin is in the allowed origins list
     */
    fun isOriginAllowed(origin: String): Boolean {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        val requestJson = VALUE_METHOD_MAPPER.writeValueAsString(
            mapOf(
                "origin" to origin,
            ),
        )
        return XbergBridge.nativeServerConfigIsOriginAllowed(selfJson, requestJson)
    }

    /** Get maximum request body size in megabytes (rounded up). */
    fun maxRequestBodyMb(): Long {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        return XbergBridge.nativeServerConfigMaxRequestBodyMb(selfJson)
    }

    /** Get maximum multipart field size in megabytes (rounded up). */
    fun maxMultipartFieldMb(): Long {
        val selfJson = VALUE_METHOD_MAPPER.writeValueAsString(this)
        return XbergBridge.nativeServerConfigMaxMultipartFieldMb(selfJson)
    }
}

// Marshals the receiver and the parameter object across the value-method JNI
// boundary. The naming strategy, null handling, and unknown-property tolerance
// must match the module facade's mapper — both feed the same Rust serde types.
private val VALUE_METHOD_MAPPER = com.fasterxml.jackson.module.kotlin.jacksonObjectMapper()
    .registerModule(com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
    .registerModule(
        com.fasterxml.jackson.module.kotlin.KotlinModule.Builder()
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullIsSameAsDefault, true)
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyCollection, true)
            .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyMap, true)
            .build(),
    )
    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
    .configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
