// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Per-category running counter for `RedactionStrategy.TokenReplace`. */
class TokenCounter internal constructor(handle: Long) : AutoCloseable {
    private var nativeHandle: Long = handle
    internal val handle: Long
        @Synchronized get() {
            check(nativeHandle != 0L) { "TokenCounter is closed" }
            return nativeHandle
        }

    @Synchronized
    override fun close() {
        val ownedHandle = nativeHandle
        if (ownedHandle == 0L) return
        nativeHandle = 0L
        XbergBridge.nativeFreeTokenCounter(ownedHandle)
    }
}
