// Generated by alef. Do not edit by hand.
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.core.type.TypeReference
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.PropertyNamingStrategies
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.KotlinFeature
import com.fasterxml.jackson.module.kotlin.KotlinModule
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
object Xberg {
    /// Jackson module that marshals ByteArray as a JSON array of unsigned bytes,
    /// matching how Rust serde encodes Vec<u8> on the wire.
    /// Jackson's default writes ByteArray as a Base64 string, which Rust serde rejects
    /// with "invalid type: string, expected a sequence".
    private val byteArrayModule = com.fasterxml.jackson.databind.module.SimpleModule().apply {
        addSerializer(
            ByteArray::class.java,
            object : com.fasterxml.jackson.databind.ser.std.StdSerializer<ByteArray>(ByteArray::class.java) {
                override fun serialize(
                    value: ByteArray,
                    gen: com.fasterxml.jackson.core.JsonGenerator,
                    provider: com.fasterxml.jackson.databind.SerializerProvider,
                ) {
                    gen.writeStartArray()
                    for (b in value) gen.writeNumber(b.toInt() and 0xff)
                    gen.writeEndArray()
                }
            },
        )
        addDeserializer(
            ByteArray::class.java,
            object : com.fasterxml.jackson.databind.deser.std.StdDeserializer<ByteArray>(ByteArray::class.java) {
                override fun deserialize(
                    parser: com.fasterxml.jackson.core.JsonParser,
                    ctx: com.fasterxml.jackson.databind.DeserializationContext,
                ): ByteArray {
                    val node = parser.codec.readTree<com.fasterxml.jackson.databind.JsonNode>(parser)
                    return when {
                        node.isArray -> ByteArray(node.size()) { i -> node.get(i).asInt().toByte() }
                        node.isTextual -> java.util.Base64.getDecoder().decode(node.asText())
                        else -> ByteArray(0)
                    }
                }
            },
        )
    }

    private val mapper = jacksonObjectMapper()
        .registerModule(com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
        .registerModule(byteArrayModule)
        .registerModule(
            com.fasterxml.jackson.module.kotlin.KotlinModule.Builder()
                .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullIsSameAsDefault, true)
                .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyCollection, true)
                .configure(com.fasterxml.jackson.module.kotlin.KotlinFeature.NullToEmptyMap, true)
                .build(),
        )
        .setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
        .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
        .configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

    /** Extract content from a single bytes or URI input. */
    fun extract(input: ExtractInput, config: ExtractionConfig): ExtractionResult {
        val resultJson = XbergBridge.nativeExtract(mapper.writeValueAsString(input), mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, ExtractionResult::class.java)
    }
    /** Extract content from multiple bytes or URI inputs. */
    fun extractBatch(inputs: List<ExtractInput>, config: ExtractionConfig): ExtractionResult {
        val resultJson = XbergBridge.nativeExtractBatch(mapper.writeValueAsString(inputs), mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, ExtractionResult::class.java)
    }
    /**
     * Discover all pages and sitemaps reachable from `uri` without extracting document content.
     *
     * Builds a `crawlberg.CrawlEngine` from `config.crawl`, calls
     * `CrawlEngine.map`, and returns the set of discovered URLs as a
     * `crawlberg.MapResult` (re-exported as `MapResult`).
     *
     * Use this when you need the URL inventory of a site before committing to
     * full document extraction — e.g. to build a crawl queue or validate scope.
     *
     * **Errors:**
     *
     * Returns `Validation` if the crawl configuration fails
     * validation or if the map operation itself fails.
     */
    fun mapUrl(uri: String, config: UrlExtractionConfig): MapResult {
        val resultJson = XbergBridge.nativeMapUrl(uri, mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, MapResult::class.java)
    }
    /**
     * List all supported document formats.
     *
     * Returns every file extension Xberg recognizes together with its
     * corresponding MIME type, derived from the central format registry.
     * Formats that have no registered file extension (such as source code,
     * which is detected dynamically) are not included.
     *
     * The static `EXT_TO_MIME` table lists every format the *codebase* knows how
     * to describe, regardless of which Cargo features were compiled in. Advertising
     * that table directly would claim support for extractors that may not exist in
     * this build (see GH#1387). To keep the advertised catalogue honest, the table
     * is intersected with the document extractor registry: an extension is only
     * included if some registered extractor actually claims its MIME type in this
     * build. This can never drift from reality and automatically covers
     * third-party extractors registered at runtime.
     *
     * The list is sorted alphabetically by file extension.
     *
     * **Returns:**
     *
     * A vector of `SupportedFormat` entries sorted by extension, limited to
     * formats with a registered extractor in this build.
     */
    fun listSupportedFormats(): List<SupportedFormat> {
        val resultJson = XbergBridge.nativeListSupportedFormats()
        return mapper.readValue(resultJson, object : TypeReference<List<SupportedFormat>>() {})
    }
    /**
     * Ensure built-in extractors are registered.
     *
     * This function is called automatically on first extraction operation.
     * It's safe to call multiple times - registration only happens once,
     * unless the registry was cleared, in which case extractors are re-registered.
     *
     * Public so a caller that wants to *inspect* the registry — rather than extract —
     * can populate it directly. Without this the only way to trigger registration is to
     * run a real extraction, which `xberg formats` would otherwise have to fake (#233).
     */
    fun ensureInitialized(): Unit = XbergBridge.nativeEnsureInitialized()
    /**
     * List the names of all registered embedding backends.
     *
     * Used by `xberg-cli`, the api/mcp endpoints, and generated language
     * bindings.
     */
    fun listEmbeddingBackends(): List<String> {
        val resultJson = XbergBridge.nativeListEmbeddingBackends()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /** List names of all registered document extractors. */
    fun listDocumentExtractors(): List<String> {
        val resultJson = XbergBridge.nativeListDocumentExtractors()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List all registered OCR backends.
     *
     * Returns the names of all OCR backends currently registered in the global registry.
     *
     * **Returns:**
     *
     * A vector of OCR backend names.
     */
    fun listOcrBackends(): List<String> {
        val resultJson = XbergBridge.nativeListOcrBackends()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List all registered post-processor names.
     *
     * Returns a vector of all post-processor names currently registered in the
     * global registry.
     *
     * **Returns:**
     *
     * - `Ok(List<String>)` - Vector of post-processor names
     * - `Err(...)` if the registry lock is poisoned
     */
    fun listPostProcessors(): List<String> {
        val resultJson = XbergBridge.nativeListPostProcessors()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List names of all registered renderers.
     *
     * **Errors:**
     *
     * Returns an error if the registry lock is poisoned.
     */
    fun listRenderers(): List<String> {
        val resultJson = XbergBridge.nativeListRenderers()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List the names of all registered reranker backends.
     *
     * Used by `xberg-cli`, the api/mcp endpoints, and generated language
     * bindings.
     *
     * Since v5.0.
     */
    fun listRerankerBackends(): List<String> {
        val resultJson = XbergBridge.nativeListRerankerBackends()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * List the names of all registered tokenizer backends.
     *
     * Used by `xberg-cli`, the api/mcp endpoints, and generated language
     * bindings.
     */
    fun listTokenizerBackends(): List<String> {
        val resultJson = XbergBridge.nativeListTokenizerBackends()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /** List names of all registered validators. */
    fun listValidators(): List<String> {
        val resultJson = XbergBridge.nativeListValidators()
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * Run chunk classification against an extraction result.
     *
     * Mutates `ChunkMetadata.classifications` on every chunk in
     * `result.chunks` and appends every LLM call's usage to `result.llm_usage`.
     * A chunk whose classification batch call fails (or that the model omitted
     * from its response) is simply left with an empty `classifications` vector for
     * that chunk, unless the failure is a validation error (empty config) or every
     * batch task fails, in which case the first error is returned.
     *
     * **Errors:**
     *
     * Returns `Validation` when `config.definitions` is empty.
     * Returns the first batch error encountered when rendering the prompt or
     * calling the LLM fails for every batch; partial failures on a subset of
     * batches are recorded here as a `ProcessingWarning` on `result` instead of
     * aborting the whole run.
     */
    fun classifyChunks(result: ExtractedDocument, config: ChunkClassificationConfig): Unit = XbergBridge.nativeClassifyChunks(mapper.writeValueAsString(result), mapper.writeValueAsString(config))
    /**
     * Find unmarked claims in markdown text.
     *
     * Returns lines that assert a claim but carry neither a footnote citation anchor (`[^...]`)
     * nor an inference marker (`[*inference*]`).
     *
     * The heuristic is simple: a line that contains alphabetic words, ends with sentence punctuation,
     * and is not a heading, blank line, or markup-only line is considered a claim.
     * Exclude lines that appear in the citation block (after `---` + `<!-- citations ... -->`).
     *
     * **Returns:**
     *
     * A vector of trimmed line text strings for unmarked claims.
     */
    fun findUnmarkedClaims(markdown: String): List<String> {
        val resultJson = XbergBridge.nativeFindUnmarkedClaims(markdown)
        return mapper.readValue(resultJson, object : TypeReference<List<String>>() {})
    }
    /**
     * Verify that an excerpt appears verbatim in source text.
     *
     * Performs exact matching by default. Also tries whitespace-normalized matching
     * (collapsing runs of whitespace on both sides) since PDF-extracted text often
     * has irregular spacing.
     *
     * **Returns:**
     *
     * `true` if the excerpt appears (exactly or with normalized whitespace), `false` otherwise.
     */
    fun verifyExcerpt(excerpt: String, sourceText: String): Boolean = XbergBridge.nativeVerifyExcerpt(excerpt, sourceText)
    /**
     * Score a query against a document using ColBERT's MaxSim operator: for each
     * query token vector, take the maximum dot product against any document
     * token vector, then sum across query tokens.
     *
     * Returns `0.0` if `query` and `doc` have mismatched dimensionality, if either
     * has zero tokens, or if either is not well-formed per
     * `MultiVectorEmbedding.is_well_formed` (its `data` length does not match
     * `num_tokens * dim`).
     *
     * Pure CPU primitive — available without ONNX Runtime.
     *
     * Since v5.0.
     */
    fun maxSimScore(query: MultiVectorEmbedding, doc: MultiVectorEmbedding): Double = XbergBridge.nativeMaxSimScore(mapper.writeValueAsString(query), mapper.writeValueAsString(doc))
    /**
     * Rank a set of documents against a query by MaxSim score, descending.
     *
     * Mirrors the sort/truncate shape of `crate.reranking`'s `build_results`,
     * minus top-k truncation (callers slice the returned `Vec` themselves).
     *
     * Pure CPU primitive — available without ONNX Runtime.
     *
     * Since v5.0.
     */
    fun maxSimRank(query: MultiVectorEmbedding, docs: List<MultiVectorEmbedding>): List<LateInteractionMatch> {
        val resultJson = XbergBridge.nativeMaxSimRank(mapper.writeValueAsString(query), mapper.writeValueAsString(docs))
        return mapper.readValue(resultJson, object : TypeReference<List<LateInteractionMatch>>() {})
    }
    /**
     * Probe the backends and settings in `config` and report what will actually
     * execute on this host.
     *
     * Runs no downloads and no billable API calls. Backends that are not compiled
     * in or whose models are not cached report `Skip` rather than failing.
     */
    fun doctor(config: ExtractionConfig): DoctorReport {
        val resultJson = XbergBridge.nativeDoctor(mapper.writeValueAsString(config))
        return mapper.readValue(resultJson, DoctorReport::class.java)
    }
    /**
     * Install `PdfOxideWarningCapture` as the process-wide `log` backend,
     * exactly once.
     *
     * If another component already installed a `log.Log` implementation (an
     * application wiring `env_logger`, for instance), `log.set_boxed_logger`
     * fails and this is a no-op: we do not fight over ownership of the global
     * logger slot, and we do not touch `log.set_max_level` unless our install
     * won, so we never silently raise or lower a level someone else configured.
     * In that case `pdf_oxide`'s glyph-drop records go wherever that other
     * logger sends them instead of into `take_pdf_oxide_render_warnings`.
     * **Opt-in.** Nothing calls this automatically, and that is deliberate: xberg
     * is a library, and `log` has exactly one global backend slot per process. A
     * library that claims it on its own behalf breaks its embedder — a host that
     * later calls `env_logger.init()` panics, and until this returns, every
     * `log` record in the process is routed here rather than wherever the host
     * intended. That decision belongs to the application, so it is exposed as a
     * call an application makes knowingly.
     *
     * Returns `true` if this call (or an earlier one) installed the capture, and
     * `false` if some other component already owns the `log` backend — in which
     * case `pdf_oxide`'s glyph-drop records go to that logger and
     * `take_pdf_oxide_render_warnings` stays empty.
     *
     * Without this call the #1364 warnings are not produced. The glyph drop
     * itself is decided inside `pdf_oxide`, which reports it only through
     * `log.warn!`; there is no return-value channel to read instead.
     */
    fun installPdfRenderDiagnostics(): Boolean = XbergBridge.nativeInstallPdfRenderDiagnostics()
    /**
     * Drain the glyph-drop `ProcessingWarning`s accumulated on this thread by
     * render calls since the last call to this function.
     *
     * Callers that render pages as part of extraction should call this after
     * their render pass and merge the result into
     * `InternalDocument.processing_warnings` (see the module-level convention
     * in `crate.core.diagnostics`) so a page with missing glyphs is never
     * returned to the user without a signal. Warnings are already deduped
     * per-thread across all pages rendered before this call.
     *
     * `pub` (rather than `pub(crate)`) so both in-tree render-consumers and the
     * regression test for #1364 can observe capture without depending on any
     * one extractor's internal state.
     *
     * As of #340, `crate.extractors.pdf.mod` drains this unconditionally right
     * after assembling a document's `processing_warnings`, so every PDF
     * extraction that renders at least one page picks up any captured
     * glyph-drop warnings for free. ~keep: that drain only ever observes
     * warnings from render calls that happened on the *same OS thread* before it
     * ran, because `PDF_OXIDE_PENDING_WARNINGS` is thread-local. OCR page
     * rendering runs inline on the extracting task's thread, so it is covered.
     * Layout-detection rasterization runs inside `tokio.task.spawn_blocking`,
     * which always executes on a different OS thread, so this function alone
     * would never see those warnings. As of #353,
     * `extractors.pdf.layout_runner.run_layout_for_pdf_pages_async` drains
     * this function itself from inside its `spawn_blocking` closure — the only
     * place that can observe the blocking-pool thread's thread-local buffer —
     * and threads the drained warnings back through its return value for the
     * caller in `extractors.pdf.mod` to merge, so layout-path glyph drops are
     * no longer silently lost.
     */
    fun takePdfOxideRenderWarnings(): List<ProcessingWarning> {
        val resultJson = XbergBridge.nativeTakePdfOxideRenderWarnings()
        return mapper.readValue(resultJson, object : TypeReference<List<ProcessingWarning>>() {})
    }
    /**
     * Build the four (or three) token Whisper decoder prompt.
     *
     * The canonical Whisper prompt is
     * `[<|startoftranscript|>, <|{lang}|>, <|transcribe|>, <|notimestamps|>]`.
     * When `timestamps` is `true`, the trailing `no_timestamps` token is omitted
     * so the model is free to emit `<|x.xx|>` timestamp tokens in its output
     * instead of being forced to suppress them.
     */
    fun buildDecoderPromptTokens(startOfTranscript: Int, langId: Int, transcribe: Int, noTimestamps: Int, timestamps: Boolean): List<Long> {
        val resultJson = XbergBridge.nativeBuildDecoderPromptTokens(startOfTranscript, langId, transcribe, noTimestamps, timestamps)
        return mapper.readValue(resultJson, object : TypeReference<List<Long>>() {})
    }
    /**
     * Convert a raw Whisper timestamp token ID to a millisecond offset from the
     * start of the 30-second chunk it was decoded in.
     *
     * `token_id` must be `>= timestamp_begin_id`; IDs below that are ordinary
     * vocabulary tokens, not timestamps.
     */
    fun timestampTokenToMs(tokenId: Int, timestampBeginId: Int): Int = XbergBridge.nativeTimestampTokenToMs(tokenId, timestampBeginId)
}
