// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * AWS Bedrock configuration for {@code bedrock/}-prefixed models.
 *
 * Mirrors liter-llm's {@code BedrockConfig}. Every field is optional: anything left
 * unset falls back to the standard AWS environment variables
 * ({@code AWS_DEFAULT_REGION} / {@code AWS_REGION}, {@code AWS_ACCESS_KEY_ID},
 * {@code AWS_SECRET_ACCESS_KEY}, {@code AWS_SESSION_TOKEN}, {@code BEDROCK_CROSS_REGION}) and the
 * default AWS credential chain. Leave the credential fields unset unless you
 * have an explicit reason to pin them.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BedrockConfig.Builder.class)
public record BedrockConfig(
    @Nullable @JsonProperty("region") String region,
    @Nullable @JsonProperty("cross_region_prefix") String crossRegionPrefix,
    @Nullable @JsonProperty("access_key_id") String accessKeyId,
    @Nullable @JsonProperty("secret_access_key") String secretAccessKey,
    @Nullable @JsonProperty("session_token") String sessionToken
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for BedrockConfig deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @Nullable private String region;
        @JsonProperty("cross_region_prefix")
        @Nullable private String crossRegionPrefix;
        @JsonProperty("access_key_id")
        @Nullable private String accessKeyId;
        @JsonProperty("secret_access_key")
        @Nullable private String secretAccessKey;
        @JsonProperty("session_token")
        @Nullable private String sessionToken;

        /** Sets the region field. */
        @JsonProperty("region")
        public Builder withRegion(final @Nullable String value) {
            this.region = value;
            return this;
        }

        /** Sets the crossRegionPrefix field. */
        @JsonProperty("cross_region_prefix")
        public Builder withCrossRegionPrefix(final @Nullable String value) {
            this.crossRegionPrefix = value;
            return this;
        }

        /** Sets the accessKeyId field. */
        @JsonProperty("access_key_id")
        public Builder withAccessKeyId(final @Nullable String value) {
            this.accessKeyId = value;
            return this;
        }

        /** Sets the secretAccessKey field. */
        @JsonProperty("secret_access_key")
        public Builder withSecretAccessKey(final @Nullable String value) {
            this.secretAccessKey = value;
            return this;
        }

        /** Sets the sessionToken field. */
        @JsonProperty("session_token")
        public Builder withSessionToken(final @Nullable String value) {
            this.sessionToken = value;
            return this;
        }

        /** Constructs a BedrockConfig instance from the builder's current state. */
        public BedrockConfig build() {
            return new BedrockConfig(
                region,
                crossRegionPrefix,
                accessKeyId,
                secretAccessKey,
                sessionToken
            );
        }
    }
    // CPD-ON
}
