// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * **Deprecated and inert.** Chunking no longer writes a heading breadcrumb into
 * {@code content} for either variant of this enum — see the revised design adopted in
 * &lt;https://github.com/xberg-io/xberg/issues/1393&gt;. Setting this field has no
 * effect on chunking output any more. It is kept only so the ~15 alef-generated
 * binding packages that construct it keep compiling; removing it outright is a
 * separate, coordinated breaking change.
 *
 * # Why this became inert
 *
 * The original design (this enum, plus
 * ChunkingConfig.prepend_heading_context(super.super.processing.ChunkingConfig.prepend_heading_context))
 * let {@code Content} mode prepend the heading breadcrumb directly into a chunk's
 * {@code content}. GH#1393's follow-up discussion argued that a single flag on the
 * chunker cannot serve all three retrieval consumers of the same chunk: dense/
 * embedding retrieval wants the breadcrumb inline, but lexical (BM25/TF-IDF) and
 * sparse learned (SPLADE) retrieval are actively harmed by it — SPLADE worse
 * than BM25, because its term-expansion pulls each heading's whole learned
 * neighbourhood (e.g. {@code "Authentication"} → {@code auth}, {@code login}, {@code credential},
 * {@code oauth}) into every chunk of that section, and that damage cannot be
 * corrected by re-indexing since the expansion comes from a pretrained encoder,
 * not the collection being indexed. Mutating {@code content} also desynced it from
 * {@code byte_start}/{@code byte_end} (#1294): {@code chunk.content.len() != byte_end - byte_start}
 * whenever a breadcrumb had been prepended, so slicing the source document by a
 * chunk's own offsets silently returned different text than {@code content}.
 *
 * The revised design removes the mutation entirely: {@code chunk.content} now always
 * equals the exact {@code [byte_start, byte_end)} source span, regardless of this
 * enum's value or {@code prepend_heading_context}.
 *
 * # What to do instead
 *
 * Call render_heading_breadcrumb(crate.chunking.render_heading_breadcrumb)
 * explicitly at index time, with a chunk's (always-clean) {@code content} and its
 * heading_context(crate.types.ChunkMetadata.heading_context) — only for
 * the consumer that wants the breadcrumb inline (typically dense/embedding).
 * BM25 and SPLADE consumers need no special handling: index {@code chunk.content} as
 * returned. See the rag(crate.chunking.rag) module docs for the full
 * per-consumer guidance.
 */
@SuppressWarnings("PMD")
public enum BreadcrumbTarget {
    /**
     * Inert (#1393). Previously prepended the heading breadcrumb into chunk
     * {@code content}; no longer has any effect — {@code content} is left untouched, exactly
     * like {@code Metadata}. Kept as the default only for wire/API compatibility.
     */
    Content("content"),
    /**
     * Inert (#1393), and was already a no-op on {@code content} before this change.
     * Kept only for backward compatibility, since {@code Content} is no longer
     * distinguishable from it.
     */
    Metadata("metadata");


    /** The string value. */
    private final String value;

    BreadcrumbTarget(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static BreadcrumbTarget fromValue(final String value) {
        for (BreadcrumbTarget e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown BreadcrumbTarget value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
