// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * A text chunk with optional embedding and metadata.
 *
 * Chunks are created when chunking is enabled in {@code ExtractionConfig}. Each chunk
 * contains the text content, optional embedding vector (if embedding generation
 * is configured), and metadata about its position in the document.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Chunk.Builder.class)
public record Chunk(
    @JsonProperty("content") String content,
    @Nullable @JsonProperty("chunk_type") ChunkType chunkType,
    @Nullable @JsonProperty("embedding") List<Float> embedding,
    @Nullable @JsonProperty("sparse_embedding") SparseEmbedding sparseEmbedding,
    @Nullable @JsonProperty("late_interaction") MultiVectorEmbedding lateInteraction,
    @JsonProperty("metadata") ChunkMetadata metadata
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for Chunk deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private String content;
        @JsonProperty("chunk_type")
        @Nullable private ChunkType chunkType = ChunkType.Unknown;
        @Nullable private List<Float> embedding;
        @JsonProperty("sparse_embedding")
        @Nullable private SparseEmbedding sparseEmbedding;
        @JsonProperty("late_interaction")
        @Nullable private MultiVectorEmbedding lateInteraction;
        private ChunkMetadata metadata;

        /** Sets the content field. */
        @JsonProperty("content")
        public Builder withContent(final String value) {
            this.content = value;
            return this;
        }

        /** Sets the chunkType field. */
        @JsonProperty("chunk_type")
        public Builder withChunkType(final @Nullable ChunkType value) {
            this.chunkType = value;
            return this;
        }

        /** Sets the embedding field. */
        @JsonProperty("embedding")
        public Builder withEmbedding(final @Nullable List<Float> value) {
            this.embedding = value;
            return this;
        }

        /** Sets the sparseEmbedding field. */
        @JsonProperty("sparse_embedding")
        public Builder withSparseEmbedding(final @Nullable SparseEmbedding value) {
            this.sparseEmbedding = value;
            return this;
        }

        /** Sets the lateInteraction field. */
        @JsonProperty("late_interaction")
        public Builder withLateInteraction(final @Nullable MultiVectorEmbedding value) {
            this.lateInteraction = value;
            return this;
        }

        /** Sets the metadata field. */
        @JsonProperty("metadata")
        public Builder withMetadata(final ChunkMetadata value) {
            this.metadata = value;
            return this;
        }

        /** Constructs a Chunk instance from the builder's current state. */
        public Chunk build() {
            return new Chunk(
                content,
                chunkType,
                embedding,
                sparseEmbedding,
                lateInteraction,
                metadata
            );
        }
    }
    // CPD-ON
}
