// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.Optional;

/**
 * Managed credential-provider configuration for OAuth2/STS-based authentication modes liter-llm
 * cannot express via a static {@code api_key}. See LlmConfig.credential_provider.
 *
 * {@code Debug} is implemented by hand: CredentialProviderConfig.AzureAd's {@code client_secret} is a
 * credential and must never be printed, matching LlmConfig's own redaction policy. The
 * other variants carry no secret material — CredentialProviderConfig.VertexOauth2 and
 * CredentialProviderConfig.BedrockWebIdentity reference a *file path*, never the key or
 * token itself.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({
    @JsonSubTypes.Type(value = CredentialProviderConfig.AzureAd.class, name = "azure_ad"),
    @JsonSubTypes.Type(value = CredentialProviderConfig.VertexOauth2.class, name = "vertex_oauth2"),
    @JsonSubTypes.Type(value = CredentialProviderConfig.VertexAdc.class, name = "vertex_adc"),
    @JsonSubTypes.Type(value = CredentialProviderConfig.BedrockWebIdentity.class, name = "bedrock_web_identity")
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface CredentialProviderConfig {

    /**
     * Azure AD OAuth2 client-credentials flow (Azure OpenAI / Azure Cognitive Services).
     */
    record AzureAd(
        @JsonProperty("tenant_id") String tenantId,
        @JsonProperty("client_id") String clientId,
        @JsonProperty("client_secret") String clientSecret,
        @JsonProperty("scope") Optional<String> scope
    ) implements CredentialProviderConfig {
    }

    /**
     * Google Vertex AI OAuth2 via a service-account JSON key file on disk.
     *
     * Points at a file path rather than embedding the key inline: the key file contains an
     * RSA private key — stronger secret material than an API key — and {@code LlmConfig} must never
     * carry that directly, matching the credential-handling policy the rest of this module
     * follows.
     */
    record VertexOauth2(
        @JsonProperty("service_account_key_file") String serviceAccountKeyFile,
        @JsonProperty("scope") Optional<String> scope
    ) implements CredentialProviderConfig {
    }

    /**
     * Google Vertex AI Application Default Credentials, resolved from the GCE/GKE/Cloud Run
     * metadata server. Carries no secret material at all.
     */
    record VertexAdc(@JsonProperty("scope") Optional<String> scope) implements CredentialProviderConfig { }

    /**
     * AWS STS {@code AssumeRoleWithWebIdentity} (EKS IRSA / OIDC federation) for Bedrock.
     */
    record BedrockWebIdentity(
        @JsonProperty("role_arn") String roleArn,
        @JsonProperty("token_file") String tokenFile,
        @JsonProperty("session_name") Optional<String> sessionName,
        @JsonProperty("region") Optional<String> region
    ) implements CredentialProviderConfig {
    }
}
