// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Structured per-language detection result: confidence, document share, and script —
 * the information the ISO-code-only {@code detected_languages} list cannot convey (#261).
 *
 * Populated by {@code language_detection} alongside {@code detected_languages}, with one
 * entry per language, in the same order as {@code detected_languages}.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LanguageConfidence.Builder.class)
public record LanguageConfidence(
    @JsonProperty("language") String language,
    @JsonProperty("confidence") double confidence,
    @JsonProperty("proportion") double proportion,
    @JsonProperty("script") String script,
    @JsonProperty("reliable") boolean reliable
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for LanguageConfidence deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private String language;
        private double confidence;
        private double proportion;
        private String script;
        private boolean reliable;

        /** Sets the language field. */
        @JsonProperty("language")
        public Builder withLanguage(final String value) {
            this.language = value;
            return this;
        }

        /** Sets the confidence field. */
        @JsonProperty("confidence")
        public Builder withConfidence(final double value) {
            this.confidence = value;
            return this;
        }

        /** Sets the proportion field. */
        @JsonProperty("proportion")
        public Builder withProportion(final double value) {
            this.proportion = value;
            return this;
        }

        /** Sets the script field. */
        @JsonProperty("script")
        public Builder withScript(final String value) {
            this.script = value;
            return this;
        }

        /** Sets the reliable field. */
        @JsonProperty("reliable")
        public Builder withReliable(final boolean value) {
            this.reliable = value;
            return this;
        }

        /** Constructs a LanguageConfidence instance from the builder's current state. */
        public LanguageConfidence build() {
            return new LanguageConfidence(
                language,
                confidence,
                proportion,
                script,
                reliable
            );
        }
    }
    // CPD-ON
}
