// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Budget enforcement configuration.
 *
 * Mirrors liter-llm's {@code LlmBudgetConfig}. Only takes effect when liter-llm's {@code tower}
 * feature is compiled in; otherwise the value round-trips through configuration
 * but is not enforced at request time.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LlmBudgetConfig.Builder.class)
public record LlmBudgetConfig(
    @Nullable @JsonProperty("global_limit") Double globalLimit,
    @Nullable @JsonProperty("model_limits") Map<String, Double> modelLimits,
    @Nullable @JsonProperty("enforcement") String enforcement
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for LlmBudgetConfig deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("global_limit")
        @Nullable private Double globalLimit;
        @JsonProperty("model_limits")
        @Nullable private Map<String, Double> modelLimits;
        @Nullable private String enforcement;

        /** Sets the globalLimit field. */
        @JsonProperty("global_limit")
        public Builder withGlobalLimit(final @Nullable Double value) {
            this.globalLimit = value;
            return this;
        }

        /** Sets the modelLimits field. */
        @JsonProperty("model_limits")
        public Builder withModelLimits(final @Nullable Map<String, Double> value) {
            this.modelLimits = value;
            return this;
        }

        /** Sets the enforcement field. */
        @JsonProperty("enforcement")
        public Builder withEnforcement(final @Nullable String value) {
            this.enforcement = value;
            return this;
        }

        /** Constructs a LlmBudgetConfig instance from the builder's current state. */
        public LlmBudgetConfig build() {
            return new LlmBudgetConfig(
                globalLimit,
                modelLimits,
                enforcement
            );
        }
    }
    // CPD-ON
}
