// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Response cache configuration.
 *
 * Mirrors liter-llm's {@code LlmCacheConfig}. Only takes effect when liter-llm's {@code tower}
 * feature is compiled in; otherwise the value round-trips through configuration
 * but is not consulted at request time.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LlmCacheConfig.Builder.class)
public record LlmCacheConfig(
    @Nullable @JsonProperty("max_entries") Long maxEntries,
    @Nullable @JsonProperty("ttl_seconds") Long ttlSeconds,
    @Nullable @JsonProperty("backend") String backend,
    @Nullable @JsonProperty("backend_config") Map<String, String> backendConfig
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for LlmCacheConfig deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("max_entries")
        @Nullable private Long maxEntries;
        @JsonProperty("ttl_seconds")
        @Nullable private Long ttlSeconds;
        @Nullable private String backend;
        @JsonProperty("backend_config")
        @Nullable private Map<String, String> backendConfig;

        /** Sets the maxEntries field. */
        @JsonProperty("max_entries")
        public Builder withMaxEntries(final @Nullable Long value) {
            this.maxEntries = value;
            return this;
        }

        /** Sets the ttlSeconds field. */
        @JsonProperty("ttl_seconds")
        public Builder withTtlSeconds(final @Nullable Long value) {
            this.ttlSeconds = value;
            return this;
        }

        /** Sets the backend field. */
        @JsonProperty("backend")
        public Builder withBackend(final @Nullable String value) {
            this.backend = value;
            return this;
        }

        /** Sets the backendConfig field. */
        @JsonProperty("backend_config")
        public Builder withBackendConfig(final @Nullable Map<String, String> value) {
            this.backendConfig = value;
            return this;
        }

        /** Constructs a LlmCacheConfig instance from the builder's current state. */
        public LlmCacheConfig build() {
            return new LlmCacheConfig(
                maxEntries,
                ttlSeconds,
                backend,
                backendConfig
            );
        }
    }
    // CPD-ON
}
