// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * A custom provider configuration entry, in addition to liter-llm's built-in providers.
 *
 * Mirrors liter-llm's {@code LlmProviderConfig}.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LlmProviderConfig.Builder.class)
public record LlmProviderConfig(
    @JsonProperty("name") String name,
    @JsonProperty("base_url") String baseUrl,
    @Nullable @JsonProperty("auth_header") String authHeader,
    @Nullable @JsonProperty("model_prefixes") List<String> modelPrefixes
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for LlmProviderConfig deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private String name;
        @JsonProperty("base_url")
        private String baseUrl;
        @JsonProperty("auth_header")
        @Nullable private String authHeader;
        @JsonProperty("model_prefixes")
        @Nullable private List<String> modelPrefixes;

        /** Sets the name field. */
        @JsonProperty("name")
        public Builder withName(final String value) {
            this.name = value;
            return this;
        }

        /** Sets the baseUrl field. */
        @JsonProperty("base_url")
        public Builder withBaseUrl(final String value) {
            this.baseUrl = value;
            return this;
        }

        /** Sets the authHeader field. */
        @JsonProperty("auth_header")
        public Builder withAuthHeader(final @Nullable String value) {
            this.authHeader = value;
            return this;
        }

        /** Sets the modelPrefixes field. */
        @JsonProperty("model_prefixes")
        public Builder withModelPrefixes(final @Nullable List<String> value) {
            this.modelPrefixes = value;
            return this;
        }

        /** Constructs a LlmProviderConfig instance from the builder's current state. */
        public LlmProviderConfig build() {
            return new LlmProviderConfig(
                name,
                baseUrl,
                authHeader,
                modelPrefixes
            );
        }
    }
    // CPD-ON
}
