// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Per-model rate limiting configuration.
 *
 * Mirrors liter-llm's {@code LlmRateLimitConfig}. Only takes effect when liter-llm's
 * {@code tower} feature is compiled in; otherwise the value round-trips through
 * configuration but is not enforced at request time.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LlmRateLimitConfig.Builder.class)
public record LlmRateLimitConfig(
    @Nullable @JsonProperty("rpm") Integer rpm,
    @Nullable @JsonProperty("tpm") Long tpm,
    @Nullable @JsonProperty("window_seconds") Long windowSeconds
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for LlmRateLimitConfig deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @Nullable private Integer rpm;
        @Nullable private Long tpm;
        @JsonProperty("window_seconds")
        @Nullable private Long windowSeconds;

        /** Sets the rpm field. */
        @JsonProperty("rpm")
        public Builder withRpm(final @Nullable Integer value) {
            this.rpm = value;
            return this;
        }

        /** Sets the tpm field. */
        @JsonProperty("tpm")
        public Builder withTpm(final @Nullable Long value) {
            this.tpm = value;
            return this;
        }

        /** Sets the windowSeconds field. */
        @JsonProperty("window_seconds")
        public Builder withWindowSeconds(final @Nullable Long value) {
            this.windowSeconds = value;
            return this;
        }

        /** Constructs a LlmRateLimitConfig instance from the builder's current state. */
        public LlmRateLimitConfig build() {
            return new LlmRateLimitConfig(
                rpm,
                tpm,
                windowSeconds
            );
        }
    }
    // CPD-ON
}
