// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Output format for extraction results.
 *
 * Controls the format of the {@code content} field in {@code ExtractedDocument}.
 * When set to {@code Markdown}, {@code Djot}, or {@code Html}, the output uses that format.
 * {@code Plain} returns the raw extracted text.
 * {@code Structured} is currently a metadata-only label: {@code derive_extraction_result}
 * returns {@code None} for it (see {@code extraction/derive.rs}), so no renderer runs and
 * the content is left exactly as {@code Plain} would leave it. Only
 * {@code metadata.output_format} differs. It does NOT attach OCR element data,
 * bounding boxes or confidence scores.
 */
@SuppressWarnings("PMD")
public enum OutputFormat {
    /**
     * Plain text content only (default)
     */
    Plain("plain"),
    /**
     * Markdown format
     */
    Markdown("markdown"),
    /**
     * Djot markup format
     */
    Djot("djot"),
    /**
     * HTML format
     */
    Html("html"),
    /**
     * JSON tree format with heading-driven sections.
     */
    Json("json"),
    /**
     * Metadata-only label; content is identical to OutputFormat.Plain.
     * No dedicated renderer exists yet, so this attaches no OCR element
     * metadata. See the enum-level docs above.
     */
    Structured("structured"),
    /**
     * Docling DocTags format (tables rendered as OTSL).
     */
    DocTags("doctags"),
    /**
     * Custom renderer registered via the RendererRegistry.
     * The string is the renderer name (e.g., "docx", "latex").
     */
    Custom("custom");


    /** The string value. */
    private final String value;

    OutputFormat(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static OutputFormat fromValue(final String value) {
        for (OutputFormat e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown OutputFormat value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
