// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Supported languages in PaddleOCR.
 *
 * Maps user-friendly language codes to paddle-ocr-rs language identifiers.
 */
@SuppressWarnings("PMD")
public enum PaddleLanguage {
    /**
     * English
     */
    English("English"),
    /**
     * Simplified Chinese
     */
    Chinese("Chinese"),
    /**
     * Japanese
     */
    Japanese("Japanese"),
    /**
     * Korean
     */
    Korean("Korean"),
    /**
     * German
     */
    German("German"),
    /**
     * French
     */
    French("French"),
    /**
     * Latin script (covers most European languages)
     */
    Latin("Latin"),
    /**
     * Cyrillic (Russian and related)
     */
    Cyrillic("Cyrillic"),
    /**
     * Traditional Chinese
     */
    TraditionalChinese("TraditionalChinese"),
    /**
     * Thai
     */
    Thai("Thai"),
    /**
     * Greek
     */
    Greek("Greek"),
    /**
     * East Slavic (Russian, Ukrainian, Belarusian)
     */
    EastSlavic("EastSlavic"),
    /**
     * Arabic (Arabic, Persian, Urdu)
     */
    Arabic("Arabic"),
    /**
     * Devanagari (Hindi, Marathi, Sanskrit, Nepali)
     */
    Devanagari("Devanagari"),
    /**
     * Tamil
     */
    Tamil("Tamil"),
    /**
     * Telugu
     */
    Telugu("Telugu");


    /** The string value. */
    private final String value;

    PaddleLanguage(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PaddleLanguage fromValue(final String value) {
        for (PaddleLanguage e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown PaddleLanguage value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
