// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * A PDF annotation extracted from a document page.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PdfAnnotation.Builder.class)
public record PdfAnnotation(
    @JsonProperty("annotation_type") PdfAnnotationType annotationType,
    @Nullable @JsonProperty("content") String content,
    @JsonProperty("page_number") int pageNumber,
    @Nullable @JsonProperty("bounding_box") BoundingBox boundingBox,
    @Nullable @JsonProperty("author") String author,
    @Nullable @JsonProperty("modified") String modified,
    @Nullable @JsonProperty("color") String color,
    @Nullable @JsonProperty("subject") String subject,
    @Nullable @JsonProperty("quad_points") List<BoundingBox> quadPoints,
    @Nullable @JsonProperty("marked_text") String markedText
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for PdfAnnotation deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("annotation_type")
        private PdfAnnotationType annotationType;
        @Nullable private String content;
        @JsonProperty("page_number")
        private int pageNumber;
        @JsonProperty("bounding_box")
        @Nullable private BoundingBox boundingBox;
        @Nullable private String author;
        @Nullable private String modified;
        @Nullable private String color;
        @Nullable private String subject;
        @JsonProperty("quad_points")
        @Nullable private List<BoundingBox> quadPoints;
        @JsonProperty("marked_text")
        @Nullable private String markedText;

        /** Sets the annotationType field. */
        @JsonProperty("annotation_type")
        public Builder withAnnotationType(final PdfAnnotationType value) {
            this.annotationType = value;
            return this;
        }

        /** Sets the content field. */
        @JsonProperty("content")
        public Builder withContent(final @Nullable String value) {
            this.content = value;
            return this;
        }

        /** Sets the pageNumber field. */
        @JsonProperty("page_number")
        public Builder withPageNumber(final int value) {
            this.pageNumber = value;
            return this;
        }

        /** Sets the boundingBox field. */
        @JsonProperty("bounding_box")
        public Builder withBoundingBox(final @Nullable BoundingBox value) {
            this.boundingBox = value;
            return this;
        }

        /** Sets the author field. */
        @JsonProperty("author")
        public Builder withAuthor(final @Nullable String value) {
            this.author = value;
            return this;
        }

        /** Sets the modified field. */
        @JsonProperty("modified")
        public Builder withModified(final @Nullable String value) {
            this.modified = value;
            return this;
        }

        /** Sets the color field. */
        @JsonProperty("color")
        public Builder withColor(final @Nullable String value) {
            this.color = value;
            return this;
        }

        /** Sets the subject field. */
        @JsonProperty("subject")
        public Builder withSubject(final @Nullable String value) {
            this.subject = value;
            return this;
        }

        /** Sets the quadPoints field. */
        @JsonProperty("quad_points")
        public Builder withQuadPoints(final @Nullable List<BoundingBox> value) {
            this.quadPoints = value;
            return this;
        }

        /** Sets the markedText field. */
        @JsonProperty("marked_text")
        public Builder withMarkedText(final @Nullable String value) {
            this.markedText = value;
            return this;
        }

        /** Constructs a PdfAnnotation instance from the builder's current state. */
        public PdfAnnotation build() {
            return new PdfAnnotation(
                annotationType,
                content,
                pageNumber,
                boundingBox,
                author,
                modified,
                color,
                subject,
                quadPoints,
                markedText
            );
        }
    }
    // CPD-ON
}
