// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type of PDF annotation.
 */
@SuppressWarnings("PMD")
public enum PdfAnnotationType {
    /**
     * Sticky note / text annotation
     */
    Text("text"),
    /**
     * Highlighted text region
     */
    Highlight("highlight"),
    /**
     * Hyperlink annotation
     */
    Link("link"),
    /**
     * Rubber stamp annotation
     */
    Stamp("stamp"),
    /**
     * Underline text markup
     */
    Underline("underline"),
    /**
     * Strikeout text markup
     */
    StrikeOut("strike_out"),
    /**
     * Squiggly (wavy) underline text markup
     */
    Squiggly("squiggly"),
    /**
     * Freehand drawing (ink) annotation
     */
    Ink("ink"),
    /**
     * Rectangle/box shape annotation
     */
    Square("square"),
    /**
     * Ellipse/oval shape annotation
     */
    Circle("circle"),
    /**
     * Closed polygon shape annotation
     */
    Polygon("polygon"),
    /**
     * Open polyline shape annotation
     */
    PolyLine("poly_line"),
    /**
     * Line annotation
     */
    Line("line"),
    /**
     * Caret (text-insertion marker) annotation
     */
    Caret("caret"),
    /**
     * Embedded file attachment annotation
     */
    FileAttachment("file_attachment"),
    /**
     * Embedded sound annotation
     */
    Sound("sound"),
    /**
     * Embedded movie annotation
     */
    Movie("movie"),
    /**
     * Any other annotation type
     */
    Other("other");


    /** The string value. */
    private final String value;

    PdfAnnotationType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PdfAnnotationType fromValue(final String value) {
        for (PdfAnnotationType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown PdfAnnotationType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
