// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Outcome of a single doctor check.
 */
@SuppressWarnings("PMD")
public enum ProbeStatus {
    /**
     * The backend or setting will work as configured.
     */
    Pass("pass"),
    /**
     * The check ran and found something actionable, but nothing is broken
     * (e.g. stray cache files, stale model revisions). Never fails the report.
     */
    Warn("warn"),
    /**
     * The configured setup will not work (or will silently degrade) on this host.
     */
    Fail("fail"),
    /**
     * The check cannot run locally (e.g. model not cached, feature not compiled in);
     * first real use decides, possibly after a download.
     */
    Skip("skip");


    /** The string value. */
    private final String value;

    ProbeStatus(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ProbeStatus fromValue(final String value) {
        for (ProbeStatus e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ProbeStatus value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
