// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Page Segmentation Mode for Tesseract OCR.
 */
@SuppressWarnings("PMD")
public enum PSMMode {
    /**
     * Orientation and script detection only.
     */
    OsdOnly("OsdOnly"),
    /**
     * Automatic page segmentation with OSD.
     */
    AutoOsd("AutoOsd"),
    /**
     * Automatic page segmentation without OSD or OCR.
     */
    AutoOnly("AutoOnly"),
    /**
     * Fully automatic page segmentation with no OSD (default).
     */
    Auto("Auto"),
    /**
     * Assume a single column of text of variable sizes.
     */
    SingleColumn("SingleColumn"),
    /**
     * Assume a single uniform block of vertically aligned text.
     */
    SingleBlockVertical("SingleBlockVertical"),
    /**
     * Assume a single uniform block of text.
     */
    SingleBlock("SingleBlock"),
    /**
     * Treat the image as a single text line.
     */
    SingleLine("SingleLine"),
    /**
     * Treat the image as a single word.
     */
    SingleWord("SingleWord"),
    /**
     * Treat the image as a single word in a circle.
     */
    CircleWord("CircleWord"),
    /**
     * Treat the image as a single character.
     */
    SingleChar("SingleChar");


    /** The string value. */
    private final String value;

    PSMMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PSMMode fromValue(final String value) {
        for (PSMMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown PSMMode value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
