// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.util.List;
@SuppressWarnings("PMD")
public final class XbergRs {
    private XbergRs() { }

    /**
     * Extract content from a single bytes or URI input.
     */
    public static ExtractionResult extract(final ExtractInput input, final ExtractionConfig config) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var cinputJson = input != null ? MAPPER.writeValueAsString(input) : null;
            var cinputJsonSeg = cinputJson != null ? arena.allocateFrom(cinputJson) : MemorySegment.NULL;
            var cinput = cinputJson != null
                ? (MemorySegment) NativeLib.XBERG_EXTRACT_INPUT_FROM_JSON.invoke(cinputJsonSeg)
                : MemorySegment.NULL;
            if (cinputJson != null && cinput.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create input from JSON");
            }
            var cconfigJson = config != null ? MAPPER.writeValueAsString(config) : null;
            var cconfigJsonSeg = cconfigJson != null ? arena.allocateFrom(cconfigJson) : MemorySegment.NULL;
            var cconfig = cconfigJson != null
                ? (MemorySegment) NativeLib.XBERG_EXTRACTION_CONFIG_FROM_JSON.invoke(cconfigJsonSeg)
                : MemorySegment.NULL;
            if (cconfigJson != null && cconfig.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create config from JSON");
            }
            var resultPtr = (MemorySegment) NativeLib.XBERG_EXTRACT.invoke(cinput, cconfig);
            if (!cinput.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_EXTRACT_INPUT_FREE.invoke(cinput);
            }
            if (!cconfig.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_EXTRACTION_CONFIG_FREE.invoke(cconfig);
            }
            if (resultPtr.equals(MemorySegment.NULL)) {
                checkLastError();                return null;            }
            // CPD-OFF
            var jsonPtr = (MemorySegment) NativeLib.XBERG_EXTRACTION_RESULT_TO_JSON.invoke(resultPtr);
            NativeLib.XBERG_EXTRACTION_RESULT_FREE.invoke(resultPtr);
            if (jsonPtr.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new XbergRsException("extract: failed to serialize response", null);
            }
            String json = jsonPtr.reinterpret(Long.MAX_VALUE).getString(0);
            NativeLib.XBERG_FREE_STRING.invoke(jsonPtr);
            return MAPPER.readValue(json, ExtractionResult.class);
            // CPD-ON
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Extract content from multiple bytes or URI inputs.
     */
    public static ExtractionResult extractBatch(final List<ExtractInput> inputs, final ExtractionConfig config) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var cinputsJson = MAPPER.writerFor(MAPPER.getTypeFactory().constructCollectionType(java.util.List.class, ExtractInput.class)).writeValueAsString(inputs);
            var cinputs = arena.allocateFrom(cinputsJson);
            var cconfigJson = config != null ? MAPPER.writeValueAsString(config) : null;
            var cconfigJsonSeg = cconfigJson != null ? arena.allocateFrom(cconfigJson) : MemorySegment.NULL;
            var cconfig = cconfigJson != null
                ? (MemorySegment) NativeLib.XBERG_EXTRACTION_CONFIG_FROM_JSON.invoke(cconfigJsonSeg)
                : MemorySegment.NULL;
            if (cconfigJson != null && cconfig.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create config from JSON");
            }
            var resultPtr = (MemorySegment) NativeLib.XBERG_EXTRACT_BATCH.invoke(cinputs, cconfig);
            if (!cconfig.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_EXTRACTION_CONFIG_FREE.invoke(cconfig);
            }
            if (resultPtr.equals(MemorySegment.NULL)) {
                checkLastError();                return null;            }
            // CPD-OFF
            var jsonPtr = (MemorySegment) NativeLib.XBERG_EXTRACTION_RESULT_TO_JSON.invoke(resultPtr);
            NativeLib.XBERG_EXTRACTION_RESULT_FREE.invoke(resultPtr);
            if (jsonPtr.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new XbergRsException("extractBatch: failed to serialize response", null);
            }
            String json = jsonPtr.reinterpret(Long.MAX_VALUE).getString(0);
            NativeLib.XBERG_FREE_STRING.invoke(jsonPtr);
            return MAPPER.readValue(json, ExtractionResult.class);
            // CPD-ON
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Discover all pages and sitemaps reachable from {@code uri} without extracting document content.
     *
     * Builds a crawlberg.CrawlEngine from {@code config.crawl}, calls
     * CrawlEngine.map, and returns the set of discovered URLs as a
     * crawlberg.MapResult (re-exported as {@code MapResult}).
     *
     * Use this when you need the URL inventory of a site before committing to
     * full document extraction — e.g. to build a crawl queue or validate scope.
     * {@literal @}throws XbergRsException Returns {@code Validation} if the crawl configuration fails
     * validation or if the map operation itself fails.
     */
    public static MapResult mapUrl(final String uri, final UrlExtractionConfig config) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var curi = arena.allocateFrom(uri);
            var cconfigJson = config != null ? MAPPER.writeValueAsString(config) : null;
            var cconfigJsonSeg = cconfigJson != null ? arena.allocateFrom(cconfigJson) : MemorySegment.NULL;
            var cconfig = cconfigJson != null
                ? (MemorySegment) NativeLib.XBERG_URL_EXTRACTION_CONFIG_FROM_JSON.invoke(cconfigJsonSeg)
                : MemorySegment.NULL;
            if (cconfigJson != null && cconfig.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create config from JSON");
            }
            var resultPtr = (MemorySegment) NativeLib.XBERG_MAP_URL.invoke(curi, cconfig);
            if (!cconfig.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_URL_EXTRACTION_CONFIG_FREE.invoke(cconfig);
            }
            if (resultPtr.equals(MemorySegment.NULL)) {
                checkLastError();                return null;            }
            // CPD-OFF
            var jsonPtr = (MemorySegment) NativeLib.XBERG_MAP_RESULT_TO_JSON.invoke(resultPtr);
            NativeLib.XBERG_MAP_RESULT_FREE.invoke(resultPtr);
            if (jsonPtr.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new XbergRsException("mapUrl: failed to serialize response", null);
            }
            String json = jsonPtr.reinterpret(Long.MAX_VALUE).getString(0);
            NativeLib.XBERG_FREE_STRING.invoke(jsonPtr);
            return MAPPER.readValue(json, MapResult.class);
            // CPD-ON
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * List all supported document formats.
     *
     * Returns every file extension Xberg recognizes together with its
     * corresponding MIME type, derived from the central format registry.
     * Formats that have no registered file extension (such as source code,
     * which is detected dynamically) are not included.
     *
     * The static {@code EXT_TO_MIME} table lists every format the *codebase* knows how
     * to describe, regardless of which Cargo features were compiled in. Advertising
     * that table directly would claim support for extractors that may not exist in
     * this build (see GH#1387). To keep the advertised catalogue honest, the table
     * is intersected with the document extractor registry: an extension is only
     * included if some registered extractor actually claims its MIME type in this
     * build. This can never drift from reality and automatically covers
     * third-party extractors registered at runtime.
     *
     * The list is sorted alphabetically by file extension.
     * {@literal @}return A vector of SupportedFormat entries sorted by extension, limited to
     * formats with a registered extractor in this build.
     */
    public static List<SupportedFormat> listSupportedFormats() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_LIST_SUPPORTED_FORMATS.invoke();
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<SupportedFormat>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Ensure built-in extractors are registered.
     *
     * This function is called automatically on first extraction operation.
     * It's safe to call multiple times - registration only happens once,
     * unless the registry was cleared, in which case extractors are re-registered.
     *
     * Public so a caller that wants to *inspect* the registry — rather than extract —
     * can populate it directly. Without this the only way to trigger registration is to
     * run a real extraction, which {@code xberg formats} would otherwise have to fake (#233).
     */
    public static void ensureInitialized() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            NativeLib.XBERG_ENSURE_INITIALIZED.invoke();
            checkLastError();
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * List the names of all registered embedding backends.
     *
     * Used by {@code xberg-cli}, the api/mcp endpoints, and generated language
     * bindings.
     */
    public static List<String> listEmbeddingBackends() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_LIST_EMBEDDING_BACKENDS.invoke();
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<String>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * List names of all registered document extractors.
     */
    public static List<String> listDocumentExtractors() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_LIST_DOCUMENT_EXTRACTORS.invoke();
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<String>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * List all registered OCR backends.
     *
     * Returns the names of all OCR backends currently registered in the global registry.
     * {@literal @}return A vector of OCR backend names.
     */
    public static List<String> listOcrBackends() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_LIST_OCR_BACKENDS.invoke();
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<String>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * List all registered post-processor names.
     *
     * Returns a vector of all post-processor names currently registered in the
     * global registry.
     * {@literal @}return - {@code Ok(Vec&lt;String&gt;)} - Vector of post-processor names
     * - {@code Err(...)} if the registry lock is poisoned
     */
    public static List<String> listPostProcessors() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_LIST_POST_PROCESSORS.invoke();
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<String>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * List names of all registered renderers.
     * {@literal @}throws XbergRsException Returns an error if the registry lock is poisoned.
     */
    public static List<String> listRenderers() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_LIST_RENDERERS.invoke();
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<String>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * List the names of all registered reranker backends.
     *
     * Used by {@code xberg-cli}, the api/mcp endpoints, and generated language
     * bindings.
     *
     * Since v5.0.0.
     */
    public static List<String> listRerankerBackends() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_LIST_RERANKER_BACKENDS.invoke();
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<String>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * List the names of all registered tokenizer backends.
     *
     * Used by {@code xberg-cli}, the api/mcp endpoints, and generated language
     * bindings.
     */
    public static List<String> listTokenizerBackends() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_LIST_TOKENIZER_BACKENDS.invoke();
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<String>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * List names of all registered validators.
     */
    public static List<String> listValidators() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_LIST_VALIDATORS.invoke();
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<String>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Run chunk classification against an extraction result.
     *
     * Mutates {@code ChunkMetadata.classifications} on every chunk in
     * {@code result.chunks} and appends every LLM call's usage to {@code result.llm_usage}.
     * A chunk whose classification batch call fails (or that the model omitted
     * from its response) is simply left with an empty {@code classifications} vector for
     * that chunk, unless the failure is a validation error (empty config) or every
     * batch task fails, in which case the first error is returned.
     * {@literal @}throws XbergRsException Returns {@code Validation} when {@code config.definitions} is empty.
     * Returns the first batch error encountered when rendering the prompt or
     * calling the LLM fails for every batch; partial failures on a subset of
     * batches are recorded here as a {@code ProcessingWarning} on {@code result} instead of
     * aborting the whole run.
     */
    public static void classifyChunks(final ExtractedDocument result, final ChunkClassificationConfig config) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var cresultJson = result != null ? MAPPER.writeValueAsString(result) : null;
            var cresultJsonSeg = cresultJson != null ? arena.allocateFrom(cresultJson) : MemorySegment.NULL;
            var cresult = cresultJson != null
                ? (MemorySegment) NativeLib.XBERG_EXTRACTED_DOCUMENT_FROM_JSON.invoke(cresultJsonSeg)
                : MemorySegment.NULL;
            if (cresultJson != null && cresult.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create result from JSON");
            }
            var cconfigJson = config != null ? MAPPER.writeValueAsString(config) : null;
            var cconfigJsonSeg = cconfigJson != null ? arena.allocateFrom(cconfigJson) : MemorySegment.NULL;
            var cconfig = cconfigJson != null
                ? (MemorySegment) NativeLib.XBERG_CHUNK_CLASSIFICATION_CONFIG_FROM_JSON.invoke(cconfigJsonSeg)
                : MemorySegment.NULL;
            if (cconfigJson != null && cconfig.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create config from JSON");
            }
            NativeLib.XBERG_CLASSIFY_CHUNKS.invoke(cresult, cconfig);
            if (!cresult.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_EXTRACTED_DOCUMENT_FREE.invoke(cresult);
            }
            if (!cconfig.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_CHUNK_CLASSIFICATION_CONFIG_FREE.invoke(cconfig);
            }
            checkLastError();
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Find unmarked claims in markdown text.
     *
     * Returns lines that assert a claim but carry neither a footnote citation anchor ({@code [^...]})
     * nor an inference marker ({@code [*inference*]}).
     *
     * The heuristic is simple: a line that contains alphabetic words, ends with sentence punctuation,
     * and is not a heading, blank line, or markup-only line is considered a claim.
     * Exclude lines that appear in the citation block (after {@code ---} + {@code &lt;!-- citations ... --&gt;}).
     * {@literal @}param markdown The markdown text to search
     *
     * {@literal @}return A vector of trimmed line text strings for unmarked claims.
     */
    public static List<String> findUnmarkedClaims(final String markdown) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var cmarkdown = arena.allocateFrom(markdown);
            var resultPtr = (MemorySegment) NativeLib.XBERG_FIND_UNMARKED_CLAIMS.invoke(cmarkdown);
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<String>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Verify that an excerpt appears verbatim in source text.
     *
     * Performs exact matching by default. Also tries whitespace-normalized matching
     * (collapsing runs of whitespace on both sides) since PDF-extracted text often
     * has irregular spacing.
     * {@literal @}param excerpt The text snippet to find
     *
     * {@literal @}param sourceText The full source text to search
     *
     * {@literal @}return {@code true} if the excerpt appears (exactly or with normalized whitespace), {@code false} otherwise.
     */
    public static boolean verifyExcerpt(final String excerpt, final String sourceText) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var cexcerpt = arena.allocateFrom(excerpt);
            var csourceText = arena.allocateFrom(sourceText);
            var primitiveResult = (long) NativeLib.XBERG_VERIFY_EXCERPT.invoke(cexcerpt, csourceText);
            return primitiveResult != 0;
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Async wrapper over embed_sparse: runs the blocking ONNX inference on a
     * bounded blocking-task pool so it does not stall the async runtime.
     *
     * Since v5.0.0.
     */
    public static List<SparseEmbedding> embedSparseAsync(
        final List<String> texts,
        final SparseEmbeddingConfig config
    ) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var ctextsJson = MAPPER.writerFor(MAPPER.getTypeFactory().constructCollectionType(java.util.List.class, String.class)).writeValueAsString(texts);
            var ctexts = arena.allocateFrom(ctextsJson);
            var cconfigJson = config != null ? MAPPER.writeValueAsString(config) : null;
            var cconfigJsonSeg = cconfigJson != null ? arena.allocateFrom(cconfigJson) : MemorySegment.NULL;
            var cconfig = cconfigJson != null
                ? (MemorySegment) NativeLib.XBERG_SPARSE_EMBEDDING_CONFIG_FROM_JSON.invoke(cconfigJsonSeg)
                : MemorySegment.NULL;
            if (cconfigJson != null && cconfig.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create config from JSON");
            }
            var resultPtr = (MemorySegment) NativeLib.XBERG_EMBED_SPARSE_ASYNC.invoke(ctexts, cconfig);
            if (!cconfig.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_SPARSE_EMBEDDING_CONFIG_FREE.invoke(cconfig);
            }
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<SparseEmbedding>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Score a query against a document using ColBERT's MaxSim operator: for each
     * query token vector, take the maximum dot product against any document
     * token vector, then sum across query tokens.
     *
     * Returns {@code 0.0} if {@code query} and {@code doc} have mismatched dimensionality, if either
     * has zero tokens, or if either is not well-formed per
     * MultiVectorEmbedding.is_well_formed (its {@code data} length does not match
     * {@code num_tokens * dim}).
     *
     * Pure CPU primitive — available without ONNX Runtime.
     *
     * Since v5.0.0.
     */
    public static double maxSimScore(final MultiVectorEmbedding query, final MultiVectorEmbedding doc) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var cqueryJson = query != null ? MAPPER.writeValueAsString(query) : null;
            var cqueryJsonSeg = cqueryJson != null ? arena.allocateFrom(cqueryJson) : MemorySegment.NULL;
            var cquery = cqueryJson != null
                ? (MemorySegment) NativeLib.XBERG_MULTI_VECTOR_EMBEDDING_FROM_JSON.invoke(cqueryJsonSeg)
                : MemorySegment.NULL;
            if (cqueryJson != null && cquery.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create query from JSON");
            }
            var cdocJson = doc != null ? MAPPER.writeValueAsString(doc) : null;
            var cdocJsonSeg = cdocJson != null ? arena.allocateFrom(cdocJson) : MemorySegment.NULL;
            var cdoc = cdocJson != null
                ? (MemorySegment) NativeLib.XBERG_MULTI_VECTOR_EMBEDDING_FROM_JSON.invoke(cdocJsonSeg)
                : MemorySegment.NULL;
            if (cdocJson != null && cdoc.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create doc from JSON");
            }
            var primitiveResult = (double) NativeLib.XBERG_MAX_SIM_SCORE.invoke(cquery, cdoc);
            if (!cquery.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_MULTI_VECTOR_EMBEDDING_FREE.invoke(cquery);
            }
            if (!cdoc.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_MULTI_VECTOR_EMBEDDING_FREE.invoke(cdoc);
            }
            return primitiveResult;
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Rank a set of documents against a query by MaxSim score, descending.
     *
     * Mirrors the sort/truncate shape of {@code crate.reranking}'s {@code build_results},
     * minus top-k truncation (callers slice the returned {@code Vec} themselves).
     *
     * Pure CPU primitive — available without ONNX Runtime.
     *
     * Since v5.0.0.
     */
    public static List<LateInteractionMatch> maxSimRank(
        final MultiVectorEmbedding query,
        final List<MultiVectorEmbedding> docs
    ) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var cqueryJson = query != null ? MAPPER.writeValueAsString(query) : null;
            var cqueryJsonSeg = cqueryJson != null ? arena.allocateFrom(cqueryJson) : MemorySegment.NULL;
            var cquery = cqueryJson != null
                ? (MemorySegment) NativeLib.XBERG_MULTI_VECTOR_EMBEDDING_FROM_JSON.invoke(cqueryJsonSeg)
                : MemorySegment.NULL;
            if (cqueryJson != null && cquery.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create query from JSON");
            }
            var cdocsJson = MAPPER.writerFor(MAPPER.getTypeFactory().constructCollectionType(java.util.List.class, MultiVectorEmbedding.class)).writeValueAsString(docs);
            var cdocs = arena.allocateFrom(cdocsJson);
            var resultPtr = (MemorySegment) NativeLib.XBERG_MAX_SIM_RANK.invoke(cquery, cdocs);
            if (!cquery.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_MULTI_VECTOR_EMBEDDING_FREE.invoke(cquery);
            }
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<LateInteractionMatch>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Async wrapper over embed_multi_vector: runs the blocking ONNX inference
     * on a bounded blocking-task pool so it does not stall the async runtime.
     *
     * Since v5.0.0.
     */
    public static List<MultiVectorEmbedding> embedMultiVectorAsync(
        final List<String> texts,
        final LateInteractionConfig config,
        final boolean isQuery
    ) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var ctextsJson = MAPPER.writerFor(MAPPER.getTypeFactory().constructCollectionType(java.util.List.class, String.class)).writeValueAsString(texts);
            var ctexts = arena.allocateFrom(ctextsJson);
            var cconfigJson = config != null ? MAPPER.writeValueAsString(config) : null;
            var cconfigJsonSeg = cconfigJson != null ? arena.allocateFrom(cconfigJson) : MemorySegment.NULL;
            var cconfig = cconfigJson != null
                ? (MemorySegment) NativeLib.XBERG_LATE_INTERACTION_CONFIG_FROM_JSON.invoke(cconfigJsonSeg)
                : MemorySegment.NULL;
            if (cconfigJson != null && cconfig.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create config from JSON");
            }
            var resultPtr = (MemorySegment) NativeLib.XBERG_EMBED_MULTI_VECTOR_ASYNC.invoke(ctexts, cconfig, (isQuery ? 1 : 0));
            if (!cconfig.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_LATE_INTERACTION_CONFIG_FREE.invoke(cconfig);
            }
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<MultiVectorEmbedding>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Probe the backends and settings in {@code config} and report what will actually
     * execute on this host.
     *
     * Runs no downloads and no billable API calls. Backends that are not compiled
     * in or whose models are not cached report {@code Skip} rather than failing.
     */
    public static DoctorReport doctor(final ExtractionConfig config) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var cconfigJson = config != null ? MAPPER.writeValueAsString(config) : null;
            var cconfigJsonSeg = cconfigJson != null ? arena.allocateFrom(cconfigJson) : MemorySegment.NULL;
            var cconfig = cconfigJson != null
                ? (MemorySegment) NativeLib.XBERG_EXTRACTION_CONFIG_FROM_JSON.invoke(cconfigJsonSeg)
                : MemorySegment.NULL;
            if (cconfigJson != null && cconfig.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new IllegalStateException("failed to create config from JSON");
            }
            var resultPtr = (MemorySegment) NativeLib.XBERG_DOCTOR.invoke(cconfig);
            if (!cconfig.equals(MemorySegment.NULL)) {
                NativeLib.XBERG_EXTRACTION_CONFIG_FREE.invoke(cconfig);
            }
            if (resultPtr.equals(MemorySegment.NULL)) {
                checkLastError();                return null;            }
            // CPD-OFF
            var jsonPtr = (MemorySegment) NativeLib.XBERG_DOCTOR_REPORT_TO_JSON.invoke(resultPtr);
            NativeLib.XBERG_DOCTOR_REPORT_FREE.invoke(resultPtr);
            if (jsonPtr.equals(MemorySegment.NULL)) {
                checkLastError();
                throw new XbergRsException("doctor: failed to serialize response", null);
            }
            String json = jsonPtr.reinterpret(Long.MAX_VALUE).getString(0);
            NativeLib.XBERG_FREE_STRING.invoke(jsonPtr);
            return MAPPER.readValue(json, DoctorReport.class);
            // CPD-ON
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Install PdfOxideWarningCapture as the process-wide {@code log} backend,
     * exactly once.
     *
     * If another component already installed a {@code log.Log} implementation (an
     * application wiring {@code env_logger}, for instance), {@code log.set_boxed_logger}
     * fails and this is a no-op: we do not fight over ownership of the global
     * logger slot, and we do not touch {@code log.set_max_level} unless our install
     * won, so we never silently raise or lower a level someone else configured.
     * In that case {@code pdf_oxide}'s glyph-drop records go wherever that other
     * logger sends them instead of into take_pdf_oxide_render_warnings.
     * **Opt-in.** Nothing calls this automatically, and that is deliberate: xberg
     * is a library, and {@code log} has exactly one global backend slot per process. A
     * library that claims it on its own behalf breaks its embedder — a host that
     * later calls {@code env_logger.init()} panics, and until this returns, every
     * {@code log} record in the process is routed here rather than wherever the host
     * intended. That decision belongs to the application, so it is exposed as a
     * call an application makes knowingly.
     *
     * Returns {@code true} if this call (or an earlier one) installed the capture, and
     * {@code false} if some other component already owns the {@code log} backend — in which
     * case {@code pdf_oxide}'s glyph-drop records go to that logger and
     * take_pdf_oxide_render_warnings stays empty.
     *
     * Without this call the #1364 warnings are not produced. The glyph drop
     * itself is decided inside {@code pdf_oxide}, which reports it only through
     * {@code log.warn!}; there is no return-value channel to read instead.
     */
    public static boolean installPdfRenderDiagnostics() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var primitiveResult = (long) NativeLib.XBERG_INSTALL_PDF_RENDER_DIAGNOSTICS.invoke();
            return primitiveResult != 0;
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Drain the glyph-drop ProcessingWarnings accumulated on this thread by
     * render calls since the last call to this function.
     *
     * Callers that render pages as part of extraction should call this after
     * their render pass and merge the result into
     * {@code InternalDocument.processing_warnings} (see the module-level convention
     * in {@code crate.core.diagnostics}) so a page with missing glyphs is never
     * returned to the user without a signal. Warnings are already deduped
     * per-thread across all pages rendered before this call.
     *
     * {@code pub} (rather than {@code pub(crate)}) so both in-tree render-consumers and the
     * regression test for #1364 can observe capture without depending on any
     * one extractor's internal state.
     *
     * As of #340, {@code crate.extractors.pdf.mod} drains this unconditionally right
     * after assembling a document's {@code processing_warnings}, so every PDF
     * extraction that renders at least one page picks up any captured
     * glyph-drop warnings for free. ~keep: that drain only ever observes
     * warnings from render calls that happened on the *same OS thread* before it
     * ran, because PDF_OXIDE_PENDING_WARNINGS is thread-local. OCR page
     * rendering runs inline on the extracting task's thread, so it is covered.
     * Layout-detection rasterization runs inside {@code tokio.task.spawn_blocking},
     * which always executes on a different OS thread, so this function alone
     * would never see those warnings. As of #353,
     * {@code extractors.pdf.layout_runner.run_layout_for_pdf_pages_async} drains
     * this function itself from inside its {@code spawn_blocking} closure — the only
     * place that can observe the blocking-pool thread's thread-local buffer —
     * and threads the drained warnings back through its return value for the
     * caller in {@code extractors.pdf.mod} to merge, so layout-path glyph drops are
     * no longer silently lost.
     */
    public static List<ProcessingWarning> takePdfOxideRenderWarnings() throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_TAKE_PDF_OXIDE_RENDER_WARNINGS.invoke();
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<ProcessingWarning>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Build the four (or three) token Whisper decoder prompt.
     *
     * The canonical Whisper prompt is
     * {@code [&lt;|startoftranscript|&gt;, &lt;|{lang}|&gt;, &lt;|transcribe|&gt;, &lt;|notimestamps|&gt;]}.
     * When {@code timestamps} is {@code true}, the trailing {@code no_timestamps} token is omitted
     * so the model is free to emit {@code &lt;|x.xx|&gt;} timestamp tokens in its output
     * instead of being forced to suppress them.
     */
    public static List<Long> buildDecoderPromptTokens(
        final int startOfTranscript,
        final int langId,
        final int transcribe,
        final int noTimestamps,
        final boolean timestamps
    ) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var resultPtr = (MemorySegment) NativeLib.XBERG_BUILD_DECODER_PROMPT_TOKENS.invoke(
                startOfTranscript,
                langId,
                transcribe,
                noTimestamps,
                (timestamps ? 1 : 0)
            );
            return readJsonList(resultPtr, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<Long>>() { });
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    /**
     * Convert a raw Whisper timestamp token ID to a millisecond offset from the
     * start of the 30-second chunk it was decoded in.
     *
     * {@code token_id} must be {@code &gt;= timestamp_begin_id}; IDs below that are ordinary
     * vocabulary tokens, not timestamps.
     */
    public static int timestampTokenToMs(final int tokenId, final int timestampBeginId) throws XbergRsException {
        try (var arena = Arena.ofShared()) {
            var primitiveResult = (int)(long) NativeLib.XBERG_TIMESTAMP_TOKEN_TO_MS.invoke(tokenId, timestampBeginId);
            return primitiveResult;
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }

    // Helper methods for FFI marshalling

    private static void checkLastError() throws Throwable {
        int errCode = (int)(long) NativeLib.XBERG_LAST_ERROR_CODE.invoke();
        if (errCode != 0) {
            var ctxPtr = (MemorySegment) NativeLib.XBERG_LAST_ERROR_CONTEXT.invoke();
            String msg = ctxPtr.reinterpret(Long.MAX_VALUE).getString(0);
            switch (errCode) {
                case 1 -> throw new InvalidInputException(msg);
                case 2 -> throw new ConversionErrorException(msg);
                case 2080723056 -> throw new IoException(msg);
                case 191686562 -> throw new ParsingException(msg);
                case 1744734248 -> throw new OcrException(msg);
                case 2093146707 -> throw new ValidationException(msg);
                case 1740547354 -> throw new CacheException(msg);
                case 1703658036 -> throw new ImageProcessingException(msg);
                case 486450251 -> throw new SerializationException(msg);
                case 1024192803 -> throw new MissingDependencyException(msg);
                case 1609738224 -> throw new PluginException(msg);
                case 1092832257 -> throw new LockPoisonedException(msg);
                case 299497109 -> throw new UnsupportedFormatException(msg);
                case 1958776963 -> throw new EmbeddingException(msg);
                case 1326275648 -> throw new RerankingException(msg);
                case 552614954 -> throw new TranscriptionException(msg);
                case 1036077712 -> throw new TimeoutException(msg);
                case 524666238 -> throw new CancelledException(msg);
                case 670246576 -> throw new SecurityException(msg);
                case 1318675240 -> throw new OtherException(msg);
                case 91451556 -> throw new ConfigErrorException(msg);
                case 1713417319 -> throw new PdfAnalysisErrorException(msg);
                case 949858217 -> throw new ParseException(msg);
                case 380113526 -> throw new SchemaValidationException(msg);
                case 2093946153 -> throw new DeserializeException(msg);
                case 2137750517 -> throw new IdMismatchException(msg);
                case 1285484759 -> throw new BadMetaSchemaException(msg);
                case 973217713 -> throw new IoException(msg);
                case 1772672798 -> throw new SchemaNotObjectException(msg);
                default -> throw new XbergRsException(errCode, msg);
            }
        }
    }
    private static com.fasterxml.jackson.databind.ObjectMapper createObjectMapper() {
        var mapper = new com.fasterxml.jackson.databind.ObjectMapper()
            .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
            .findAndRegisterModules()
            .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
            .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.ALWAYS)
            .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true);
        var module = new com.fasterxml.jackson.databind.module.SimpleModule();
        module.addSerializer(byte[].class, new ByteArraySerializer());
        mapper.registerModule(module);
        return mapper;
    }

    private static final com.fasterxml.jackson.databind.ObjectMapper MAPPER = createObjectMapper();
    private static <T> java.util.List<T> readJsonList(
        MemorySegment resultPtr,
        com.fasterxml.jackson.core.type.TypeReference<java.util.List<T>> typeRef
    ) throws XbergRsException {
        try {
            if (resultPtr.equals(MemorySegment.NULL)) {
                checkLastError();
                return java.util.List.of();
            }
            String json = resultPtr.reinterpret(Long.MAX_VALUE).getString(0);
            NativeLib.XBERG_FREE_STRING.invoke(resultPtr);
            return MAPPER.readValue(json, typeRef);
        } catch (Throwable e) {
            throw new XbergRsException("FFI call failed", e);
        }
    }
}
