// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg;

import java.util.List;
@SuppressWarnings("PMD")
public final class Xberg {
    private Xberg() { }

    /**
     * Extract content from a single bytes or URI input.
     */
    public static ExtractionResult extract(final ExtractInput input, final ExtractionConfig config) throws XbergRsException {
        java.util.Objects.requireNonNull(input, "input must not be null");
        java.util.Objects.requireNonNull(config, "config must not be null");
        return XbergRs.extract(input, config);
    }

    /**
     * Extract content from multiple bytes or URI inputs.
     */
    public static ExtractionResult extractBatch(final List<ExtractInput> inputs, final ExtractionConfig config) throws XbergRsException {
        java.util.Objects.requireNonNull(inputs, "inputs must not be null");
        java.util.Objects.requireNonNull(config, "config must not be null");
        return XbergRs.extractBatch(inputs, config);
    }

    /**
     * Discover all pages and sitemaps reachable from {@code uri} without extracting document content.
     *
     * Builds a crawlberg.CrawlEngine from {@code config.crawl}, calls
     * CrawlEngine.map, and returns the set of discovered URLs as a
     * crawlberg.MapResult (re-exported as {@code MapResult}).
     *
     * Use this when you need the URL inventory of a site before committing to
     * full document extraction — e.g. to build a crawl queue or validate scope.
     * {@literal @}throws XbergRsException Returns {@code Validation} if the crawl configuration fails
     * validation or if the map operation itself fails.
     */
    public static MapResult mapUrl(final String uri, final UrlExtractionConfig config) throws XbergRsException {
        java.util.Objects.requireNonNull(uri, "uri must not be null");
        java.util.Objects.requireNonNull(config, "config must not be null");
        return XbergRs.mapUrl(uri, config);
    }

    /**
     * List all supported document formats.
     *
     * Returns every file extension Xberg recognizes together with its
     * corresponding MIME type, derived from the central format registry.
     * Formats that have no registered file extension (such as source code,
     * which is detected dynamically) are not included.
     *
     * The static {@code EXT_TO_MIME} table lists every format the *codebase* knows how
     * to describe, regardless of which Cargo features were compiled in. Advertising
     * that table directly would claim support for extractors that may not exist in
     * this build (see GH#1387). To keep the advertised catalogue honest, the table
     * is intersected with the document extractor registry: an extension is only
     * included if some registered extractor actually claims its MIME type in this
     * build. This can never drift from reality and automatically covers
     * third-party extractors registered at runtime.
     *
     * The list is sorted alphabetically by file extension.
     * {@literal @}return A vector of SupportedFormat entries sorted by extension, limited to
     * formats with a registered extractor in this build.
     */
    public static List<SupportedFormat> listSupportedFormats() throws XbergRsException {
        return XbergRs.listSupportedFormats();
    }

    /**
     * Ensure built-in extractors are registered.
     *
     * This function is called automatically on first extraction operation.
     * It's safe to call multiple times - registration only happens once,
     * unless the registry was cleared, in which case extractors are re-registered.
     *
     * Public so a caller that wants to *inspect* the registry — rather than extract —
     * can populate it directly. Without this the only way to trigger registration is to
     * run a real extraction, which {@code xberg formats} would otherwise have to fake (#233).
     */
    public static void ensureInitialized() throws XbergRsException {
        XbergRs.ensureInitialized();
    }

    /**
     * List the names of all registered embedding backends.
     *
     * Used by {@code xberg-cli}, the api/mcp endpoints, and generated language
     * bindings.
     */
    public static List<String> listEmbeddingBackends() throws XbergRsException {
        return XbergRs.listEmbeddingBackends();
    }

    /**
     * List names of all registered document extractors.
     */
    public static List<String> listDocumentExtractors() throws XbergRsException {
        return XbergRs.listDocumentExtractors();
    }

    /**
     * List all registered OCR backends.
     *
     * Returns the names of all OCR backends currently registered in the global registry.
     * {@literal @}return A vector of OCR backend names.
     */
    public static List<String> listOcrBackends() throws XbergRsException {
        return XbergRs.listOcrBackends();
    }

    /**
     * List all registered post-processor names.
     *
     * Returns a vector of all post-processor names currently registered in the
     * global registry.
     * {@literal @}return - {@code Ok(Vec&lt;String&gt;)} - Vector of post-processor names
     * - {@code Err(...)} if the registry lock is poisoned
     */
    public static List<String> listPostProcessors() throws XbergRsException {
        return XbergRs.listPostProcessors();
    }

    /**
     * List names of all registered renderers.
     * {@literal @}throws XbergRsException Returns an error if the registry lock is poisoned.
     */
    public static List<String> listRenderers() throws XbergRsException {
        return XbergRs.listRenderers();
    }

    /**
     * List the names of all registered reranker backends.
     *
     * Used by {@code xberg-cli}, the api/mcp endpoints, and generated language
     * bindings.
     *
     * Since v5.0.0.
     */
    public static List<String> listRerankerBackends() throws XbergRsException {
        return XbergRs.listRerankerBackends();
    }

    /**
     * List the names of all registered tokenizer backends.
     *
     * Used by {@code xberg-cli}, the api/mcp endpoints, and generated language
     * bindings.
     */
    public static List<String> listTokenizerBackends() throws XbergRsException {
        return XbergRs.listTokenizerBackends();
    }

    /**
     * List names of all registered validators.
     */
    public static List<String> listValidators() throws XbergRsException {
        return XbergRs.listValidators();
    }

    /**
     * Run chunk classification against an extraction result.
     *
     * Mutates {@code ChunkMetadata.classifications} on every chunk in
     * {@code result.chunks} and appends every LLM call's usage to {@code result.llm_usage}.
     * A chunk whose classification batch call fails (or that the model omitted
     * from its response) is simply left with an empty {@code classifications} vector for
     * that chunk, unless the failure is a validation error (empty config) or every
     * batch task fails, in which case the first error is returned.
     * {@literal @}throws XbergRsException Returns {@code Validation} when {@code config.definitions} is empty.
     * Returns the first batch error encountered when rendering the prompt or
     * calling the LLM fails for every batch; partial failures on a subset of
     * batches are recorded here as a {@code ProcessingWarning} on {@code result} instead of
     * aborting the whole run.
     */
    public static void classifyChunks(final ExtractedDocument result, final ChunkClassificationConfig config) throws XbergRsException {
        java.util.Objects.requireNonNull(result, "result must not be null");
        java.util.Objects.requireNonNull(config, "config must not be null");
        XbergRs.classifyChunks(result, config);
    }

    /**
     * Find unmarked claims in markdown text.
     *
     * Returns lines that assert a claim but carry neither a footnote citation anchor ({@code [^...]})
     * nor an inference marker ({@code [*inference*]}).
     *
     * The heuristic is simple: a line that contains alphabetic words, ends with sentence punctuation,
     * and is not a heading, blank line, or markup-only line is considered a claim.
     * Exclude lines that appear in the citation block (after {@code ---} + {@code &lt;!-- citations ... --&gt;}).
     * {@literal @}param markdown The markdown text to search
     *
     * {@literal @}return A vector of trimmed line text strings for unmarked claims.
     */
    public static List<String> findUnmarkedClaims(final String markdown) throws XbergRsException {
        java.util.Objects.requireNonNull(markdown, "markdown must not be null");
        return XbergRs.findUnmarkedClaims(markdown);
    }

    /**
     * Verify that an excerpt appears verbatim in source text.
     *
     * Performs exact matching by default. Also tries whitespace-normalized matching
     * (collapsing runs of whitespace on both sides) since PDF-extracted text often
     * has irregular spacing.
     * {@literal @}param excerpt The text snippet to find
     *
     * {@literal @}param sourceText The full source text to search
     *
     * {@literal @}return {@code true} if the excerpt appears (exactly or with normalized whitespace), {@code false} otherwise.
     */
    public static boolean verifyExcerpt(final String excerpt, final String sourceText) throws XbergRsException {
        java.util.Objects.requireNonNull(excerpt, "excerpt must not be null");
        java.util.Objects.requireNonNull(sourceText, "sourceText must not be null");
        return XbergRs.verifyExcerpt(excerpt, sourceText);
    }

    /**
     * Async wrapper over embed_sparse: runs the blocking ONNX inference on a
     * bounded blocking-task pool so it does not stall the async runtime.
     *
     * Since v5.0.0.
     */
    public static List<SparseEmbedding> embedSparseAsync(
        final List<String> texts,
        final SparseEmbeddingConfig config
    ) throws XbergRsException {
        java.util.Objects.requireNonNull(texts, "texts must not be null");
        java.util.Objects.requireNonNull(config, "config must not be null");
        return XbergRs.embedSparseAsync(texts, config);
    }

    /**
     * Score a query against a document using ColBERT's MaxSim operator: for each
     * query token vector, take the maximum dot product against any document
     * token vector, then sum across query tokens.
     *
     * Returns {@code 0.0} if {@code query} and {@code doc} have mismatched dimensionality, if either
     * has zero tokens, or if either is not well-formed per
     * MultiVectorEmbedding.is_well_formed (its {@code data} length does not match
     * {@code num_tokens * dim}).
     *
     * Pure CPU primitive — available without ONNX Runtime.
     *
     * Since v5.0.0.
     */
    public static double maxSimScore(final MultiVectorEmbedding query, final MultiVectorEmbedding doc) throws XbergRsException {
        java.util.Objects.requireNonNull(query, "query must not be null");
        java.util.Objects.requireNonNull(doc, "doc must not be null");
        return XbergRs.maxSimScore(query, doc);
    }

    /**
     * Rank a set of documents against a query by MaxSim score, descending.
     *
     * Mirrors the sort/truncate shape of {@code crate.reranking}'s {@code build_results},
     * minus top-k truncation (callers slice the returned {@code Vec} themselves).
     *
     * Pure CPU primitive — available without ONNX Runtime.
     *
     * Since v5.0.0.
     */
    public static List<LateInteractionMatch> maxSimRank(
        final MultiVectorEmbedding query,
        final List<MultiVectorEmbedding> docs
    ) throws XbergRsException {
        java.util.Objects.requireNonNull(query, "query must not be null");
        java.util.Objects.requireNonNull(docs, "docs must not be null");
        return XbergRs.maxSimRank(query, docs);
    }

    /**
     * Async wrapper over embed_multi_vector: runs the blocking ONNX inference
     * on a bounded blocking-task pool so it does not stall the async runtime.
     *
     * Since v5.0.0.
     */
    public static List<MultiVectorEmbedding> embedMultiVectorAsync(
        final List<String> texts,
        final LateInteractionConfig config,
        final boolean isQuery
    ) throws XbergRsException {
        java.util.Objects.requireNonNull(texts, "texts must not be null");
        java.util.Objects.requireNonNull(config, "config must not be null");
        java.util.Objects.requireNonNull(isQuery, "isQuery must not be null");
        return XbergRs.embedMultiVectorAsync(texts, config, isQuery);
    }

    /**
     * Probe the backends and settings in {@code config} and report what will actually
     * execute on this host.
     *
     * Runs no downloads and no billable API calls. Backends that are not compiled
     * in or whose models are not cached report {@code Skip} rather than failing.
     */
    public static DoctorReport doctor(final ExtractionConfig config) throws XbergRsException {
        java.util.Objects.requireNonNull(config, "config must not be null");
        return XbergRs.doctor(config);
    }

    /**
     * Install PdfOxideWarningCapture as the process-wide {@code log} backend,
     * exactly once.
     *
     * If another component already installed a {@code log.Log} implementation (an
     * application wiring {@code env_logger}, for instance), {@code log.set_boxed_logger}
     * fails and this is a no-op: we do not fight over ownership of the global
     * logger slot, and we do not touch {@code log.set_max_level} unless our install
     * won, so we never silently raise or lower a level someone else configured.
     * In that case {@code pdf_oxide}'s glyph-drop records go wherever that other
     * logger sends them instead of into take_pdf_oxide_render_warnings.
     * **Opt-in.** Nothing calls this automatically, and that is deliberate: xberg
     * is a library, and {@code log} has exactly one global backend slot per process. A
     * library that claims it on its own behalf breaks its embedder — a host that
     * later calls {@code env_logger.init()} panics, and until this returns, every
     * {@code log} record in the process is routed here rather than wherever the host
     * intended. That decision belongs to the application, so it is exposed as a
     * call an application makes knowingly.
     *
     * Returns {@code true} if this call (or an earlier one) installed the capture, and
     * {@code false} if some other component already owns the {@code log} backend — in which
     * case {@code pdf_oxide}'s glyph-drop records go to that logger and
     * take_pdf_oxide_render_warnings stays empty.
     *
     * Without this call the #1364 warnings are not produced. The glyph drop
     * itself is decided inside {@code pdf_oxide}, which reports it only through
     * {@code log.warn!}; there is no return-value channel to read instead.
     */
    public static boolean installPdfRenderDiagnostics() throws XbergRsException {
        return XbergRs.installPdfRenderDiagnostics();
    }

    /**
     * Drain the glyph-drop ProcessingWarnings accumulated on this thread by
     * render calls since the last call to this function.
     *
     * Callers that render pages as part of extraction should call this after
     * their render pass and merge the result into
     * {@code InternalDocument.processing_warnings} (see the module-level convention
     * in {@code crate.core.diagnostics}) so a page with missing glyphs is never
     * returned to the user without a signal. Warnings are already deduped
     * per-thread across all pages rendered before this call.
     *
     * {@code pub} (rather than {@code pub(crate)}) so both in-tree render-consumers and the
     * regression test for #1364 can observe capture without depending on any
     * one extractor's internal state.
     *
     * As of #340, {@code crate.extractors.pdf.mod} drains this unconditionally right
     * after assembling a document's {@code processing_warnings}, so every PDF
     * extraction that renders at least one page picks up any captured
     * glyph-drop warnings for free. ~keep: that drain only ever observes
     * warnings from render calls that happened on the *same OS thread* before it
     * ran, because PDF_OXIDE_PENDING_WARNINGS is thread-local. OCR page
     * rendering runs inline on the extracting task's thread, so it is covered.
     * Layout-detection rasterization runs inside {@code tokio.task.spawn_blocking},
     * which always executes on a different OS thread, so this function alone
     * would never see those warnings. As of #353,
     * {@code extractors.pdf.layout_runner.run_layout_for_pdf_pages_async} drains
     * this function itself from inside its {@code spawn_blocking} closure — the only
     * place that can observe the blocking-pool thread's thread-local buffer —
     * and threads the drained warnings back through its return value for the
     * caller in {@code extractors.pdf.mod} to merge, so layout-path glyph drops are
     * no longer silently lost.
     */
    public static List<ProcessingWarning> takePdfOxideRenderWarnings() throws XbergRsException {
        return XbergRs.takePdfOxideRenderWarnings();
    }

    /**
     * Build the four (or three) token Whisper decoder prompt.
     *
     * The canonical Whisper prompt is
     * {@code [&lt;|startoftranscript|&gt;, &lt;|{lang}|&gt;, &lt;|transcribe|&gt;, &lt;|notimestamps|&gt;]}.
     * When {@code timestamps} is {@code true}, the trailing {@code no_timestamps} token is omitted
     * so the model is free to emit {@code &lt;|x.xx|&gt;} timestamp tokens in its output
     * instead of being forced to suppress them.
     */
    public static List<Long> buildDecoderPromptTokens(
        final int startOfTranscript,
        final int langId,
        final int transcribe,
        final int noTimestamps,
        final boolean timestamps
    ) throws XbergRsException {
        java.util.Objects.requireNonNull(startOfTranscript, "startOfTranscript must not be null");
        java.util.Objects.requireNonNull(langId, "langId must not be null");
        java.util.Objects.requireNonNull(transcribe, "transcribe must not be null");
        java.util.Objects.requireNonNull(noTimestamps, "noTimestamps must not be null");
        java.util.Objects.requireNonNull(timestamps, "timestamps must not be null");
        return XbergRs.buildDecoderPromptTokens(startOfTranscript, langId, transcribe, noTimestamps, timestamps);
    }

    /**
     * Convert a raw Whisper timestamp token ID to a millisecond offset from the
     * start of the 30-second chunk it was decoded in.
     *
     * {@code token_id} must be {@code &gt;= timestamp_begin_id}; IDs below that are ordinary
     * vocabulary tokens, not timestamps.
     */
    public static int timestampTokenToMs(final int tokenId, final int timestampBeginId) throws XbergRsException {
        java.util.Objects.requireNonNull(tokenId, "tokenId must not be null");
        java.util.Objects.requireNonNull(timestampBeginId, "timestampBeginId must not be null");
        return XbergRs.timestampTokenToMs(tokenId, timestampBeginId);
    }
    public static void registerOcrBackend(final IOcrBackend impl) throws XbergRsException {
        try {
            OcrBackendBridge.registerOcrBackend(impl);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void unregisterOcrBackend(final String name) throws XbergRsException {
        try {
            OcrBackendBridge.unregisterOcrBackend(name);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void clearOcrBackends() throws XbergRsException {
        try {
            OcrBackendBridge.clearOcrBackends();
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void registerPostProcessor(final IPostProcessor impl) throws XbergRsException {
        try {
            PostProcessorBridge.registerPostProcessor(impl);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void unregisterPostProcessor(final String name) throws XbergRsException {
        try {
            PostProcessorBridge.unregisterPostProcessor(name);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void clearPostProcessors() throws XbergRsException {
        try {
            PostProcessorBridge.clearPostProcessors();
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void registerValidator(final IValidator impl) throws XbergRsException {
        try {
            ValidatorBridge.registerValidator(impl);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void unregisterValidator(final String name) throws XbergRsException {
        try {
            ValidatorBridge.unregisterValidator(name);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void clearValidators() throws XbergRsException {
        try {
            ValidatorBridge.clearValidators();
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void registerDocumentExtractor(final IDocumentExtractor impl) throws XbergRsException {
        try {
            DocumentExtractorBridge.registerDocumentExtractor(impl);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void unregisterDocumentExtractor(final String name) throws XbergRsException {
        try {
            DocumentExtractorBridge.unregisterDocumentExtractor(name);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void clearDocumentExtractors() throws XbergRsException {
        try {
            DocumentExtractorBridge.clearDocumentExtractors();
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void registerEmbeddingBackend(final IEmbeddingBackend impl) throws XbergRsException {
        try {
            EmbeddingBackendBridge.registerEmbeddingBackend(impl);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void unregisterEmbeddingBackend(final String name) throws XbergRsException {
        try {
            EmbeddingBackendBridge.unregisterEmbeddingBackend(name);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void clearEmbeddingBackends() throws XbergRsException {
        try {
            EmbeddingBackendBridge.clearEmbeddingBackends();
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void registerRenderer(final IRenderer impl) throws XbergRsException {
        try {
            RendererBridge.registerRenderer(impl);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void unregisterRenderer(final String name) throws XbergRsException {
        try {
            RendererBridge.unregisterRenderer(name);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void clearRenderers() throws XbergRsException {
        try {
            RendererBridge.clearRenderers();
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void registerRerankerBackend(final IRerankerBackend impl) throws XbergRsException {
        try {
            RerankerBackendBridge.registerRerankerBackend(impl);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void unregisterRerankerBackend(final String name) throws XbergRsException {
        try {
            RerankerBackendBridge.unregisterRerankerBackend(name);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void clearRerankerBackends() throws XbergRsException {
        try {
            RerankerBackendBridge.clearRerankerBackends();
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void registerTokenizerBackend(final ITokenizerBackend impl) throws XbergRsException {
        try {
            TokenizerBackendBridge.registerTokenizerBackend(impl);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void unregisterTokenizerBackend(final String name) throws XbergRsException {
        try {
            TokenizerBackendBridge.unregisterTokenizerBackend(name);
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }

    public static void clearTokenizerBackends() throws XbergRsException {
        try {
            TokenizerBackendBridge.clearTokenizerBackends();
        } catch (Exception e) {
            throw new XbergRsException(e.getMessage(), e);
        }
    }


}
