# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.1.0"
end
