<?php

// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace Xberg;

final class Xberg
{
    /**
     * Extract content from a single bytes or URI input.
     *
     * @param ExtractInput $input
     * @param ExtractionConfig $config
     * @return ExtractionResult
     * @throws \Xberg\XbergException
     */
    public static function extract(
ExtractInput $input, ExtractionConfig $config): ExtractionResult
    {
        return \Xberg\XbergApi::extract($input, $config); // delegate to native extension class
    }
    /**
     * Extract content from multiple bytes or URI inputs.
     *
     * @param array<ExtractInput> $inputs
     * @param ExtractionConfig $config
     * @return ExtractionResult
     * @throws \Xberg\XbergException
     */
    public static function extractBatch(
array $inputs, ExtractionConfig $config): ExtractionResult
    {
        return \Xberg\XbergApi::extractBatch($inputs, $config); // delegate to native extension class
    }
    /**
     * Discover all pages and sitemaps reachable from `uri` without extracting document content.
     *
     * Builds a [`crawlberg::CrawlEngine`] from `config.crawl`, calls
     * [`CrawlEngine::map`], and returns the set of discovered URLs as a
     * [`crawlberg::MapResult`] (re-exported as `MapResult`).
     *
     * Use this when you need the URL inventory of a site before committing to
     * full document extraction — e.g. to build a crawl queue or validate scope.
     *
     * @param string $uri
     * @param UrlExtractionConfig $config
     * @return MapResult
     * @throws \Xberg\XbergException
     */
    public static function mapUrl(
string $uri, UrlExtractionConfig $config): MapResult
    {
        return \Xberg\XbergApi::mapUrl($uri, $config); // delegate to native extension class
    }
    /**
     * List all supported document formats.
     *
     * Returns every file extension Xberg recognizes together with its
     * corresponding MIME type, derived from the central format registry.
     * Formats that have no registered file extension (such as source code,
     * which is detected dynamically) are not included.
     *
     * The static `EXT_TO_MIME` table lists every format the *codebase* knows how
     * to describe, regardless of which Cargo features were compiled in. Advertising
     * that table directly would claim support for extractors that may not exist in
     * this build (see GH#1387). To keep the advertised catalogue honest, the table
     * is intersected with the document extractor registry: an extension is only
     * included if some registered extractor actually claims its MIME type in this
     * build. This can never drift from reality and automatically covers
     * third-party extractors registered at runtime.
     *
     * The list is sorted alphabetically by file extension.
     *
     * @return array<SupportedFormat>
     */
    public static function listSupportedFormats(): array {
        return \Xberg\XbergApi::listSupportedFormats(); // delegate to native extension class
    }
    /**
     * Ensure built-in extractors are registered.
     *
     * This function is called automatically on first extraction operation.
     * It's safe to call multiple times - registration only happens once,
     * unless the registry was cleared, in which case extractors are re-registered.
     *
     * Public so a caller that wants to *inspect* the registry — rather than extract —
     * can populate it directly. Without this the only way to trigger registration is to
     * run a real extraction, which `xberg formats` would otherwise have to fake (#233).
     *
     * @return void
     * @throws \Xberg\XbergException
     */
    public static function ensureInitialized(): void {
        \Xberg\XbergApi::ensureInitialized(); // delegate to native extension class
    }
    /**
     * List the names of all registered embedding backends.
     *
     * Used by `xberg-cli`, the api/mcp endpoints, and generated language
     * bindings.
     *
     * @return array<string>
     * @throws \Xberg\XbergException
     */
    public static function listEmbeddingBackends(): array {
        return \Xberg\XbergApi::listEmbeddingBackends(); // delegate to native extension class
    }
    /**
     * List names of all registered document extractors.
     *
     * @return array<string>
     * @throws \Xberg\XbergException
     */
    public static function listDocumentExtractors(): array {
        return \Xberg\XbergApi::listDocumentExtractors(); // delegate to native extension class
    }
    /**
     * List all registered OCR backends.
     *
     * Returns the names of all OCR backends currently registered in the global registry.
     *
     * @return array<string>
     * @throws \Xberg\XbergException
     */
    public static function listOcrBackends(): array {
        return \Xberg\XbergApi::listOcrBackends(); // delegate to native extension class
    }
    /**
     * List all registered post-processor names.
     *
     * Returns a vector of all post-processor names currently registered in the
     * global registry.
     *
     * @return array<string>
     * @throws \Xberg\XbergException
     */
    public static function listPostProcessors(): array {
        return \Xberg\XbergApi::listPostProcessors(); // delegate to native extension class
    }
    /**
     * List names of all registered renderers.
     *
     * @return array<string>
     * @throws \Xberg\XbergException
     */
    public static function listRenderers(): array {
        return \Xberg\XbergApi::listRenderers(); // delegate to native extension class
    }
    /**
     * List the names of all registered reranker backends.
     *
     * Used by `xberg-cli`, the api/mcp endpoints, and generated language
     * bindings.
     *
     * Since v5.0.0.
     *
     * @return array<string>
     * @throws \Xberg\XbergException
     */
    public static function listRerankerBackends(): array {
        return \Xberg\XbergApi::listRerankerBackends(); // delegate to native extension class
    }
    /**
     * List the names of all registered tokenizer backends.
     *
     * Used by `xberg-cli`, the api/mcp endpoints, and generated language
     * bindings.
     *
     * @return array<string>
     * @throws \Xberg\XbergException
     */
    public static function listTokenizerBackends(): array {
        return \Xberg\XbergApi::listTokenizerBackends(); // delegate to native extension class
    }
    /**
     * List names of all registered validators.
     *
     * @return array<string>
     * @throws \Xberg\XbergException
     */
    public static function listValidators(): array {
        return \Xberg\XbergApi::listValidators(); // delegate to native extension class
    }
    /**
     * Run chunk classification against an extraction result.
     *
     * Mutates `ChunkMetadata::classifications` on every chunk in
     * `result.chunks` and appends every LLM call's usage to `result.llm_usage`.
     * A chunk whose classification batch call fails (or that the model omitted
     * from its response) is simply left with an empty `classifications` vector for
     * that chunk, unless the failure is a validation error (empty config) or every
     * batch task fails, in which case the first error is returned.
     *
     * @param ExtractedDocument $result
     * @param ChunkClassificationConfig $config
     * @return void
     * @throws \Xberg\XbergException
     */
    public static function classifyChunks(
ExtractedDocument $result, ChunkClassificationConfig $config): void
    {
        \Xberg\XbergApi::classifyChunks($result, $config); // delegate to native extension class
    }
    /**
     * Find unmarked claims in markdown text.
     *
     * Returns lines that assert a claim but carry neither a footnote citation anchor (`[^...]`)
     * nor an inference marker (`[*inference*]`).
     *
     * The heuristic is simple: a line that contains alphabetic words, ends with sentence punctuation,
     * and is not a heading, blank line, or markup-only line is considered a claim.
     * Exclude lines that appear in the citation block (after `---` + `<!-- citations ... -->`).
     *
     * @param string $markdown
     * @return array<string>
     */
    public static function findUnmarkedClaims(
string $markdown): array
    {
        return \Xberg\XbergApi::findUnmarkedClaims($markdown); // delegate to native extension class
    }
    /**
     * Verify that an excerpt appears verbatim in source text.
     *
     * Performs exact matching by default. Also tries whitespace-normalized matching
     * (collapsing runs of whitespace on both sides) since PDF-extracted text often
     * has irregular spacing.
     *
     * @param string $excerpt
     * @param string $source_text
     * @return bool
     */
    public static function verifyExcerpt(
string $excerpt, string $source_text): bool
    {
        return \Xberg\XbergApi::verifyExcerpt($excerpt, $source_text); // delegate to native extension class
    }
    /**
     * Score a query against a document using ColBERT's MaxSim operator: for each
     * query token vector, take the maximum dot product against any document
     * token vector, then sum across query tokens.
     *
     * Returns `0.0` if `query` and `doc` have mismatched dimensionality, if either
     * has zero tokens, or if either is not well-formed per
     * [`MultiVectorEmbedding::is_well_formed`] (its `data` length does not match
     * `num_tokens * dim`).
     *
     * Pure CPU primitive — available without ONNX Runtime.
     *
     * Since v5.0.0.
     *
     * @param MultiVectorEmbedding $query
     * @param MultiVectorEmbedding $doc
     * @return float
     */
    public static function maxSimScore(
MultiVectorEmbedding $query, MultiVectorEmbedding $doc): float
    {
        return \Xberg\XbergApi::maxSimScore($query, $doc); // delegate to native extension class
    }
    /**
     * Rank a set of documents against a query by MaxSim score, descending.
     *
     * Mirrors the sort/truncate shape of `crate::reranking`'s `build_results`,
     * minus top-k truncation (callers slice the returned `Vec` themselves).
     *
     * Pure CPU primitive — available without ONNX Runtime.
     *
     * Since v5.0.0.
     *
     * @param MultiVectorEmbedding $query
     * @param array<MultiVectorEmbedding> $docs
     * @return array<LateInteractionMatch>
     */
    public static function maxSimRank(
MultiVectorEmbedding $query, array $docs): array
    {
        return \Xberg\XbergApi::maxSimRank($query, $docs); // delegate to native extension class
    }
    /**
     * Probe the backends and settings in `config` and report what will actually
     * execute on this host.
     *
     * Runs no downloads and no billable API calls. Backends that are not compiled
     * in or whose models are not cached report `Skip` rather than failing.
     *
     * @param ExtractionConfig $config
     * @return DoctorReport
     */
    public static function doctor(
ExtractionConfig $config): DoctorReport
    {
        return \Xberg\XbergApi::doctor($config); // delegate to native extension class
    }
    /**
     * Install [`PdfOxideWarningCapture`] as the process-wide `log` backend,
     * exactly once.
     *
     * If another component already installed a `log::Log` implementation (an
     * application wiring `env_logger`, for instance), `log::set_boxed_logger`
     * fails and this is a no-op: we do not fight over ownership of the global
     * logger slot, and we do not touch `log::set_max_level` unless our install
     * won, so we never silently raise or lower a level someone else configured.
     * In that case `pdf_oxide`'s glyph-drop records go wherever that other
     * logger sends them instead of into [`take_pdf_oxide_render_warnings`].
     * **Opt-in.** Nothing calls this automatically, and that is deliberate: xberg
     * is a library, and `log` has exactly one global backend slot per process. A
     * library that claims it on its own behalf breaks its embedder — a host that
     * later calls `env_logger::init()` panics, and until this returns, every
     * `log` record in the process is routed here rather than wherever the host
     * intended. That decision belongs to the application, so it is exposed as a
     * call an application makes knowingly.
     *
     * Returns `true` if this call (or an earlier one) installed the capture, and
     * `false` if some other component already owns the `log` backend — in which
     * case `pdf_oxide`'s glyph-drop records go to that logger and
     * [`take_pdf_oxide_render_warnings`] stays empty.
     *
     * Without this call the #1364 warnings are not produced. The glyph drop
     * itself is decided inside `pdf_oxide`, which reports it only through
     * `log::warn!`; there is no return-value channel to read instead.
     *
     * @return bool
     */
    public static function installPdfRenderDiagnostics(): bool {
        return \Xberg\XbergApi::installPdfRenderDiagnostics(); // delegate to native extension class
    }
    /**
     * Drain the glyph-drop [`ProcessingWarning`]s accumulated on this thread by
     * render calls since the last call to this function.
     *
     * Callers that render pages as part of extraction should call this after
     * their render pass and merge the result into
     * `InternalDocument::processing_warnings` (see the module-level convention
     * in `crate::core::diagnostics`) so a page with missing glyphs is never
     * returned to the user without a signal. Warnings are already deduped
     * per-thread across all pages rendered before this call.
     *
     * `pub` (rather than `pub(crate)`) so both in-tree render-consumers and the
     * regression test for #1364 can observe capture without depending on any
     * one extractor's internal state.
     *
     * As of #340, `crate::extractors::pdf::mod` drains this unconditionally right
     * after assembling a document's `processing_warnings`, so every PDF
     * extraction that renders at least one page picks up any captured
     * glyph-drop warnings for free. ~keep: that drain only ever observes
     * warnings from render calls that happened on the *same OS thread* before it
     * ran, because [`PDF_OXIDE_PENDING_WARNINGS`] is thread-local. OCR page
     * rendering runs inline on the extracting task's thread, so it is covered.
     * Layout-detection rasterization runs inside `tokio::task::spawn_blocking`,
     * which always executes on a different OS thread, so this function alone
     * would never see those warnings. As of #353,
     * `extractors::pdf::layout_runner::run_layout_for_pdf_pages_async` drains
     * this function itself from inside its `spawn_blocking` closure — the only
     * place that can observe the blocking-pool thread's thread-local buffer —
     * and threads the drained warnings back through its return value for the
     * caller in `extractors::pdf::mod` to merge, so layout-path glyph drops are
     * no longer silently lost.
     *
     * @return array<ProcessingWarning>
     */
    public static function takePdfOxideRenderWarnings(): array {
        return \Xberg\XbergApi::takePdfOxideRenderWarnings(); // delegate to native extension class
    }
    /**
     * Build the four (or three) token Whisper decoder prompt.
     *
     * The canonical Whisper prompt is
     * `[<|startoftranscript|>, <|{lang}|>, <|transcribe|>, <|notimestamps|>]`.
     * When `timestamps` is `true`, the trailing `no_timestamps` token is omitted
     * so the model is free to emit `<|x.xx|>` timestamp tokens in its output
     * instead of being forced to suppress them.
     *
     * @param int $start_of_transcript
     * @param int $lang_id
     * @param int $transcribe
     * @param int $no_timestamps
     * @param bool $timestamps
     * @return array<int>
     */
    public static function buildDecoderPromptTokens(
int $start_of_transcript, int $lang_id, int $transcribe, int $no_timestamps, bool $timestamps): array
    {
        return \Xberg\XbergApi::buildDecoderPromptTokens($start_of_transcript, $lang_id, $transcribe, $no_timestamps, $timestamps); // delegate to native extension class
    }
    /**
     * Convert a raw Whisper timestamp token ID to a millisecond offset from the
     * start of the 30-second chunk it was decoded in.
     *
     * `token_id` must be `>= timestamp_begin_id`; IDs below that are ordinary
     * vocabulary tokens, not timestamps.
     *
     * @param int $token_id
     * @param int $timestamp_begin_id
     * @return int
     */
    public static function timestampTokenToMs(
int $token_id, int $timestamp_begin_id): int
    {
        return \Xberg\XbergApi::timestampTokenToMs($token_id, $timestamp_begin_id); // delegate to native extension class
    }
    /**
     * registerOcrBackend.
     *
     * @param OcrBackend $backend
     * @return void
     */
    public static function registerOcrBackend(
OcrBackend $backend) : void
    {
        \Xberg\XbergApi::registerOcrBackend($backend); // delegate to native extension class
    }
    /**
     * unregisterOcrBackend.
     *
     * @param string $name
     * @return void
     */
    public static function unregisterOcrBackend(
string $name) : void
    {
        \Xberg\XbergApi::unregisterOcrBackend($name); // delegate to native extension class
    }
    /**
     * clearOcrBackends.
     *
     * @return void
     */
    public static function clearOcrBackends(
) : void
    {
        \Xberg\XbergApi::clearOcrBackends(); // delegate to native extension class
    }
    /**
     * registerPostProcessor.
     *
     * @param PostProcessor $backend
     * @return void
     */
    public static function registerPostProcessor(
PostProcessor $backend) : void
    {
        \Xberg\XbergApi::registerPostProcessor($backend); // delegate to native extension class
    }
    /**
     * unregisterPostProcessor.
     *
     * @param string $name
     * @return void
     */
    public static function unregisterPostProcessor(
string $name) : void
    {
        \Xberg\XbergApi::unregisterPostProcessor($name); // delegate to native extension class
    }
    /**
     * clearPostProcessors.
     *
     * @return void
     */
    public static function clearPostProcessors(
) : void
    {
        \Xberg\XbergApi::clearPostProcessors(); // delegate to native extension class
    }
    /**
     * registerValidator.
     *
     * @param Validator $backend
     * @return void
     */
    public static function registerValidator(
Validator $backend) : void
    {
        \Xberg\XbergApi::registerValidator($backend); // delegate to native extension class
    }
    /**
     * unregisterValidator.
     *
     * @param string $name
     * @return void
     */
    public static function unregisterValidator(
string $name) : void
    {
        \Xberg\XbergApi::unregisterValidator($name); // delegate to native extension class
    }
    /**
     * clearValidators.
     *
     * @return void
     */
    public static function clearValidators(
) : void
    {
        \Xberg\XbergApi::clearValidators(); // delegate to native extension class
    }
    /**
     * registerDocumentExtractor.
     *
     * @param DocumentExtractor $backend
     * @return void
     */
    public static function registerDocumentExtractor(
DocumentExtractor $backend) : void
    {
        \Xberg\XbergApi::registerDocumentExtractor($backend); // delegate to native extension class
    }
    /**
     * unregisterDocumentExtractor.
     *
     * @param string $name
     * @return void
     */
    public static function unregisterDocumentExtractor(
string $name) : void
    {
        \Xberg\XbergApi::unregisterDocumentExtractor($name); // delegate to native extension class
    }
    /**
     * clearDocumentExtractors.
     *
     * @return void
     */
    public static function clearDocumentExtractors(
) : void
    {
        \Xberg\XbergApi::clearDocumentExtractors(); // delegate to native extension class
    }
    /**
     * registerEmbeddingBackend.
     *
     * @param EmbeddingBackend $backend
     * @return void
     */
    public static function registerEmbeddingBackend(
EmbeddingBackend $backend) : void
    {
        \Xberg\XbergApi::registerEmbeddingBackend($backend); // delegate to native extension class
    }
    /**
     * unregisterEmbeddingBackend.
     *
     * @param string $name
     * @return void
     */
    public static function unregisterEmbeddingBackend(
string $name) : void
    {
        \Xberg\XbergApi::unregisterEmbeddingBackend($name); // delegate to native extension class
    }
    /**
     * clearEmbeddingBackends.
     *
     * @return void
     */
    public static function clearEmbeddingBackends(
) : void
    {
        \Xberg\XbergApi::clearEmbeddingBackends(); // delegate to native extension class
    }
    /**
     * registerRenderer.
     *
     * @param Renderer $backend
     * @return void
     */
    public static function registerRenderer(
Renderer $backend) : void
    {
        \Xberg\XbergApi::registerRenderer($backend); // delegate to native extension class
    }
    /**
     * unregisterRenderer.
     *
     * @param string $name
     * @return void
     */
    public static function unregisterRenderer(
string $name) : void
    {
        \Xberg\XbergApi::unregisterRenderer($name); // delegate to native extension class
    }
    /**
     * clearRenderers.
     *
     * @return void
     */
    public static function clearRenderers(
) : void
    {
        \Xberg\XbergApi::clearRenderers(); // delegate to native extension class
    }
    /**
     * registerRerankerBackend.
     *
     * @param RerankerBackend $backend
     * @return void
     */
    public static function registerRerankerBackend(
RerankerBackend $backend) : void
    {
        \Xberg\XbergApi::registerRerankerBackend($backend); // delegate to native extension class
    }
    /**
     * unregisterRerankerBackend.
     *
     * @param string $name
     * @return void
     */
    public static function unregisterRerankerBackend(
string $name) : void
    {
        \Xberg\XbergApi::unregisterRerankerBackend($name); // delegate to native extension class
    }
    /**
     * clearRerankerBackends.
     *
     * @return void
     */
    public static function clearRerankerBackends(
) : void
    {
        \Xberg\XbergApi::clearRerankerBackends(); // delegate to native extension class
    }
    /**
     * registerTokenizerBackend.
     *
     * @param TokenizerBackend $backend
     * @return void
     */
    public static function registerTokenizerBackend(
TokenizerBackend $backend) : void
    {
        \Xberg\XbergApi::registerTokenizerBackend($backend); // delegate to native extension class
    }
    /**
     * unregisterTokenizerBackend.
     *
     * @param string $name
     * @return void
     */
    public static function unregisterTokenizerBackend(
string $name) : void
    {
        \Xberg\XbergApi::unregisterTokenizerBackend($name); // delegate to native extension class
    }
    /**
     * clearTokenizerBackends.
     *
     * @return void
     */
    public static function clearTokenizerBackends(
) : void
    {
        \Xberg\XbergApi::clearTokenizerBackends(); // delegate to native extension class
    }
}
