// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: code
package e2e_test

import (
	"encoding/json"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	xberg "github.com/xberg-io/xberg/packages/go"
)

func Test_CodeShebangDetection(t *testing.T) {
	// Test language detection from shebang line via bytes input
	inputMockBaseURL := os.Getenv("MOCK_SERVER_CODE_SHEBANG_DETECTION")
	if inputMockBaseURL == "" {
		inputMockBaseURL = os.Getenv("MOCK_SERVER_URL") + "/fixtures/code_shebang_detection"
	}
	inputJSON := strings.ReplaceAll(`{"kind":"uri","mime_type":"text/x-source-code","uri":"$mock_url/code/script.sh"}`, "$mock_url", inputMockBaseURL)
	var input xberg.ExtractInput
	if err := json.Unmarshal([]byte(inputJSON), &input); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	result, err := xberg.Extract(input, xberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if len(result.Results) > 0 {
		if string(result.Results[0].MimeType) != `text/x-source-code` {
			t.Errorf("equals mismatch: got %v", result.Results[0].MimeType)
		}
	}
	if len(result.Results) > 0 {
		assert.GreaterOrEqual(t, len(result.Results[0].Content), 10, "expected length >= 10")
	}
	if len(result.Results) > 0 {
		if !strings.Contains(string(result.Results[0].Content), `build`) {
			t.Errorf("expected to contain %s", `build`)
		}
		if !strings.Contains(string(result.Results[0].Content), `clean`) {
			t.Errorf("expected to contain %s", `clean`)
		}
	}
}
